
"""
fortisapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from fortisapi.api_helper import APIHelper
from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class PaymentCardReaderTokenControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.payment_card_reader_token
        cls.response_catcher = cls.controller.http_call_back

    def test_payment_card_reader_token_request(self):
        """
        For initializing iPhone card readers for Apple Tap to Pay transactions .
        """
        # Parameters for the API call
        product_transaction_id = "11e95f8ec39de8fbdb0a4f1a"

        # Perform the API call through the SDK function
        result = self.controller.payment_card_reader_token_request(
            product_transaction_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize(
            "{\"type\":\"PaymentCardReaderToken\",\"data\":{}}",
        )
        received_body = APIHelper.json_deserialize(
            self.response_catcher.response.text,
        )
        assert ComparisonHelper.match_body(
            expected_body,
            received_body,
        )

