
"""
fortisapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from fortisapi.api_helper import APIHelper
from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class TagsControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.tags
        cls.response_catcher = cls.controller.http_call_back

    def test_list_all_tags_related(self):
        """
        List all tags related.
        """
        # Parameters for the API call
        page = None
        order = None
        filter_by = None
        expand = None
        format = None
        typeahead = None
        fields = None

        # Perform the API call through the SDK function
        result = self.controller.list_all_tags_related(
            page,
            order,
            filter_by,
            expand,
            format,
            typeahead,
            fields,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize(
            "{\"type\":\"TagsCollection\",\"list\":[{\"location_id\":\"11e95f8ec39de8"
            "fbdb0a4f1a\",\"title\":\"My terminal\",\"id\":\"11e95f8ec39de8fbdb0a4f1a"
            "\",\"created_ts\":1422040992,\"modified_ts\":1422040992,\"location\":{\""
            "id\":\"11e95f8ec39de8fbdb0a4f1a\",\"created_ts\":1422040992,\"modified_t"
            "s\":1422040992,\"account_number\":\"5454545454545454\",\"address\":{\"ci"
            "ty\":\"Novi\",\"state\":\"MI\",\"postal_code\":\"48375\",\"country\":\"U"
            "S\"},\"branding_domain_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"contact_email"
            "_trx_receipt_default\":true,\"default_ach\":\"11e608a7d515f1e093242bb2\""
            ",\"default_cc\":\"11e608a442a5f1e092242dda\",\"email_reply_to\":\"email@"
            "domain.com\",\"fax\":\"3339998822\",\"location_api_id\":\"location-11111"
            "1\",\"location_api_key\":\"AE34BBCAADF4AE34BBCAADF4\",\"location_c1\":\""
            "custom 1\",\"location_c2\":\"custom 2\",\"location_c3\":\"custom data 3"
            "\",\"name\":\"Sample Company Headquarters\",\"office_phone\":\"248123456"
            "7\",\"office_ext_phone\":\"1021021209\",\"tz\":\"America/New_York\",\"pa"
            "rent_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"show_contact_notes\":true,\"sho"
            "w_contact_files\":true,\"created_user_id\":\"11e95f8ec39de8fbdb0a4f1a\","
            "\"location_type\":\"merchant\",\"ticket_hash_key\":\"A5F443CADF4AE34BBCA"
            "ADF4\",\"additional_access\":{}}}],\"links\":{\"type\":\"Links\",\"first"
            "\":\"/v1/endpoint?page[size]=10&page[number]=1\",\"previous\":\"/v1/endp"
            "oint?page[size]=10&page[number]=5\",\"next\":\"/v1/endpoint?page[size]=1"
            "0&page[number]=7\",\"last\":\"/v1/endpoint?page[size]=10&page[number]=42"
            "\"},\"pagination\":{\"type\":\"Pagination\",\"total_count\":423,\"page_c"
            "ount\":42,\"page_number\":6,\"page_size\":10},\"sort\":{\"type\":\"Sorti"
            "ng\",\"fields\":[{\"field\":\"last_name\",\"order\":\"asc\"}]}}",
        )
        received_body = APIHelper.json_deserialize(
            self.response_catcher.response.text,
        )
        assert ComparisonHelper.match_body(
            expected_body,
            received_body,
        )

    def test_delete_tag_record(self):
        """
        Delete tag record.
        """
        # Parameters for the API call
        tag_id = "11e95f8ec39de8fbdb0a4f1a"

        # Perform the API call through the SDK function
        result = self.controller.delete_tag_record(
            tag_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 204
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize(
            "{\"type\":\"Tag\",\"data\":{\"location_id\":\"11e95f8ec39de8fbdb0a4f1a\""
            ",\"title\":\"My terminal\",\"id\":\"11e95f8ec39de8fbdb0a4f1a\",\"created"
            "_ts\":1422040992,\"modified_ts\":1422040992,\"location\":{\"id\":\"11e95"
            "f8ec39de8fbdb0a4f1a\",\"created_ts\":1422040992,\"modified_ts\":14220409"
            "92,\"account_number\":\"5454545454545454\",\"address\":{\"city\":\"Novi"
            "\",\"state\":\"MI\",\"postal_code\":\"48375\",\"country\":\"US\"},\"bran"
            "ding_domain_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"contact_email_trx_receip"
            "t_default\":true,\"default_ach\":\"11e608a7d515f1e093242bb2\",\"default_"
            "cc\":\"11e608a442a5f1e092242dda\",\"email_reply_to\":\"email@domain.com"
            "\",\"fax\":\"3339998822\",\"location_api_id\":\"location-111111\",\"loca"
            "tion_api_key\":\"AE34BBCAADF4AE34BBCAADF4\",\"location_c1\":\"custom 1\""
            ",\"location_c2\":\"custom 2\",\"location_c3\":\"custom data 3\",\"name\""
            ":\"Sample Company Headquarters\",\"office_phone\":\"2481234567\",\"offic"
            "e_ext_phone\":\"1021021209\",\"tz\":\"America/New_York\",\"parent_id\":"
            "\"11e95f8ec39de8fbdb0a4f1a\",\"show_contact_notes\":true,\"show_contact_"
            "files\":true,\"created_user_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"location"
            "_type\":\"merchant\",\"ticket_hash_key\":\"A5F443CADF4AE34BBCAADF4\",\"a"
            "dditional_access\":{}}}}",
        )
        received_body = APIHelper.json_deserialize(
            self.response_catcher.response.text,
        )
        assert ComparisonHelper.match_body(
            expected_body,
            received_body,
        )

    def test_view_single_tags_record(self):
        """
        View single tags record.
        """
        # Parameters for the API call
        tag_id = "11e95f8ec39de8fbdb0a4f1a"
        expand = None
        fields = None

        # Perform the API call through the SDK function
        result = self.controller.view_single_tags_record(
            tag_id,
            expand,
            fields,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize(
            "{\"type\":\"Tag\",\"data\":{\"location_id\":\"11e95f8ec39de8fbdb0a4f1a\""
            ",\"title\":\"My terminal\",\"id\":\"11e95f8ec39de8fbdb0a4f1a\",\"created"
            "_ts\":1422040992,\"modified_ts\":1422040992,\"location\":{\"id\":\"11e95"
            "f8ec39de8fbdb0a4f1a\",\"created_ts\":1422040992,\"modified_ts\":14220409"
            "92,\"account_number\":\"5454545454545454\",\"address\":{\"city\":\"Novi"
            "\",\"state\":\"MI\",\"postal_code\":\"48375\",\"country\":\"US\"},\"bran"
            "ding_domain_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"contact_email_trx_receip"
            "t_default\":true,\"default_ach\":\"11e608a7d515f1e093242bb2\",\"default_"
            "cc\":\"11e608a442a5f1e092242dda\",\"email_reply_to\":\"email@domain.com"
            "\",\"fax\":\"3339998822\",\"location_api_id\":\"location-111111\",\"loca"
            "tion_api_key\":\"AE34BBCAADF4AE34BBCAADF4\",\"location_c1\":\"custom 1\""
            ",\"location_c2\":\"custom 2\",\"location_c3\":\"custom data 3\",\"name\""
            ":\"Sample Company Headquarters\",\"office_phone\":\"2481234567\",\"offic"
            "e_ext_phone\":\"1021021209\",\"tz\":\"America/New_York\",\"parent_id\":"
            "\"11e95f8ec39de8fbdb0a4f1a\",\"show_contact_notes\":true,\"show_contact_"
            "files\":true,\"created_user_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"location"
            "_type\":\"merchant\",\"ticket_hash_key\":\"A5F443CADF4AE34BBCAADF4\",\"a"
            "dditional_access\":{}}}}",
        )
        received_body = APIHelper.json_deserialize(
            self.response_catcher.response.text,
        )
        assert ComparisonHelper.match_body(
            expected_body,
            received_body,
        )

