
"""
fortisapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from fortisapi.api_helper import APIHelper
from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class M3DSTransactionsControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.m3_ds_transactions
        cls.response_catcher = cls.controller.http_call_back

    def test_3_ds_transactions_request(self):
        """
        For getting results of successful 3DS authentication attempts.
        """
        # Parameters for the API call
        three_ds_server_trans_id = "516ef0bf-e510-4895-b0a8-c889f2eaf471"
        product_transaction_id = "11e95f8ec39de8fbdb0a4f1a"

        # Perform the API call through the SDK function
        result = self.controller.m3_ds_transactions_request(
            three_ds_server_trans_id,
            product_transaction_id,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize(
            "{\"type\":\"ThreeDSTransaction\",\"data\":{\"three_ds_server_trans_id\":"
            "\"516ef0bf-e510-4895-b0a8-c889f2eaf471\",\"transaction_status\":\"Y\",\""
            "ds_trans_id\":\"f25084f0-5b16-4c0a-ae5d-b24808a95e4b\",\"acs_trans_id\":"
            "\"d7c1ee99-9478-44a6-b1f2-391e29c6b340\",\"message_version\":\"2.2.0\","
            "\"authentication_value\":\"MTIzNDU2Nzg5MDA5ODc2NTQzMjE=\",\"eci\":\"05\""
            "}}",
        )
        received_body = APIHelper.json_deserialize(
            self.response_catcher.response.text,
        )
        assert ComparisonHelper.match_body(
            expected_body,
            received_body,
        )

