
"""
fortisapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from apimatic_core.utilities.comparison_helper import (
    ComparisonHelper,
)

from fortisapi.api_helper import APIHelper
from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class DeviceTermsControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.device_terms
        cls.response_catcher = cls.controller.http_call_back

    def test_list_all_device_terms_related(self):
        """
        List all device terms related.
        """
        # Parameters for the API call
        page = None
        order = None
        filter_by = None
        expand = None
        format = None
        typeahead = None
        fields = None

        # Perform the API call through the SDK function
        result = self.controller.list_all_device_terms_related(
            page,
            order,
            filter_by,
            expand,
            format,
            typeahead,
            fields,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize(
            "{\"type\":\"DeviceTermsCollection\",\"list\":[{\"location_id\":\"11e95f8"
            "ec39de8fbdb0a4f1a\",\"terminal_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"requi"
            "re_signature\":true,\"device_term_api_id\":\"device_term134\",\"terms_co"
            "nditions\":\"FUNgib0Vh0B9c0Wbttvr50vNtGLOkTdFL0eFmhN1RJpKhK14IENeDa8irp2"
            "dEk9thEcVHvVEyriQeZLs5NjNsCzqNj9JDA4RSJwK647IFtYjrNPN1nBb9bw6hoQ71oT5kps"
            "iXGt8HcqBFVBVeDA7psIzKAyDveAw2o1hfjipkOtXrPgWun0rYwyyFuvqkT1egQYKfYDj\","
            "\"id\":\"11e95f8ec39de8fbdb0a4f1a\",\"reason_code_id\":1000,\"signature"
            "\":{\"signature\":\"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAYAAAAOyNaYAAACvklE"
            "QVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4OIXtaXw2H3"
            "/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYVVW6"
            "WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8"
            "A8FNrCzLm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWO"
            "Y83zXOu6vnqfeQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRF"
            "WhSFRlHUrmr7/b4NLU3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoY"
            "hjdnPKJzD8E5xjyT647T6aSr1UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/"
            "Z82K1z/jca5zB8F9wFBQY6JaLBYax7EmSXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTD"
            "GrNK3YsqTdNRn69pGs2y7NshssV0w2yCK4pCRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7ptt1ui"
            "c8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk7s1wR371z1zPnKlbDGuvc9TKKz"
            "78cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+SlRj9L8ALcJ/lNsym+DO"
            "5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDcERxgEcEBFhEc"
            "YBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGDRX+EC"
            "0ah++pNrAAAAAElFTkSuQmCC\",\"resource\":\"Transaction\",\"resource_id\":"
            "\"11e95f8ec39de8fbdb0a4f1a\",\"id\":\"11e95f8ec39de8fbdb0a4f1a\",\"creat"
            "ed_ts\":1422040992,\"modified_ts\":1422040992},\"created_ts\":1422040992"
            ",\"modified_ts\":1422040992,\"created_user_id\":\"11e95f8ec39de8fbdb0a4f"
            "1a\",\"created_user\":{\"account_number\":\"5454545454545454\",\"brandin"
            "g_domain_url\":\"{branding_domain_url}\",\"cell_phone\":\"3339998822\","
            "\"company_name\":\"Fortis Payment Systems, LLC\",\"contact_id\":\"11e95f"
            "8ec39de8fbdb0a4f1a\",\"date_of_birth\":\"2021-12-01\",\"domain_id\":\"11"
            "e95f8ec39de8fbdb0a4f1a\",\"email\":\"email@domain.com\",\"email_trx_rece"
            "ipt\":true,\"home_phone\":\"3339998822\",\"first_name\":\"John\",\"last_"
            "name\":\"Smith\",\"locale\":\"en-US\",\"office_phone\":\"3339998822\",\""
            "office_ext_phone\":\"5\",\"primary_location_id\":\"11e95f8ec39de8fbdb0a4"
            "f1a\",\"requires_new_password\":null,\"terms_condition_code\":\"20220308"
            "\",\"tz\":\"America/New_York\",\"ui_prefs\":{\"entry_page\":\"dashboard"
            "\",\"page_size\":2,\"report_export_type\":\"csv\",\"process_method\":\"v"
            "irtual_terminal\",\"default_terminal\":\"11e95f8ec39de8fbdb0a4f1a\"},\"u"
            "sername\":\"{user_name}\",\"user_api_key\":\"234bas8dfn8238f923w2\",\"us"
            "er_hash_key\":null,\"user_type_code\":100,\"password\":null,\"zip\":\"48"
            "375\",\"location_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"status_code\":1,\"a"
            "pi_only\":false,\"is_invitation\":false,\"address\":{\"city\":\"Novi\","
            "\"state\":\"MI\",\"postal_code\":\"48375\",\"country\":\"US\"},\"id\":\""
            "11e95f8ec39de8fbdb0a4f1a\",\"status\":true,\"login_attempts\":0,\"last_l"
            "ogin_ts\":1422040992,\"created_ts\":1422040992,\"modified_ts\":142204099"
            "2,\"created_user_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"terms_accepted_ts\""
            ":1422040992,\"terms_agree_ip\":\"192.168.0.10\",\"current_date_time\":\""
            "2019-03-11T10:38:26-0700\",\"current_login\":1422040992,\"log_api_respon"
            "se_body_ts\":1422040992},\"location\":{\"id\":\"11e95f8ec39de8fbdb0a4f1a"
            "\",\"created_ts\":1422040992,\"modified_ts\":1422040992,\"account_number"
            "\":\"5454545454545454\",\"address\":{\"city\":\"Novi\",\"state\":\"MI\","
            "\"postal_code\":\"48375\",\"country\":\"US\"},\"branding_domain_id\":\"1"
            "1e95f8ec39de8fbdb0a4f1a\",\"contact_email_trx_receipt_default\":true,\"d"
            "efault_ach\":\"11e608a7d515f1e093242bb2\",\"default_cc\":\"11e608a442a5f"
            "1e092242dda\",\"email_reply_to\":\"email@domain.com\",\"fax\":\"33399988"
            "22\",\"location_api_id\":\"location-111111\",\"location_api_key\":\"AE34"
            "BBCAADF4AE34BBCAADF4\",\"location_c1\":\"custom 1\",\"location_c2\":\"cu"
            "stom 2\",\"location_c3\":\"custom data 3\",\"name\":\"Sample Company Hea"
            "dquarters\",\"office_phone\":\"2481234567\",\"office_ext_phone\":\"10210"
            "21209\",\"tz\":\"America/New_York\",\"parent_id\":\"11e95f8ec39de8fbdb0a"
            "4f1a\",\"show_contact_notes\":true,\"show_contact_files\":true,\"created"
            "_user_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"location_type\":\"merchant\","
            "\"ticket_hash_key\":\"A5F443CADF4AE34BBCAADF4\",\"additional_access\":{}"
            "},\"terminal\":{\"location_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"default_p"
            "roduct_transaction_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"terminal_applicat"
            "ion_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"terminal_cvm_id\":\"11e95f8ec39d"
            "e8fbdb0a4f1a\",\"terminal_manufacturer_code\":\"1\",\"title\":\"My termi"
            "nal\",\"mac_address\":\"3D:F2:C9:A6:B3:4F\",\"local_ip_address\":\"192.1"
            "68.0.10\",\"port\":10009,\"serial_number\":\"1234567890\",\"terminal_num"
            "ber\":\"973456789012367\",\"terminal_timeouts\":{\"card_entry_timeout\":"
            "47,\"device_terms_prompt_timeout\":30,\"overall_timeout\":125,\"pin_entr"
            "y_timeout\":40,\"signature_input_timeout\":35,\"signature_submit_timeout"
            "\":38,\"status_display_time\":12,\"tip_cashback_timeout\":25,\"transacti"
            "on_timeout\":17},\"tip_percents\":{\"percent_1\":0,\"percent_2\":2,\"per"
            "cent_3\":99},\"header_line_1\":\"line 1 sample\",\"header_line_2\":\"lin"
            "e 2 sample\",\"header_line_3\":\"line 3 sample\",\"header_line_4\":\"lin"
            "e 4 sample\",\"header_line_5\":\"line 5 sample\",\"trailer_line_1\":\"tr"
            "ailer 1 sample\",\"trailer_line_2\":\"trailer 2 sample\",\"trailer_line_"
            "3\":\"trailer 3 sample\",\"trailer_line_4\":\"trailer 4 sample\",\"trail"
            "er_line_5\":\"trailer 5 sample\",\"default_checkin\":\"2021-12-01\",\"de"
            "fault_checkout\":\"2021-12-01\",\"default_room_rate\":56,\"default_room_"
            "number\":\"303\",\"debit\":false,\"emv\":false,\"cashback_enable\":false"
            ",\"print_enable\":false,\"sig_capture_enable\":false,\"is_provisioned\":"
            "false,\"tip_enable\":false,\"validated_decryption\":false,\"communicatio"
            "n_type\":\"http\",\"active\":true,\"id\":\"11e95f8ec39de8fbdb0a4f1a\",\""
            "created_ts\":1422040992,\"modified_ts\":1422040992,\"last_registration_t"
            "s\":1422040992,\"created_user_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"modifi"
            "ed_user_id\":\"11e95f8ec39de8fbdb0a4f1a\"},\"changelogs\":[{\"id\":\"11e"
            "95f8ec39de8fbdb0a4f1a\",\"created_ts\":1422040992,\"action\":\"CREATE\","
            "\"model\":\"TransactionRequest\",\"model_id\":\"11ec829598f0d4008be9aba4"
            "\",\"user_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"changelog_details\":[{\"id"
            "\":\"11e95f8ec39de8fbdb0a4f1a\",\"changelog_id\":\"11e95f8ec39de8fbdb0a4"
            "f1a\",\"field\":\"next_run_ts\",\"old_value\":\"1643616000\"}],\"user\":"
            "{\"id\":\"11e95f8ec39de8fbdb0a4f1a\",\"username\":\"email@domain.com\","
            "\"first_name\":\"Bob\",\"last_name\":\"Fairview\"}}],\"reason_code\":{\""
            "id\":50,\"title\":\"Sample Title\"}}],\"links\":{\"type\":\"Links\",\"fi"
            "rst\":\"/v1/endpoint?page[size]=10&page[number]=1\",\"previous\":\"/v1/e"
            "ndpoint?page[size]=10&page[number]=5\",\"next\":\"/v1/endpoint?page[size"
            "]=10&page[number]=7\",\"last\":\"/v1/endpoint?page[size]=10&page[number]"
            "=42\"},\"pagination\":{\"type\":\"Pagination\",\"total_count\":423,\"pag"
            "e_count\":42,\"page_number\":6,\"page_size\":10},\"sort\":{\"type\":\"So"
            "rting\",\"fields\":[{\"field\":\"last_name\",\"order\":\"asc\"}]}}",
        )
        received_body = APIHelper.json_deserialize(
            self.response_catcher.response.text,
        )
        assert ComparisonHelper.match_body(
            expected_body,
            received_body,
        )

    def test_view_single_device_term_record(self):
        """
        View single device term record.
        """
        # Parameters for the API call
        device_terms_id = "11e95f8ec39de8fbdb0a4f1a"
        expand = None
        fields = None

        # Perform the API call through the SDK function
        result = self.controller.view_single_device_term_record(
            device_terms_id,
            expand,
            fields,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200
        # Test headers
        expected_headers = {
            "content-type": "application/json",
        }

        assert ComparisonHelper.match_headers(
            expected_headers,
            self.response_catcher.response.headers,
        )
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize(
            "{\"type\":\"DeviceTerm\",\"data\":{\"location_id\":\"11e95f8ec39de8fbdb0"
            "a4f1a\",\"terminal_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"require_signature"
            "\":true,\"device_term_api_id\":\"device_term134\",\"terms_conditions\":"
            "\"FUNgib0Vh0B9c0Wbttvr50vNtGLOkTdFL0eFmhN1RJpKhK14IENeDa8irp2dEk9thEcVHv"
            "VEyriQeZLs5NjNsCzqNj9JDA4RSJwK647IFtYjrNPN1nBb9bw6hoQ71oT5kpsiXGt8HcqBFV"
            "BVeDA7psIzKAyDveAw2o1hfjipkOtXrPgWun0rYwyyFuvqkT1egQYKfYDj\",\"id\":\"11"
            "e95f8ec39de8fbdb0a4f1a\",\"reason_code_id\":1000,\"signature\":{\"signat"
            "ure\":\"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAYAAAAOyNaYAAACvklEQVR4nO3bLZOq"
            "UBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4OIXtaXw2H3/5s5MwZ39rgz"
            "/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYVVW6WCxURDTLsqmn"
            "gzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8A8FNrCzLm5j6"
            "8Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu6vnqf"
            "eQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7"
            "/b4NLU3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5"
            "xjyT647T6aSr1UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5z"
            "B8F9wFBQY6JaLBYax7EmSXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNR"
            "n69pGs2y7NshssV0w2yCK4pCRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8BsgsvzXEVE"
            "D4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk7s1wR371z1zPnKlbDGuvc9TKKz78cE9yio3W43"
            "6vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+SlRj9L8ALcJ/lNsym+DO5/PTQaVpqnVd"
            "T/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDcERxgEcEBFhEcYBHBARYRHGAR"
            "wQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGDRX+EC0ah++pNrAAAA"
            "AElFTkSuQmCC\",\"resource\":\"Transaction\",\"resource_id\":\"11e95f8ec3"
            "9de8fbdb0a4f1a\",\"id\":\"11e95f8ec39de8fbdb0a4f1a\",\"created_ts\":1422"
            "040992,\"modified_ts\":1422040992},\"created_ts\":1422040992,\"modified_"
            "ts\":1422040992,\"created_user_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"creat"
            "ed_user\":{\"account_number\":\"5454545454545454\",\"branding_domain_url"
            "\":\"{branding_domain_url}\",\"cell_phone\":\"3339998822\",\"company_nam"
            "e\":\"Fortis Payment Systems, LLC\",\"contact_id\":\"11e95f8ec39de8fbdb0"
            "a4f1a\",\"date_of_birth\":\"2021-12-01\",\"domain_id\":\"11e95f8ec39de8f"
            "bdb0a4f1a\",\"email\":\"email@domain.com\",\"email_trx_receipt\":true,\""
            "home_phone\":\"3339998822\",\"first_name\":\"John\",\"last_name\":\"Smit"
            "h\",\"locale\":\"en-US\",\"office_phone\":\"3339998822\",\"office_ext_ph"
            "one\":\"5\",\"primary_location_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"requi"
            "res_new_password\":null,\"terms_condition_code\":\"20220308\",\"tz\":\"A"
            "merica/New_York\",\"ui_prefs\":{\"entry_page\":\"dashboard\",\"page_size"
            "\":2,\"report_export_type\":\"csv\",\"process_method\":\"virtual_termina"
            "l\",\"default_terminal\":\"11e95f8ec39de8fbdb0a4f1a\"},\"username\":\"{u"
            "ser_name}\",\"user_api_key\":\"234bas8dfn8238f923w2\",\"user_hash_key\":"
            "null,\"user_type_code\":100,\"password\":null,\"zip\":\"48375\",\"locati"
            "on_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"status_code\":1,\"api_only\":fals"
            "e,\"is_invitation\":false,\"address\":{\"city\":\"Novi\",\"state\":\"MI"
            "\",\"postal_code\":\"48375\",\"country\":\"US\"},\"id\":\"11e95f8ec39de8"
            "fbdb0a4f1a\",\"status\":true,\"login_attempts\":0,\"last_login_ts\":1422"
            "040992,\"created_ts\":1422040992,\"modified_ts\":1422040992,\"created_us"
            "er_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"terms_accepted_ts\":1422040992,\""
            "terms_agree_ip\":\"192.168.0.10\",\"current_date_time\":\"2019-03-11T10:"
            "38:26-0700\",\"current_login\":1422040992,\"log_api_response_body_ts\":1"
            "422040992},\"location\":{\"id\":\"11e95f8ec39de8fbdb0a4f1a\",\"created_t"
            "s\":1422040992,\"modified_ts\":1422040992,\"account_number\":\"545454545"
            "4545454\",\"address\":{\"city\":\"Novi\",\"state\":\"MI\",\"postal_code"
            "\":\"48375\",\"country\":\"US\"},\"branding_domain_id\":\"11e95f8ec39de8"
            "fbdb0a4f1a\",\"contact_email_trx_receipt_default\":true,\"default_ach\":"
            "\"11e608a7d515f1e093242bb2\",\"default_cc\":\"11e608a442a5f1e092242dda\""
            ",\"email_reply_to\":\"email@domain.com\",\"fax\":\"3339998822\",\"locati"
            "on_api_id\":\"location-111111\",\"location_api_key\":\"AE34BBCAADF4AE34B"
            "BCAADF4\",\"location_c1\":\"custom 1\",\"location_c2\":\"custom 2\",\"lo"
            "cation_c3\":\"custom data 3\",\"name\":\"Sample Company Headquarters\","
            "\"office_phone\":\"2481234567\",\"office_ext_phone\":\"1021021209\",\"tz"
            "\":\"America/New_York\",\"parent_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"sho"
            "w_contact_notes\":true,\"show_contact_files\":true,\"created_user_id\":"
            "\"11e95f8ec39de8fbdb0a4f1a\",\"location_type\":\"merchant\",\"ticket_has"
            "h_key\":\"A5F443CADF4AE34BBCAADF4\",\"additional_access\":{}},\"terminal"
            "\":{\"location_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"default_product_trans"
            "action_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"terminal_application_id\":\"1"
            "1e95f8ec39de8fbdb0a4f1a\",\"terminal_cvm_id\":\"11e95f8ec39de8fbdb0a4f1a"
            "\",\"terminal_manufacturer_code\":\"1\",\"title\":\"My terminal\",\"mac_"
            "address\":\"3D:F2:C9:A6:B3:4F\",\"local_ip_address\":\"192.168.0.10\",\""
            "port\":10009,\"serial_number\":\"1234567890\",\"terminal_number\":\"9734"
            "56789012367\",\"terminal_timeouts\":{\"card_entry_timeout\":47,\"device_"
            "terms_prompt_timeout\":30,\"overall_timeout\":125,\"pin_entry_timeout\":"
            "40,\"signature_input_timeout\":35,\"signature_submit_timeout\":38,\"stat"
            "us_display_time\":12,\"tip_cashback_timeout\":25,\"transaction_timeout\""
            ":17},\"tip_percents\":{\"percent_1\":0,\"percent_2\":2,\"percent_3\":99}"
            ",\"header_line_1\":\"line 1 sample\",\"header_line_2\":\"line 2 sample\""
            ",\"header_line_3\":\"line 3 sample\",\"header_line_4\":\"line 4 sample\""
            ",\"header_line_5\":\"line 5 sample\",\"trailer_line_1\":\"trailer 1 samp"
            "le\",\"trailer_line_2\":\"trailer 2 sample\",\"trailer_line_3\":\"traile"
            "r 3 sample\",\"trailer_line_4\":\"trailer 4 sample\",\"trailer_line_5\":"
            "\"trailer 5 sample\",\"default_checkin\":\"2021-12-01\",\"default_checko"
            "ut\":\"2021-12-01\",\"default_room_rate\":56,\"default_room_number\":\"3"
            "03\",\"debit\":false,\"emv\":false,\"cashback_enable\":false,\"print_ena"
            "ble\":false,\"sig_capture_enable\":false,\"is_provisioned\":false,\"tip_"
            "enable\":false,\"validated_decryption\":false,\"communication_type\":\"h"
            "ttp\",\"active\":true,\"id\":\"11e95f8ec39de8fbdb0a4f1a\",\"created_ts\""
            ":1422040992,\"modified_ts\":1422040992,\"last_registration_ts\":14220409"
            "92,\"created_user_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"modified_user_id\""
            ":\"11e95f8ec39de8fbdb0a4f1a\"},\"changelogs\":[{\"id\":\"11e95f8ec39de8f"
            "bdb0a4f1a\",\"created_ts\":1422040992,\"action\":\"CREATE\",\"model\":\""
            "TransactionRequest\",\"model_id\":\"11ec829598f0d4008be9aba4\",\"user_id"
            "\":\"11e95f8ec39de8fbdb0a4f1a\",\"changelog_details\":[{\"id\":\"11e95f8"
            "ec39de8fbdb0a4f1a\",\"changelog_id\":\"11e95f8ec39de8fbdb0a4f1a\",\"fiel"
            "d\":\"next_run_ts\",\"old_value\":\"1643616000\"}],\"user\":{\"id\":\"11"
            "e95f8ec39de8fbdb0a4f1a\",\"username\":\"email@domain.com\",\"first_name"
            "\":\"Bob\",\"last_name\":\"Fairview\"}}],\"reason_code\":{\"id\":50,\"ti"
            "tle\":\"Sample Title\"}}}",
        )
        received_body = APIHelper.json_deserialize(
            self.response_catcher.response.text,
        )
        assert ComparisonHelper.match_body(
            expected_body,
            received_body,
        )

