"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper


class AccountInfo1(object):
    """Implementation of the 'AccountInfo1' model.

    Attributes:
        ch_acc_age_ind (ChAccAgeInd): The model property of type ChAccAgeInd.
        ch_acc_date (str): Date converted into UTC that the cardholder opened the
            account with the 3DS Requestor. Date format = YYYYMMDD.
        ch_acc_change_ind (ChAccChangeInd): The model property of type ChAccChangeInd.
        ch_acc_change (str): Date converted into UTC that the cardholder's account
            with the 3DS Requestor was last changed. Including Billing or Shipping
            address, new payment account, or new user(s) added. Date format =
            YYYYMMDD.
        ch_acc_pw_change_ind (ChAccPwChangeInd): The model property of type
            ChAccPwChangeInd.
        ch_acc_pw_change (str): Date converted into UTC that cardholder's account
            with the 3DS Requestor had a password change or account reset. Date
            format must be YYYYMMDD.
        ship_address_usage_ind (ShipAddressUsageInd): The model property of type
            ShipAddressUsageInd.
        ship_address_usage (str): Date converted into UTC when the shipping address
            used for this transaction was first used with the 3DS Requestor. Date
            format must be YYYYMMDD.
        txn_activity_day (int): Number of transactions (successful and abandoned) for
            this cardholder account with the 3DS Requestor across all payment
            accounts in the previous 24 hours.
        txn_activity_year (int): Number of transactions (successful and abandoned)
            for this cardholder account with the 3DS Requestor across all payment
            accounts in the previous year.
        provision_attempts_day (int): Number of Add Card attempts in the last 24
            hours.
        nb_purchase_account (int): Number of purchases with this cardholder account
            during the previous six months.
        suspicious_acc_activity (SuspiciousAccActivity): The model property of type
            SuspiciousAccActivity.
        ship_name_indicator (ShipNameIndicator): The model property of type
            ShipNameIndicator.
        payment_acc_ind (PaymentAccInd): The model property of type PaymentAccInd.
        payment_acc_age (str): Date converted into UTC that the payment account was
            enrolled in the cardholder's account with the 3DS Requestor. Date format
            must be YYYYMMDD.
        ch_acc_req_id (str): The 3DS Requestor assigned account identifier of the
            transacting Cardholder. This identifier is a unique representation of the
            account identifier for the 3DS Requestor and is provided as a String.
            This field is supported in Starting from EMV 3DS 2.3.1 and later.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ch_acc_age_ind": "ch_acc_age_ind",
        "ch_acc_date": "ch_acc_date",
        "ch_acc_change_ind": "ch_acc_change_ind",
        "ch_acc_change": "ch_acc_change",
        "ch_acc_pw_change_ind": "ch_acc_pw_change_ind",
        "ch_acc_pw_change": "ch_acc_pw_change",
        "ship_address_usage_ind": "ship_address_usage_ind",
        "ship_address_usage": "ship_address_usage",
        "txn_activity_day": "txn_activity_day",
        "txn_activity_year": "txn_activity_year",
        "provision_attempts_day": "provision_attempts_day",
        "nb_purchase_account": "nb_purchase_account",
        "suspicious_acc_activity": "suspicious_acc_activity",
        "ship_name_indicator": "ship_name_indicator",
        "payment_acc_ind": "payment_acc_ind",
        "payment_acc_age": "payment_acc_age",
        "ch_acc_req_id": "ch_acc_req_id",
    }

    _optionals = [
        "ch_acc_age_ind",
        "ch_acc_date",
        "ch_acc_change_ind",
        "ch_acc_change",
        "ch_acc_pw_change_ind",
        "ch_acc_pw_change",
        "ship_address_usage_ind",
        "ship_address_usage",
        "txn_activity_day",
        "txn_activity_year",
        "provision_attempts_day",
        "nb_purchase_account",
        "suspicious_acc_activity",
        "ship_name_indicator",
        "payment_acc_ind",
        "payment_acc_age",
        "ch_acc_req_id",
    ]

    _nullables = [
        "ch_acc_req_id",
    ]

    def __init__(
        self,
        ch_acc_age_ind=APIHelper.SKIP,
        ch_acc_date=APIHelper.SKIP,
        ch_acc_change_ind=APIHelper.SKIP,
        ch_acc_change=APIHelper.SKIP,
        ch_acc_pw_change_ind=APIHelper.SKIP,
        ch_acc_pw_change=APIHelper.SKIP,
        ship_address_usage_ind=APIHelper.SKIP,
        ship_address_usage=APIHelper.SKIP,
        txn_activity_day=APIHelper.SKIP,
        txn_activity_year=APIHelper.SKIP,
        provision_attempts_day=APIHelper.SKIP,
        nb_purchase_account=APIHelper.SKIP,
        suspicious_acc_activity=APIHelper.SKIP,
        ship_name_indicator=APIHelper.SKIP,
        payment_acc_ind=APIHelper.SKIP,
        payment_acc_age=APIHelper.SKIP,
        ch_acc_req_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AccountInfo1 instance."""
        # Initialize members of the class
        if ch_acc_age_ind is not APIHelper.SKIP:
            self.ch_acc_age_ind = ch_acc_age_ind
        if ch_acc_date is not APIHelper.SKIP:
            self.ch_acc_date = ch_acc_date
        if ch_acc_change_ind is not APIHelper.SKIP:
            self.ch_acc_change_ind = ch_acc_change_ind
        if ch_acc_change is not APIHelper.SKIP:
            self.ch_acc_change = ch_acc_change
        if ch_acc_pw_change_ind is not APIHelper.SKIP:
            self.ch_acc_pw_change_ind = ch_acc_pw_change_ind
        if ch_acc_pw_change is not APIHelper.SKIP:
            self.ch_acc_pw_change = ch_acc_pw_change
        if ship_address_usage_ind is not APIHelper.SKIP:
            self.ship_address_usage_ind = ship_address_usage_ind
        if ship_address_usage is not APIHelper.SKIP:
            self.ship_address_usage = ship_address_usage
        if txn_activity_day is not APIHelper.SKIP:
            self.txn_activity_day = txn_activity_day
        if txn_activity_year is not APIHelper.SKIP:
            self.txn_activity_year = txn_activity_year
        if provision_attempts_day is not APIHelper.SKIP:
            self.provision_attempts_day = provision_attempts_day
        if nb_purchase_account is not APIHelper.SKIP:
            self.nb_purchase_account = nb_purchase_account
        if suspicious_acc_activity is not APIHelper.SKIP:
            self.suspicious_acc_activity = suspicious_acc_activity
        if ship_name_indicator is not APIHelper.SKIP:
            self.ship_name_indicator = ship_name_indicator
        if payment_acc_ind is not APIHelper.SKIP:
            self.payment_acc_ind = payment_acc_ind
        if payment_acc_age is not APIHelper.SKIP:
            self.payment_acc_age = payment_acc_age
        if ch_acc_req_id is not APIHelper.SKIP:
            self.ch_acc_req_id = ch_acc_req_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        ch_acc_age_ind =\
            dictionary.get("ch_acc_age_ind")\
            if dictionary.get("ch_acc_age_ind")\
                else APIHelper.SKIP
        ch_acc_date =\
            dictionary.get("ch_acc_date")\
            if dictionary.get("ch_acc_date")\
                else APIHelper.SKIP
        ch_acc_change_ind =\
            dictionary.get("ch_acc_change_ind")\
            if dictionary.get("ch_acc_change_ind")\
                else APIHelper.SKIP
        ch_acc_change =\
            dictionary.get("ch_acc_change")\
            if dictionary.get("ch_acc_change")\
                else APIHelper.SKIP
        ch_acc_pw_change_ind =\
            dictionary.get("ch_acc_pw_change_ind")\
            if dictionary.get("ch_acc_pw_change_ind")\
                else APIHelper.SKIP
        ch_acc_pw_change =\
            dictionary.get("ch_acc_pw_change")\
            if dictionary.get("ch_acc_pw_change")\
                else APIHelper.SKIP
        ship_address_usage_ind =\
            dictionary.get("ship_address_usage_ind")\
            if dictionary.get("ship_address_usage_ind")\
                else APIHelper.SKIP
        ship_address_usage =\
            dictionary.get("ship_address_usage")\
            if dictionary.get("ship_address_usage")\
                else APIHelper.SKIP
        txn_activity_day =\
            dictionary.get("txn_activity_day")\
            if dictionary.get("txn_activity_day")\
                else APIHelper.SKIP
        txn_activity_year =\
            dictionary.get("txn_activity_year")\
            if dictionary.get("txn_activity_year")\
                else APIHelper.SKIP
        provision_attempts_day =\
            dictionary.get("provision_attempts_day")\
            if dictionary.get("provision_attempts_day")\
                else APIHelper.SKIP
        nb_purchase_account =\
            dictionary.get("nb_purchase_account")\
            if dictionary.get("nb_purchase_account")\
                else APIHelper.SKIP
        suspicious_acc_activity =\
            dictionary.get("suspicious_acc_activity")\
            if dictionary.get("suspicious_acc_activity")\
                else APIHelper.SKIP
        ship_name_indicator =\
            dictionary.get("ship_name_indicator")\
            if dictionary.get("ship_name_indicator")\
                else APIHelper.SKIP
        payment_acc_ind =\
            dictionary.get("payment_acc_ind")\
            if dictionary.get("payment_acc_ind")\
                else APIHelper.SKIP
        payment_acc_age =\
            dictionary.get("payment_acc_age")\
            if dictionary.get("payment_acc_age")\
                else APIHelper.SKIP
        ch_acc_req_id =\
            dictionary.get("ch_acc_req_id")\
            if "ch_acc_req_id" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(ch_acc_age_ind,
                   ch_acc_date,
                   ch_acc_change_ind,
                   ch_acc_change,
                   ch_acc_pw_change_ind,
                   ch_acc_pw_change,
                   ship_address_usage_ind,
                   ship_address_usage,
                   txn_activity_day,
                   txn_activity_year,
                   provision_attempts_day,
                   nb_purchase_account,
                   suspicious_acc_activity,
                   ship_name_indicator,
                   payment_acc_ind,
                   payment_acc_age,
                   ch_acc_req_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _ch_acc_age_ind=(
            self.ch_acc_age_ind
            if hasattr(self, "ch_acc_age_ind")
            else None
        )
        _ch_acc_date=(
            self.ch_acc_date
            if hasattr(self, "ch_acc_date")
            else None
        )
        _ch_acc_change_ind=(
            self.ch_acc_change_ind
            if hasattr(self, "ch_acc_change_ind")
            else None
        )
        _ch_acc_change=(
            self.ch_acc_change
            if hasattr(self, "ch_acc_change")
            else None
        )
        _ch_acc_pw_change_ind=(
            self.ch_acc_pw_change_ind
            if hasattr(self, "ch_acc_pw_change_ind")
            else None
        )
        _ch_acc_pw_change=(
            self.ch_acc_pw_change
            if hasattr(self, "ch_acc_pw_change")
            else None
        )
        _ship_address_usage_ind=(
            self.ship_address_usage_ind
            if hasattr(self, "ship_address_usage_ind")
            else None
        )
        _ship_address_usage=(
            self.ship_address_usage
            if hasattr(self, "ship_address_usage")
            else None
        )
        _txn_activity_day=(
            self.txn_activity_day
            if hasattr(self, "txn_activity_day")
            else None
        )
        _txn_activity_year=(
            self.txn_activity_year
            if hasattr(self, "txn_activity_year")
            else None
        )
        _provision_attempts_day=(
            self.provision_attempts_day
            if hasattr(self, "provision_attempts_day")
            else None
        )
        _nb_purchase_account=(
            self.nb_purchase_account
            if hasattr(self, "nb_purchase_account")
            else None
        )
        _suspicious_acc_activity=(
            self.suspicious_acc_activity
            if hasattr(self, "suspicious_acc_activity")
            else None
        )
        _ship_name_indicator=(
            self.ship_name_indicator
            if hasattr(self, "ship_name_indicator")
            else None
        )
        _payment_acc_ind=(
            self.payment_acc_ind
            if hasattr(self, "payment_acc_ind")
            else None
        )
        _payment_acc_age=(
            self.payment_acc_age
            if hasattr(self, "payment_acc_age")
            else None
        )
        _ch_acc_req_id=(
            self.ch_acc_req_id
            if hasattr(self, "ch_acc_req_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ch_acc_age_ind={_ch_acc_age_ind!r}, "
            f"ch_acc_date={_ch_acc_date!r}, "
            f"ch_acc_change_ind={_ch_acc_change_ind!r}, "
            f"ch_acc_change={_ch_acc_change!r}, "
            f"ch_acc_pw_change_ind={_ch_acc_pw_change_ind!r}, "
            f"ch_acc_pw_change={_ch_acc_pw_change!r}, "
            f"ship_address_usage_ind={_ship_address_usage_ind!r}, "
            f"ship_address_usage={_ship_address_usage!r}, "
            f"txn_activity_day={_txn_activity_day!r}, "
            f"txn_activity_year={_txn_activity_year!r}, "
            f"provision_attempts_day={_provision_attempts_day!r}, "
            f"nb_purchase_account={_nb_purchase_account!r}, "
            f"suspicious_acc_activity={_suspicious_acc_activity!r}, "
            f"ship_name_indicator={_ship_name_indicator!r}, "
            f"payment_acc_ind={_payment_acc_ind!r}, "
            f"payment_acc_age={_payment_acc_age!r}, "
            f"ch_acc_req_id={_ch_acc_req_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _ch_acc_age_ind=(
            self.ch_acc_age_ind
            if hasattr(self, "ch_acc_age_ind")
            else None
        )
        _ch_acc_date=(
            self.ch_acc_date
            if hasattr(self, "ch_acc_date")
            else None
        )
        _ch_acc_change_ind=(
            self.ch_acc_change_ind
            if hasattr(self, "ch_acc_change_ind")
            else None
        )
        _ch_acc_change=(
            self.ch_acc_change
            if hasattr(self, "ch_acc_change")
            else None
        )
        _ch_acc_pw_change_ind=(
            self.ch_acc_pw_change_ind
            if hasattr(self, "ch_acc_pw_change_ind")
            else None
        )
        _ch_acc_pw_change=(
            self.ch_acc_pw_change
            if hasattr(self, "ch_acc_pw_change")
            else None
        )
        _ship_address_usage_ind=(
            self.ship_address_usage_ind
            if hasattr(self, "ship_address_usage_ind")
            else None
        )
        _ship_address_usage=(
            self.ship_address_usage
            if hasattr(self, "ship_address_usage")
            else None
        )
        _txn_activity_day=(
            self.txn_activity_day
            if hasattr(self, "txn_activity_day")
            else None
        )
        _txn_activity_year=(
            self.txn_activity_year
            if hasattr(self, "txn_activity_year")
            else None
        )
        _provision_attempts_day=(
            self.provision_attempts_day
            if hasattr(self, "provision_attempts_day")
            else None
        )
        _nb_purchase_account=(
            self.nb_purchase_account
            if hasattr(self, "nb_purchase_account")
            else None
        )
        _suspicious_acc_activity=(
            self.suspicious_acc_activity
            if hasattr(self, "suspicious_acc_activity")
            else None
        )
        _ship_name_indicator=(
            self.ship_name_indicator
            if hasattr(self, "ship_name_indicator")
            else None
        )
        _payment_acc_ind=(
            self.payment_acc_ind
            if hasattr(self, "payment_acc_ind")
            else None
        )
        _payment_acc_age=(
            self.payment_acc_age
            if hasattr(self, "payment_acc_age")
            else None
        )
        _ch_acc_req_id=(
            self.ch_acc_req_id
            if hasattr(self, "ch_acc_req_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ch_acc_age_ind={_ch_acc_age_ind!s}, "
            f"ch_acc_date={_ch_acc_date!s}, "
            f"ch_acc_change_ind={_ch_acc_change_ind!s}, "
            f"ch_acc_change={_ch_acc_change!s}, "
            f"ch_acc_pw_change_ind={_ch_acc_pw_change_ind!s}, "
            f"ch_acc_pw_change={_ch_acc_pw_change!s}, "
            f"ship_address_usage_ind={_ship_address_usage_ind!s}, "
            f"ship_address_usage={_ship_address_usage!s}, "
            f"txn_activity_day={_txn_activity_day!s}, "
            f"txn_activity_year={_txn_activity_year!s}, "
            f"provision_attempts_day={_provision_attempts_day!s}, "
            f"nb_purchase_account={_nb_purchase_account!s}, "
            f"suspicious_acc_activity={_suspicious_acc_activity!s}, "
            f"ship_name_indicator={_ship_name_indicator!s}, "
            f"payment_acc_ind={_payment_acc_ind!s}, "
            f"payment_acc_age={_payment_acc_age!s}, "
            f"ch_acc_req_id={_ch_acc_req_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
