"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class AccountType16(object):
    """Implementation of the 'AccountType16' enum.

    Required for ACH transactions if account_vault_id is not provided.
    >For ACH, allowed values are 'checking' or 'savings'. For CC, this field is read
    only. The system will identify card type and generate a value for this field
    automatically. possible values are: visa, mc, disc, amex, jcb, diners, and debit.
    >

    Attributes:
        CHECKING: The enum member of type str.
        SAVINGS: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    CHECKING = "checking"

    SAVINGS = "savings"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
