"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class AcsChallengeMandated(object):
    """Implementation of the 'AcsChallengeMandated' enum.

    Indication of whether a challenge is required for the transaction to be
    authorised due to local/regional mandates or other variable.
    >Y - Challenge is mandated
    >
    >N - Challenge is not mandated
    >

    Attributes:
        Y: The enum member of type str.
        N: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    Y = "Y"

    N = "N"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
