"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper


class Address(object):
    """Implementation of the 'Address' model.

    Address of contact

    Attributes:
        city (str): City of contact
        state (str): State of contact
        postal_code (str): Postal code of contact
        country (str): The alpha 2 or alpha 3 format country code. If alpha 3 is
            provided, it will be converted to alpha 2.
        street (str): Street of contact
        additional_properties (Dict[str, object]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "city": "city",
        "state": "state",
        "postal_code": "postal_code",
        "country": "country",
        "street": "street",
    }

    _optionals = [
        "city",
        "state",
        "postal_code",
        "country",
        "street",
    ]

    _nullables = [
        "city",
        "state",
        "postal_code",
        "country",
        "street",
    ]

    def __init__(
        self,
        city=APIHelper.SKIP,
        state=APIHelper.SKIP,
        postal_code=APIHelper.SKIP,
        country=APIHelper.SKIP,
        street=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Address instance."""
        # Initialize members of the class
        if city is not APIHelper.SKIP:
            self.city = city
        if state is not APIHelper.SKIP:
            self.state = state
        if postal_code is not APIHelper.SKIP:
            self.postal_code = postal_code
        if country is not APIHelper.SKIP:
            self.country = country
        if street is not APIHelper.SKIP:
            self.street = street

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        city =\
            dictionary.get("city")\
            if "city" in dictionary.keys()\
                else APIHelper.SKIP
        state =\
            dictionary.get("state")\
            if "state" in dictionary.keys()\
                else APIHelper.SKIP
        postal_code =\
            dictionary.get("postal_code")\
            if "postal_code" in dictionary.keys()\
                else APIHelper.SKIP
        country =\
            dictionary.get("country")\
            if "country" in dictionary.keys()\
                else APIHelper.SKIP
        street =\
            dictionary.get("street")\
            if "street" in dictionary.keys()\
                else APIHelper.SKIP

        # Clean out expected properties from dictionary
        additional_properties =\
            {k: v for k, v in dictionary.items() if k not in cls._names.values()}

        # Return an object of this model
        return cls(city,
                   state,
                   postal_code,
                   country,
                   street,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _city=(
            self.city
            if hasattr(self, "city")
            else None
        )
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _street=(
            self.street
            if hasattr(self, "street")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"city={_city!r}, "
            f"state={_state!r}, "
            f"postal_code={_postal_code!r}, "
            f"country={_country!r}, "
            f"street={_street!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _city=(
            self.city
            if hasattr(self, "city")
            else None
        )
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _street=(
            self.street
            if hasattr(self, "street")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"city={_city!s}, "
            f"state={_state!s}, "
            f"postal_code={_postal_code!s}, "
            f"country={_country!s}, "
            f"street={_street!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
