"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper


class AuthRole(object):
    """Implementation of the 'AuthRole' model.

    Attributes:
        user_id (str): User ID
        auth_role_code (int): Auth Role Code
        code (int): Auth Role User Code
        created_ts (int): Created Time Stamp
        modified_ts (int): Modified Time Stamp
        created_user_id (str): System generated id for user who created record
        modified_user_id (str): System generated id for user who created record
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "user_id": "user_id",
        "auth_role_code": "auth_role_code",
        "code": "code",
        "created_ts": "created_ts",
        "modified_ts": "modified_ts",
        "created_user_id": "created_user_id",
        "modified_user_id": "modified_user_id",
    }

    _optionals = [
        "user_id",
        "auth_role_code",
        "code",
        "created_ts",
        "modified_ts",
        "created_user_id",
        "modified_user_id",
    ]

    _nullables = [
        "created_user_id",
        "modified_user_id",
    ]

    def __init__(
        self,
        user_id=APIHelper.SKIP,
        auth_role_code=APIHelper.SKIP,
        code=APIHelper.SKIP,
        created_ts=APIHelper.SKIP,
        modified_ts=APIHelper.SKIP,
        created_user_id=APIHelper.SKIP,
        modified_user_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AuthRole instance."""
        # Initialize members of the class
        if user_id is not APIHelper.SKIP:
            self.user_id = user_id
        if auth_role_code is not APIHelper.SKIP:
            self.auth_role_code = auth_role_code
        if code is not APIHelper.SKIP:
            self.code = code
        if created_ts is not APIHelper.SKIP:
            self.created_ts = created_ts
        if modified_ts is not APIHelper.SKIP:
            self.modified_ts = modified_ts
        if created_user_id is not APIHelper.SKIP:
            self.created_user_id = created_user_id
        if modified_user_id is not APIHelper.SKIP:
            self.modified_user_id = modified_user_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        user_id =\
            dictionary.get("user_id")\
            if dictionary.get("user_id")\
                else APIHelper.SKIP
        auth_role_code =\
            dictionary.get("auth_role_code")\
            if dictionary.get("auth_role_code")\
                else APIHelper.SKIP
        code =\
            dictionary.get("code")\
            if dictionary.get("code")\
                else APIHelper.SKIP
        created_ts =\
            dictionary.get("created_ts")\
            if dictionary.get("created_ts")\
                else APIHelper.SKIP
        modified_ts =\
            dictionary.get("modified_ts")\
            if dictionary.get("modified_ts")\
                else APIHelper.SKIP
        created_user_id =\
            dictionary.get("created_user_id")\
            if "created_user_id" in dictionary.keys()\
                else APIHelper.SKIP
        modified_user_id =\
            dictionary.get("modified_user_id")\
            if "modified_user_id" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(user_id,
                   auth_role_code,
                   code,
                   created_ts,
                   modified_ts,
                   created_user_id,
                   modified_user_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        _auth_role_code=(
            self.auth_role_code
            if hasattr(self, "auth_role_code")
            else None
        )
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _created_ts=(
            self.created_ts
            if hasattr(self, "created_ts")
            else None
        )
        _modified_ts=(
            self.modified_ts
            if hasattr(self, "modified_ts")
            else None
        )
        _created_user_id=(
            self.created_user_id
            if hasattr(self, "created_user_id")
            else None
        )
        _modified_user_id=(
            self.modified_user_id
            if hasattr(self, "modified_user_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"user_id={_user_id!r}, "
            f"auth_role_code={_auth_role_code!r}, "
            f"code={_code!r}, "
            f"created_ts={_created_ts!r}, "
            f"modified_ts={_modified_ts!r}, "
            f"created_user_id={_created_user_id!r}, "
            f"modified_user_id={_modified_user_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        _auth_role_code=(
            self.auth_role_code
            if hasattr(self, "auth_role_code")
            else None
        )
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _created_ts=(
            self.created_ts
            if hasattr(self, "created_ts")
            else None
        )
        _modified_ts=(
            self.modified_ts
            if hasattr(self, "modified_ts")
            else None
        )
        _created_user_id=(
            self.created_user_id
            if hasattr(self, "created_user_id")
            else None
        )
        _modified_user_id=(
            self.modified_user_id
            if hasattr(self, "modified_user_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"user_id={_user_id!s}, "
            f"auth_role_code={_auth_role_code!s}, "
            f"code={_code!s}, "
            f"created_ts={_created_ts!s}, "
            f"modified_ts={_modified_ts!s}, "
            f"created_user_id={_created_user_id!s}, "
            f"modified_user_id={_modified_user_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
