"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper


class BillingAddress13(object):
    """Implementation of the 'BillingAddress13' model.

    Attributes:
        city (str): The city of the Cardholder billing address associated with the
            card used for this purchase.  This field is required unless market or
            regional mandate restricts sending this information.
        country_code (str): The ISO 3166-1 alpha-3 or alpha-2 country of the
            Cardholder billing address associated with the card used for this
            purchase.  The field is required if Cardholder Billing Address State is
            present and unless market or regional mandate restricts sending this
            information.
        address_line_1 (str): First line of the street address or equivalent local
            portion of the Cardholder billing address associated with the card use
            for this purchase.  This field is required unless market or regional
            mandate restricts sending this information.
        address_line_2 (str): Second line of the street address or equivalent local
            portion of the Cardholder billing address associated with the card use
            for this purchase.  This field is required unless market or regional
            mandate restricts sending this information.
        address_line_3 (str): Third line of the street address or equivalent local
            portion of the Cardholder billing address associated with the card use
            for this purchase.  This field is required unless market or regional
            mandate restricts sending this information.
        postal_code (str): ZIP or other postal code of the Cardholder billing address
            associated with the card used for this purchase.  This field is required
            unless market or regional mandate restricts sending this information.
        state (str): The state or province of the Cardholder billing address
            associated with the card used for this purchase. The value should be the
            country subdivision code defined in ISO 3166-2.  This field is required
            unless State is not applicable for this country and unless market or
            regional mandate restricts sending this information.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "city": "city",
        "country_code": "country_code",
        "address_line_1": "address_line_1",
        "address_line_2": "address_line_2",
        "address_line_3": "address_line_3",
        "postal_code": "postal_code",
        "state": "state",
    }

    _optionals = [
        "city",
        "country_code",
        "address_line_1",
        "address_line_2",
        "address_line_3",
        "postal_code",
        "state",
    ]

    def __init__(
        self,
        city=APIHelper.SKIP,
        country_code=APIHelper.SKIP,
        address_line_1=APIHelper.SKIP,
        address_line_2=APIHelper.SKIP,
        address_line_3=APIHelper.SKIP,
        postal_code=APIHelper.SKIP,
        state=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a BillingAddress13 instance."""
        # Initialize members of the class
        if city is not APIHelper.SKIP:
            self.city = city
        if country_code is not APIHelper.SKIP:
            self.country_code = country_code
        if address_line_1 is not APIHelper.SKIP:
            self.address_line_1 = address_line_1
        if address_line_2 is not APIHelper.SKIP:
            self.address_line_2 = address_line_2
        if address_line_3 is not APIHelper.SKIP:
            self.address_line_3 = address_line_3
        if postal_code is not APIHelper.SKIP:
            self.postal_code = postal_code
        if state is not APIHelper.SKIP:
            self.state = state

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        city =\
            dictionary.get("city")\
            if dictionary.get("city")\
                else APIHelper.SKIP
        country_code =\
            dictionary.get("country_code")\
            if dictionary.get("country_code")\
                else APIHelper.SKIP
        address_line_1 =\
            dictionary.get("address_line_1")\
            if dictionary.get("address_line_1")\
                else APIHelper.SKIP
        address_line_2 =\
            dictionary.get("address_line_2")\
            if dictionary.get("address_line_2")\
                else APIHelper.SKIP
        address_line_3 =\
            dictionary.get("address_line_3")\
            if dictionary.get("address_line_3")\
                else APIHelper.SKIP
        postal_code =\
            dictionary.get("postal_code")\
            if dictionary.get("postal_code")\
                else APIHelper.SKIP
        state =\
            dictionary.get("state")\
            if dictionary.get("state")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(city,
                   country_code,
                   address_line_1,
                   address_line_2,
                   address_line_3,
                   postal_code,
                   state,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _city=(
            self.city
            if hasattr(self, "city")
            else None
        )
        _country_code=(
            self.country_code
            if hasattr(self, "country_code")
            else None
        )
        _address_line_1=(
            self.address_line_1
            if hasattr(self, "address_line_1")
            else None
        )
        _address_line_2=(
            self.address_line_2
            if hasattr(self, "address_line_2")
            else None
        )
        _address_line_3=(
            self.address_line_3
            if hasattr(self, "address_line_3")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"city={_city!r}, "
            f"country_code={_country_code!r}, "
            f"address_line_1={_address_line_1!r}, "
            f"address_line_2={_address_line_2!r}, "
            f"address_line_3={_address_line_3!r}, "
            f"postal_code={_postal_code!r}, "
            f"state={_state!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _city=(
            self.city
            if hasattr(self, "city")
            else None
        )
        _country_code=(
            self.country_code
            if hasattr(self, "country_code")
            else None
        )
        _address_line_1=(
            self.address_line_1
            if hasattr(self, "address_line_1")
            else None
        )
        _address_line_2=(
            self.address_line_2
            if hasattr(self, "address_line_2")
            else None
        )
        _address_line_3=(
            self.address_line_3
            if hasattr(self, "address_line_3")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"city={_city!s}, "
            f"country_code={_country_code!s}, "
            f"address_line_1={_address_line_1!s}, "
            f"address_line_2={_address_line_2!s}, "
            f"address_line_3={_address_line_3!s}, "
            f"postal_code={_postal_code!s}, "
            f"state={_state!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
