"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper
from fortisapi.models.billing_address_24 import (
    BillingAddress24,
)
from fortisapi.models.home_phone import HomePhone
from fortisapi.models.mobile_phone import MobilePhone
from fortisapi.models.shipping_address import (
    ShippingAddress,
)
from fortisapi.models.work_phone import WorkPhone


class Cardholder(object):
    """Implementation of the 'Cardholder' model.

    Contains information for the Cardholder. This field is required unless market or
    regional mandate restricts sending this information.

    Attributes:
        address_match (AddressMatchEnum): Indicates whether the Cardholder Shipping
            Address and Cardholder Billing Address are the same.  If the field is not
            set and the shipping and billing addresses are the same, the 3DS Server
            will set the value to Y. Otherwise, the value will not be changed. >Y -
            Shipping Address matches Billing Address > >N - Shipping Address does not
            match Billing Address >
        billing_address (BillingAddress24): Cardholder billing address object
        email (str): The email address associated with the account that is either
            entered by the Cardholder, or is on file with the 3DS Requestor. This
            field shall meet requirements of Section 3.4 of IETF RFC 5322.  This
            field is required unless market or regional mandate restricts sending
            this information.
        home_phone (HomePhone): The home phone provided by the Cardholder. Refer to
            ITU-E.164 for additional information on format and length.  This field is
            required if available, unless market or regional mandate restricts
            sending this information.
        mobile_phone (MobilePhone): The mobile phone provided by the Cardholder.
            Refer to ITU-E.164 for additional information on format and length.  This
            field is required if available, unless market or regional mandate
            restricts sending this information.
        work_phone (WorkPhone): The work phone provided by the Cardholder. Refer to
            ITU-E.164 for additional information on format and length.  This field is
            required if available, unless market or regional mandate restricts
            sending this information.
        cardholder_name (str): Name of the Cardholder.  This field is required unless
            market or regional mandate restricts sending this information.
        shipping_address (ShippingAddress): Cardholder shipping address object
        tax_id (str): Tax ID is the Cardholder's tax identification.  This field is
            required depending on the rules provided by the Directory Server.
            Available for supporting EMV 3DS 2.3.1 and later versions.
        additional_properties (Dict[str, object]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "address_match": "address_match",
        "billing_address": "billing_address",
        "email": "email",
        "home_phone": "home_phone",
        "mobile_phone": "mobile_phone",
        "work_phone": "work_phone",
        "cardholder_name": "cardholder_name",
        "shipping_address": "shipping_address",
        "tax_id": "tax_id",
    }

    _optionals = [
        "address_match",
        "billing_address",
        "email",
        "home_phone",
        "mobile_phone",
        "work_phone",
        "cardholder_name",
        "shipping_address",
        "tax_id",
    ]

    def __init__(
        self,
        address_match=APIHelper.SKIP,
        billing_address=APIHelper.SKIP,
        email=APIHelper.SKIP,
        home_phone=APIHelper.SKIP,
        mobile_phone=APIHelper.SKIP,
        work_phone=APIHelper.SKIP,
        cardholder_name=APIHelper.SKIP,
        shipping_address=APIHelper.SKIP,
        tax_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Cardholder instance."""
        # Initialize members of the class
        if address_match is not APIHelper.SKIP:
            self.address_match = address_match
        if billing_address is not APIHelper.SKIP:
            self.billing_address = billing_address
        if email is not APIHelper.SKIP:
            self.email = email
        if home_phone is not APIHelper.SKIP:
            self.home_phone = home_phone
        if mobile_phone is not APIHelper.SKIP:
            self.mobile_phone = mobile_phone
        if work_phone is not APIHelper.SKIP:
            self.work_phone = work_phone
        if cardholder_name is not APIHelper.SKIP:
            self.cardholder_name = cardholder_name
        if shipping_address is not APIHelper.SKIP:
            self.shipping_address = shipping_address
        if tax_id is not APIHelper.SKIP:
            self.tax_id = tax_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        address_match =\
            dictionary.get("address_match")\
            if dictionary.get("address_match")\
                else APIHelper.SKIP
        billing_address =\
            BillingAddress24.from_dictionary(
                dictionary.get("billing_address"))\
                if "billing_address" in dictionary.keys()\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        home_phone =\
            HomePhone.from_dictionary(
                dictionary.get("home_phone"))\
                if "home_phone" in dictionary.keys()\
                else APIHelper.SKIP
        mobile_phone =\
            MobilePhone.from_dictionary(
                dictionary.get("mobile_phone"))\
                if "mobile_phone" in dictionary.keys()\
                else APIHelper.SKIP
        work_phone =\
            WorkPhone.from_dictionary(
                dictionary.get("work_phone"))\
                if "work_phone" in dictionary.keys()\
                else APIHelper.SKIP
        cardholder_name =\
            dictionary.get("cardholder_name")\
            if dictionary.get("cardholder_name")\
                else APIHelper.SKIP
        shipping_address =\
            ShippingAddress.from_dictionary(
                dictionary.get("shipping_address"))\
                if "shipping_address" in dictionary.keys()\
                else APIHelper.SKIP
        tax_id =\
            dictionary.get("tax_id")\
            if dictionary.get("tax_id")\
                else APIHelper.SKIP

        # Clean out expected properties from dictionary
        additional_properties =\
            {k: v for k, v in dictionary.items() if k not in cls._names.values()}

        # Return an object of this model
        return cls(address_match,
                   billing_address,
                   email,
                   home_phone,
                   mobile_phone,
                   work_phone,
                   cardholder_name,
                   shipping_address,
                   tax_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _address_match=(
            self.address_match
            if hasattr(self, "address_match")
            else None
        )
        _billing_address=(
            self.billing_address
            if hasattr(self, "billing_address")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _home_phone=(
            self.home_phone
            if hasattr(self, "home_phone")
            else None
        )
        _mobile_phone=(
            self.mobile_phone
            if hasattr(self, "mobile_phone")
            else None
        )
        _work_phone=(
            self.work_phone
            if hasattr(self, "work_phone")
            else None
        )
        _cardholder_name=(
            self.cardholder_name
            if hasattr(self, "cardholder_name")
            else None
        )
        _shipping_address=(
            self.shipping_address
            if hasattr(self, "shipping_address")
            else None
        )
        _tax_id=(
            self.tax_id
            if hasattr(self, "tax_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"address_match={_address_match!r}, "
            f"billing_address={_billing_address!r}, "
            f"email={_email!r}, "
            f"home_phone={_home_phone!r}, "
            f"mobile_phone={_mobile_phone!r}, "
            f"work_phone={_work_phone!r}, "
            f"cardholder_name={_cardholder_name!r}, "
            f"shipping_address={_shipping_address!r}, "
            f"tax_id={_tax_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _address_match=(
            self.address_match
            if hasattr(self, "address_match")
            else None
        )
        _billing_address=(
            self.billing_address
            if hasattr(self, "billing_address")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _home_phone=(
            self.home_phone
            if hasattr(self, "home_phone")
            else None
        )
        _mobile_phone=(
            self.mobile_phone
            if hasattr(self, "mobile_phone")
            else None
        )
        _work_phone=(
            self.work_phone
            if hasattr(self, "work_phone")
            else None
        )
        _cardholder_name=(
            self.cardholder_name
            if hasattr(self, "cardholder_name")
            else None
        )
        _shipping_address=(
            self.shipping_address
            if hasattr(self, "shipping_address")
            else None
        )
        _tax_id=(
            self.tax_id
            if hasattr(self, "tax_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"address_match={_address_match!s}, "
            f"billing_address={_billing_address!s}, "
            f"email={_email!s}, "
            f"home_phone={_home_phone!s}, "
            f"mobile_phone={_mobile_phone!s}, "
            f"work_phone={_work_phone!s}, "
            f"cardholder_name={_cardholder_name!s}, "
            f"shipping_address={_shipping_address!s}, "
            f"tax_id={_tax_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
