"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper
from fortisapi.models.account_vault_cau_product_transaction import (
    AccountVaultCauProductTransaction,
)
from fortisapi.models.active_notification_alert import (
    ActiveNotificationAlert,
)
from fortisapi.models.address_3 import Address3
from fortisapi.models.auth_role import AuthRole
from fortisapi.models.changelog import Changelog
from fortisapi.models.contact_3 import Contact3
from fortisapi.models.domain_1 import Domain1
from fortisapi.models.email_blacklist_1 import (
    EmailBlacklist1,
)
from fortisapi.models.helppage import Helppage
from fortisapi.models.location_18 import Location18
from fortisapi.models.location_user import LocationUser
from fortisapi.models.locationmarketplace import (
    Locationmarketplace,
)
from fortisapi.models.received_email import (
    ReceivedEmail,
)
from fortisapi.models.resources_1 import Resources1
from fortisapi.models.ui_prefs_1 import UiPrefs1
from fortisapi.models.user_9 import User9


class Data34(object):
    """Implementation of the 'Data34' model.

    Attributes:
        account_number (str): Account Number
        branding_domain_url (str): Branding Domain Url
        cell_phone (str): Cell Phone
        company_name (str): Company Name
        contact_id (str): Contact Id Information on `expand`
        date_of_birth (str): Date Of Birth
        domain_id (str): Domain
        email (str): Email
        email_trx_receipt (bool): Email Trx Receipt
        home_phone (str): Home Phone
        first_name (str): First Name
        last_name (str): Last Name
        locale (str): Locale
        office_phone (str): Office Phone
        office_ext_phone (str): Office Ext Phone
        primary_location_id (str): Primary Location ID
        requires_new_password (str): Requires New Password
        terms_condition_code (str): Terms Condition (This field is required when
            updating your own password).
        tz (str): Time zone
        ui_prefs (UiPrefs1): The model property of type UiPrefs1.
        username (str): Username
        user_api_key (str): User Api Key
        user_hash_key (str): User Hash Key
        user_type_code (UserTypeCode): The model property of type UserTypeCode.
        password (str): Password
        zip (str): Zip
        location_id (str): Location ID
        contact_api_id (str): ContactApi Id
        primary_location_api_id (str): Primary LocationApi ID
        status_code (Any): The model property of type Any.
        api_only (bool): API Only
        is_invitation (bool): Is Invitation
        address (Address3): The model property of type Address3.
        id (str): User ID
        status (bool): Status
        login_attempts (int): Login Attempts
        last_login_ts (int): Last Login
        created_ts (int): Created Time Stamp
        modified_ts (int): Modified Time Stamp
        created_user_id (str): Created User
        terms_accepted_ts (int): Terms Accepted
        terms_agree_ip (str): Terms Agree Ip
        current_date_time (str): Current Date Time
        current_login_ip (str): Current Login Ip
        current_login (int): Current Login Timestamp
        sftp_access (bool): SFTP Access
        log_api_response_body_ts (int): Log Api Response Body
        locations (List[Location18]): Location Information on `expand`
        primary_location (AccountVaultCauProductTransaction): The model property of
            type AccountVaultCauProductTransaction.
        received_emails (List[ReceivedEmail]): Received Email Information on `expand`
        contact (Contact3): The model property of type Contact3.
        is_deletable (bool): Is Deletable Information on `expand`
        active_notification_alerts (List[ActiveNotificationAlert]): Active
            Notification Alert Information on `expand`
        location_users (List[LocationUser]): Location User Information on `expand`
        auth_roles (List[AuthRole]): Auth Role Information on `expand`
        changelogs (List[Changelog]): Changelog Information on `expand`
        resources (Resources1): The model property of type Resources1.
        domain (Domain1): The model property of type Domain1.
        created_user (User9): The model property of type User9.
        location_marketplaces (List[Locationmarketplace]): Locationmarketplaces
            Information on `expand`
        email_blacklist (EmailBlacklist1): The model property of type EmailBlacklist1.
        helppage (Helppage): The model property of type Helppage.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_number": "account_number",
        "branding_domain_url": "branding_domain_url",
        "cell_phone": "cell_phone",
        "company_name": "company_name",
        "contact_id": "contact_id",
        "date_of_birth": "date_of_birth",
        "domain_id": "domain_id",
        "email": "email",
        "email_trx_receipt": "email_trx_receipt",
        "home_phone": "home_phone",
        "first_name": "first_name",
        "last_name": "last_name",
        "locale": "locale",
        "office_phone": "office_phone",
        "office_ext_phone": "office_ext_phone",
        "primary_location_id": "primary_location_id",
        "requires_new_password": "requires_new_password",
        "terms_condition_code": "terms_condition_code",
        "tz": "tz",
        "ui_prefs": "ui_prefs",
        "username": "username",
        "user_api_key": "user_api_key",
        "user_hash_key": "user_hash_key",
        "user_type_code": "user_type_code",
        "password": "password",
        "zip": "zip",
        "location_id": "location_id",
        "contact_api_id": "contact_api_id",
        "primary_location_api_id": "primary_location_api_id",
        "status_code": "status_code",
        "api_only": "api_only",
        "is_invitation": "is_invitation",
        "address": "address",
        "id": "id",
        "status": "status",
        "login_attempts": "login_attempts",
        "last_login_ts": "last_login_ts",
        "created_ts": "created_ts",
        "modified_ts": "modified_ts",
        "created_user_id": "created_user_id",
        "terms_accepted_ts": "terms_accepted_ts",
        "terms_agree_ip": "terms_agree_ip",
        "current_date_time": "current_date_time",
        "current_login_ip": "current_login_ip",
        "current_login": "current_login",
        "sftp_access": "sftp_access",
        "log_api_response_body_ts": "log_api_response_body_ts",
        "locations": "locations",
        "primary_location": "primary_location",
        "received_emails": "received_emails",
        "contact": "contact",
        "is_deletable": "isDeletable",
        "active_notification_alerts": "active_notification_alerts",
        "location_users": "location_users",
        "auth_roles": "auth_roles",
        "changelogs": "changelogs",
        "resources": "resources",
        "domain": "domain",
        "created_user": "created_user",
        "location_marketplaces": "location_marketplaces",
        "email_blacklist": "email_blacklist",
        "helppage": "helppage",
    }

    _optionals = [
        "account_number",
        "branding_domain_url",
        "cell_phone",
        "company_name",
        "contact_id",
        "date_of_birth",
        "domain_id",
        "email",
        "email_trx_receipt",
        "home_phone",
        "first_name",
        "last_name",
        "locale",
        "office_phone",
        "office_ext_phone",
        "primary_location_id",
        "requires_new_password",
        "terms_condition_code",
        "tz",
        "ui_prefs",
        "username",
        "user_api_key",
        "user_hash_key",
        "user_type_code",
        "password",
        "zip",
        "location_id",
        "contact_api_id",
        "primary_location_api_id",
        "status_code",
        "api_only",
        "is_invitation",
        "address",
        "id",
        "status",
        "login_attempts",
        "last_login_ts",
        "created_ts",
        "modified_ts",
        "created_user_id",
        "terms_accepted_ts",
        "terms_agree_ip",
        "current_date_time",
        "current_login_ip",
        "current_login",
        "sftp_access",
        "log_api_response_body_ts",
        "locations",
        "primary_location",
        "received_emails",
        "contact",
        "is_deletable",
        "active_notification_alerts",
        "location_users",
        "auth_roles",
        "changelogs",
        "resources",
        "domain",
        "created_user",
        "location_marketplaces",
        "email_blacklist",
        "helppage",
    ]

    _nullables = [
        "account_number",
        "branding_domain_url",
        "cell_phone",
        "company_name",
        "contact_id",
        "date_of_birth",
        "domain_id",
        "home_phone",
        "first_name",
        "locale",
        "office_phone",
        "office_ext_phone",
        "requires_new_password",
        "terms_condition_code",
        "user_api_key",
        "user_hash_key",
        "password",
        "zip",
        "location_id",
        "contact_api_id",
        "primary_location_api_id",
        "terms_accepted_ts",
        "terms_agree_ip",
        "current_login_ip",
        "current_login",
        "log_api_response_body_ts",
    ]

    def __init__(
        self,
        account_number=APIHelper.SKIP,
        branding_domain_url=APIHelper.SKIP,
        cell_phone=APIHelper.SKIP,
        company_name=APIHelper.SKIP,
        contact_id=APIHelper.SKIP,
        date_of_birth=APIHelper.SKIP,
        domain_id=APIHelper.SKIP,
        email=APIHelper.SKIP,
        email_trx_receipt=APIHelper.SKIP,
        home_phone=APIHelper.SKIP,
        first_name=APIHelper.SKIP,
        last_name=APIHelper.SKIP,
        locale=APIHelper.SKIP,
        office_phone=APIHelper.SKIP,
        office_ext_phone=APIHelper.SKIP,
        primary_location_id=APIHelper.SKIP,
        requires_new_password=APIHelper.SKIP,
        terms_condition_code=APIHelper.SKIP,
        tz=APIHelper.SKIP,
        ui_prefs=APIHelper.SKIP,
        username=APIHelper.SKIP,
        user_api_key=APIHelper.SKIP,
        user_hash_key=APIHelper.SKIP,
        user_type_code=APIHelper.SKIP,
        password=APIHelper.SKIP,
        zip=APIHelper.SKIP,
        location_id=APIHelper.SKIP,
        contact_api_id=APIHelper.SKIP,
        primary_location_api_id=APIHelper.SKIP,
        status_code=APIHelper.SKIP,
        api_only=APIHelper.SKIP,
        is_invitation=APIHelper.SKIP,
        address=APIHelper.SKIP,
        id=APIHelper.SKIP,
        status=APIHelper.SKIP,
        login_attempts=APIHelper.SKIP,
        last_login_ts=APIHelper.SKIP,
        created_ts=APIHelper.SKIP,
        modified_ts=APIHelper.SKIP,
        created_user_id=APIHelper.SKIP,
        terms_accepted_ts=APIHelper.SKIP,
        terms_agree_ip=APIHelper.SKIP,
        current_date_time=APIHelper.SKIP,
        current_login_ip=APIHelper.SKIP,
        current_login=APIHelper.SKIP,
        sftp_access=APIHelper.SKIP,
        log_api_response_body_ts=APIHelper.SKIP,
        locations=APIHelper.SKIP,
        primary_location=APIHelper.SKIP,
        received_emails=APIHelper.SKIP,
        contact=APIHelper.SKIP,
        is_deletable=APIHelper.SKIP,
        active_notification_alerts=APIHelper.SKIP,
        location_users=APIHelper.SKIP,
        auth_roles=APIHelper.SKIP,
        changelogs=APIHelper.SKIP,
        resources=APIHelper.SKIP,
        domain=APIHelper.SKIP,
        created_user=APIHelper.SKIP,
        location_marketplaces=APIHelper.SKIP,
        email_blacklist=APIHelper.SKIP,
        helppage=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Data34 instance."""
        # Initialize members of the class
        if account_number is not APIHelper.SKIP:
            self.account_number = account_number
        if branding_domain_url is not APIHelper.SKIP:
            self.branding_domain_url = branding_domain_url
        if cell_phone is not APIHelper.SKIP:
            self.cell_phone = cell_phone
        if company_name is not APIHelper.SKIP:
            self.company_name = company_name
        if contact_id is not APIHelper.SKIP:
            self.contact_id = contact_id
        if date_of_birth is not APIHelper.SKIP:
            self.date_of_birth = date_of_birth
        if domain_id is not APIHelper.SKIP:
            self.domain_id = domain_id
        if email is not APIHelper.SKIP:
            self.email = email
        if email_trx_receipt is not APIHelper.SKIP:
            self.email_trx_receipt = email_trx_receipt
        if home_phone is not APIHelper.SKIP:
            self.home_phone = home_phone
        if first_name is not APIHelper.SKIP:
            self.first_name = first_name
        if last_name is not APIHelper.SKIP:
            self.last_name = last_name
        if locale is not APIHelper.SKIP:
            self.locale = locale
        if office_phone is not APIHelper.SKIP:
            self.office_phone = office_phone
        if office_ext_phone is not APIHelper.SKIP:
            self.office_ext_phone = office_ext_phone
        if primary_location_id is not APIHelper.SKIP:
            self.primary_location_id = primary_location_id
        if requires_new_password is not APIHelper.SKIP:
            self.requires_new_password = requires_new_password
        if terms_condition_code is not APIHelper.SKIP:
            self.terms_condition_code = terms_condition_code
        if tz is not APIHelper.SKIP:
            self.tz = tz
        if ui_prefs is not APIHelper.SKIP:
            self.ui_prefs = ui_prefs
        if username is not APIHelper.SKIP:
            self.username = username
        if user_api_key is not APIHelper.SKIP:
            self.user_api_key = user_api_key
        if user_hash_key is not APIHelper.SKIP:
            self.user_hash_key = user_hash_key
        if user_type_code is not APIHelper.SKIP:
            self.user_type_code = user_type_code
        if password is not APIHelper.SKIP:
            self.password = password
        if zip is not APIHelper.SKIP:
            self.zip = zip
        if location_id is not APIHelper.SKIP:
            self.location_id = location_id
        if contact_api_id is not APIHelper.SKIP:
            self.contact_api_id = contact_api_id
        if primary_location_api_id is not APIHelper.SKIP:
            self.primary_location_api_id = primary_location_api_id
        if status_code is not APIHelper.SKIP:
            self.status_code = status_code
        if api_only is not APIHelper.SKIP:
            self.api_only = api_only
        if is_invitation is not APIHelper.SKIP:
            self.is_invitation = is_invitation
        if address is not APIHelper.SKIP:
            self.address = address
        if id is not APIHelper.SKIP:
            self.id = id
        if status is not APIHelper.SKIP:
            self.status = status
        if login_attempts is not APIHelper.SKIP:
            self.login_attempts = login_attempts
        if last_login_ts is not APIHelper.SKIP:
            self.last_login_ts = last_login_ts
        if created_ts is not APIHelper.SKIP:
            self.created_ts = created_ts
        if modified_ts is not APIHelper.SKIP:
            self.modified_ts = modified_ts
        if created_user_id is not APIHelper.SKIP:
            self.created_user_id = created_user_id
        if terms_accepted_ts is not APIHelper.SKIP:
            self.terms_accepted_ts = terms_accepted_ts
        if terms_agree_ip is not APIHelper.SKIP:
            self.terms_agree_ip = terms_agree_ip
        if current_date_time is not APIHelper.SKIP:
            self.current_date_time = current_date_time
        if current_login_ip is not APIHelper.SKIP:
            self.current_login_ip = current_login_ip
        if current_login is not APIHelper.SKIP:
            self.current_login = current_login
        if sftp_access is not APIHelper.SKIP:
            self.sftp_access = sftp_access
        if log_api_response_body_ts is not APIHelper.SKIP:
            self.log_api_response_body_ts = log_api_response_body_ts
        if locations is not APIHelper.SKIP:
            self.locations = locations
        if primary_location is not APIHelper.SKIP:
            self.primary_location = primary_location
        if received_emails is not APIHelper.SKIP:
            self.received_emails = received_emails
        if contact is not APIHelper.SKIP:
            self.contact = contact
        if is_deletable is not APIHelper.SKIP:
            self.is_deletable = is_deletable
        if active_notification_alerts is not APIHelper.SKIP:
            self.active_notification_alerts = active_notification_alerts
        if location_users is not APIHelper.SKIP:
            self.location_users = location_users
        if auth_roles is not APIHelper.SKIP:
            self.auth_roles = auth_roles
        if changelogs is not APIHelper.SKIP:
            self.changelogs = changelogs
        if resources is not APIHelper.SKIP:
            self.resources = resources
        if domain is not APIHelper.SKIP:
            self.domain = domain
        if created_user is not APIHelper.SKIP:
            self.created_user = created_user
        if location_marketplaces is not APIHelper.SKIP:
            self.location_marketplaces = location_marketplaces
        if email_blacklist is not APIHelper.SKIP:
            self.email_blacklist = email_blacklist
        if helppage is not APIHelper.SKIP:
            self.helppage = helppage

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_number =\
            dictionary.get("account_number")\
            if "account_number" in dictionary.keys()\
                else APIHelper.SKIP
        branding_domain_url =\
            dictionary.get("branding_domain_url")\
            if "branding_domain_url" in dictionary.keys()\
                else APIHelper.SKIP
        cell_phone =\
            dictionary.get("cell_phone")\
            if "cell_phone" in dictionary.keys()\
                else APIHelper.SKIP
        company_name =\
            dictionary.get("company_name")\
            if "company_name" in dictionary.keys()\
                else APIHelper.SKIP
        contact_id =\
            dictionary.get("contact_id")\
            if "contact_id" in dictionary.keys()\
                else APIHelper.SKIP
        date_of_birth =\
            dictionary.get("date_of_birth")\
            if "date_of_birth" in dictionary.keys()\
                else APIHelper.SKIP
        domain_id =\
            dictionary.get("domain_id")\
            if "domain_id" in dictionary.keys()\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        email_trx_receipt =\
            dictionary.get("email_trx_receipt")\
            if "email_trx_receipt" in dictionary.keys()\
                else APIHelper.SKIP
        home_phone =\
            dictionary.get("home_phone")\
            if "home_phone" in dictionary.keys()\
                else APIHelper.SKIP
        first_name =\
            dictionary.get("first_name")\
            if "first_name" in dictionary.keys()\
                else APIHelper.SKIP
        last_name =\
            dictionary.get("last_name")\
            if dictionary.get("last_name")\
                else APIHelper.SKIP
        locale =\
            dictionary.get("locale")\
            if "locale" in dictionary.keys()\
                else APIHelper.SKIP
        office_phone =\
            dictionary.get("office_phone")\
            if "office_phone" in dictionary.keys()\
                else APIHelper.SKIP
        office_ext_phone =\
            dictionary.get("office_ext_phone")\
            if "office_ext_phone" in dictionary.keys()\
                else APIHelper.SKIP
        primary_location_id =\
            dictionary.get("primary_location_id")\
            if dictionary.get("primary_location_id")\
                else APIHelper.SKIP
        requires_new_password =\
            dictionary.get("requires_new_password")\
            if "requires_new_password" in dictionary.keys()\
                else APIHelper.SKIP
        terms_condition_code =\
            dictionary.get("terms_condition_code")\
            if "terms_condition_code" in dictionary.keys()\
                else APIHelper.SKIP
        tz =\
            dictionary.get("tz")\
            if dictionary.get("tz")\
                else APIHelper.SKIP
        ui_prefs =\
            UiPrefs1.from_dictionary(
                dictionary.get("ui_prefs"))\
                if "ui_prefs" in dictionary.keys()\
                else APIHelper.SKIP
        username =\
            dictionary.get("username")\
            if dictionary.get("username")\
                else APIHelper.SKIP
        user_api_key =\
            dictionary.get("user_api_key")\
            if "user_api_key" in dictionary.keys()\
                else APIHelper.SKIP
        user_hash_key =\
            dictionary.get("user_hash_key")\
            if "user_hash_key" in dictionary.keys()\
                else APIHelper.SKIP
        user_type_code =\
            dictionary.get("user_type_code")\
            if dictionary.get("user_type_code")\
                else APIHelper.SKIP
        password =\
            dictionary.get("password")\
            if "password" in dictionary.keys()\
                else APIHelper.SKIP
        zip =\
            dictionary.get("zip")\
            if "zip" in dictionary.keys()\
                else APIHelper.SKIP
        location_id =\
            dictionary.get("location_id")\
            if "location_id" in dictionary.keys()\
                else APIHelper.SKIP
        contact_api_id =\
            dictionary.get("contact_api_id")\
            if "contact_api_id" in dictionary.keys()\
                else APIHelper.SKIP
        primary_location_api_id =\
            dictionary.get("primary_location_api_id")\
            if "primary_location_api_id" in dictionary.keys()\
                else APIHelper.SKIP
        status_code =\
            dictionary.get("status_code")\
            if dictionary.get("status_code")\
                else APIHelper.SKIP
        api_only =\
            dictionary.get("api_only")\
            if "api_only" in dictionary.keys()\
                else APIHelper.SKIP
        is_invitation =\
            dictionary.get("is_invitation")\
            if "is_invitation" in dictionary.keys()\
                else APIHelper.SKIP
        address =\
            Address3.from_dictionary(
                dictionary.get("address"))\
                if "address" in dictionary.keys()\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if "status" in dictionary.keys()\
                else APIHelper.SKIP
        login_attempts =\
            dictionary.get("login_attempts")\
            if dictionary.get("login_attempts")\
                else APIHelper.SKIP
        last_login_ts =\
            dictionary.get("last_login_ts")\
            if dictionary.get("last_login_ts")\
                else APIHelper.SKIP
        created_ts =\
            dictionary.get("created_ts")\
            if dictionary.get("created_ts")\
                else APIHelper.SKIP
        modified_ts =\
            dictionary.get("modified_ts")\
            if dictionary.get("modified_ts")\
                else APIHelper.SKIP
        created_user_id =\
            dictionary.get("created_user_id")\
            if dictionary.get("created_user_id")\
                else APIHelper.SKIP
        terms_accepted_ts =\
            dictionary.get("terms_accepted_ts")\
            if "terms_accepted_ts" in dictionary.keys()\
                else APIHelper.SKIP
        terms_agree_ip =\
            dictionary.get("terms_agree_ip")\
            if "terms_agree_ip" in dictionary.keys()\
                else APIHelper.SKIP
        current_date_time =\
            dictionary.get("current_date_time")\
            if dictionary.get("current_date_time")\
                else APIHelper.SKIP
        current_login_ip =\
            dictionary.get("current_login_ip")\
            if "current_login_ip" in dictionary.keys()\
                else APIHelper.SKIP
        current_login =\
            dictionary.get("current_login")\
            if "current_login" in dictionary.keys()\
                else APIHelper.SKIP
        sftp_access =\
            dictionary.get("sftp_access")\
            if "sftp_access" in dictionary.keys()\
                else APIHelper.SKIP
        log_api_response_body_ts =\
            dictionary.get("log_api_response_body_ts")\
            if "log_api_response_body_ts" in dictionary.keys()\
                else APIHelper.SKIP
        locations = None
        if dictionary.get("locations") is not None:
            locations = [
                Location18.from_dictionary(x)
                    for x in dictionary.get("locations")
            ]
        else:
            locations = APIHelper.SKIP
        primary_location =\
            AccountVaultCauProductTransaction.from_dictionary(
                dictionary.get("primary_location"))\
                if "primary_location" in dictionary.keys()\
                else APIHelper.SKIP
        received_emails = None
        if dictionary.get("received_emails") is not None:
            received_emails = [
                ReceivedEmail.from_dictionary(x)
                    for x in dictionary.get("received_emails")
            ]
        else:
            received_emails = APIHelper.SKIP
        contact =\
            Contact3.from_dictionary(
                dictionary.get("contact"))\
                if "contact" in dictionary.keys()\
                else APIHelper.SKIP
        is_deletable =\
            dictionary.get("isDeletable")\
            if "isDeletable" in dictionary.keys()\
                else APIHelper.SKIP
        active_notification_alerts = None
        if dictionary.get("active_notification_alerts") is not None:
            active_notification_alerts = [
                ActiveNotificationAlert.from_dictionary(x)
                    for x in dictionary.get("active_notification_alerts")
            ]
        else:
            active_notification_alerts = APIHelper.SKIP
        location_users = None
        if dictionary.get("location_users") is not None:
            location_users = [
                LocationUser.from_dictionary(x)
                    for x in dictionary.get("location_users")
            ]
        else:
            location_users = APIHelper.SKIP
        auth_roles = None
        if dictionary.get("auth_roles") is not None:
            auth_roles = [
                AuthRole.from_dictionary(x)
                    for x in dictionary.get("auth_roles")
            ]
        else:
            auth_roles = APIHelper.SKIP
        changelogs = None
        if dictionary.get("changelogs") is not None:
            changelogs = [
                Changelog.from_dictionary(x)
                    for x in dictionary.get("changelogs")
            ]
        else:
            changelogs = APIHelper.SKIP
        resources =\
            Resources1.from_dictionary(
                dictionary.get("resources"))\
                if "resources" in dictionary.keys()\
                else APIHelper.SKIP
        domain =\
            Domain1.from_dictionary(
                dictionary.get("domain"))\
                if "domain" in dictionary.keys()\
                else APIHelper.SKIP
        created_user =\
            User9.from_dictionary(
                dictionary.get("created_user"))\
                if "created_user" in dictionary.keys()\
                else APIHelper.SKIP
        location_marketplaces = None
        if dictionary.get("location_marketplaces") is not None:
            location_marketplaces = [
                Locationmarketplace.from_dictionary(x)
                    for x in dictionary.get("location_marketplaces")
            ]
        else:
            location_marketplaces = APIHelper.SKIP
        email_blacklist =\
            EmailBlacklist1.from_dictionary(
                dictionary.get("email_blacklist"))\
                if "email_blacklist" in dictionary.keys()\
                else APIHelper.SKIP
        helppage =\
            Helppage.from_dictionary(
                dictionary.get("helppage"))\
                if "helppage" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_number,
                   branding_domain_url,
                   cell_phone,
                   company_name,
                   contact_id,
                   date_of_birth,
                   domain_id,
                   email,
                   email_trx_receipt,
                   home_phone,
                   first_name,
                   last_name,
                   locale,
                   office_phone,
                   office_ext_phone,
                   primary_location_id,
                   requires_new_password,
                   terms_condition_code,
                   tz,
                   ui_prefs,
                   username,
                   user_api_key,
                   user_hash_key,
                   user_type_code,
                   password,
                   zip,
                   location_id,
                   contact_api_id,
                   primary_location_api_id,
                   status_code,
                   api_only,
                   is_invitation,
                   address,
                   id,
                   status,
                   login_attempts,
                   last_login_ts,
                   created_ts,
                   modified_ts,
                   created_user_id,
                   terms_accepted_ts,
                   terms_agree_ip,
                   current_date_time,
                   current_login_ip,
                   current_login,
                   sftp_access,
                   log_api_response_body_ts,
                   locations,
                   primary_location,
                   received_emails,
                   contact,
                   is_deletable,
                   active_notification_alerts,
                   location_users,
                   auth_roles,
                   changelogs,
                   resources,
                   domain,
                   created_user,
                   location_marketplaces,
                   email_blacklist,
                   helppage,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_number=(
            self.account_number
            if hasattr(self, "account_number")
            else None
        )
        _branding_domain_url=(
            self.branding_domain_url
            if hasattr(self, "branding_domain_url")
            else None
        )
        _cell_phone=(
            self.cell_phone
            if hasattr(self, "cell_phone")
            else None
        )
        _company_name=(
            self.company_name
            if hasattr(self, "company_name")
            else None
        )
        _contact_id=(
            self.contact_id
            if hasattr(self, "contact_id")
            else None
        )
        _date_of_birth=(
            self.date_of_birth
            if hasattr(self, "date_of_birth")
            else None
        )
        _domain_id=(
            self.domain_id
            if hasattr(self, "domain_id")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _email_trx_receipt=(
            self.email_trx_receipt
            if hasattr(self, "email_trx_receipt")
            else None
        )
        _home_phone=(
            self.home_phone
            if hasattr(self, "home_phone")
            else None
        )
        _first_name=(
            self.first_name
            if hasattr(self, "first_name")
            else None
        )
        _last_name=(
            self.last_name
            if hasattr(self, "last_name")
            else None
        )
        _locale=(
            self.locale
            if hasattr(self, "locale")
            else None
        )
        _office_phone=(
            self.office_phone
            if hasattr(self, "office_phone")
            else None
        )
        _office_ext_phone=(
            self.office_ext_phone
            if hasattr(self, "office_ext_phone")
            else None
        )
        _primary_location_id=(
            self.primary_location_id
            if hasattr(self, "primary_location_id")
            else None
        )
        _requires_new_password=(
            self.requires_new_password
            if hasattr(self, "requires_new_password")
            else None
        )
        _terms_condition_code=(
            self.terms_condition_code
            if hasattr(self, "terms_condition_code")
            else None
        )
        _tz=(
            self.tz
            if hasattr(self, "tz")
            else None
        )
        _ui_prefs=(
            self.ui_prefs
            if hasattr(self, "ui_prefs")
            else None
        )
        _username=(
            self.username
            if hasattr(self, "username")
            else None
        )
        _user_api_key=(
            self.user_api_key
            if hasattr(self, "user_api_key")
            else None
        )
        _user_hash_key=(
            self.user_hash_key
            if hasattr(self, "user_hash_key")
            else None
        )
        _user_type_code=(
            self.user_type_code
            if hasattr(self, "user_type_code")
            else None
        )
        _password=(
            self.password
            if hasattr(self, "password")
            else None
        )
        _zip=(
            self.zip
            if hasattr(self, "zip")
            else None
        )
        _location_id=(
            self.location_id
            if hasattr(self, "location_id")
            else None
        )
        _contact_api_id=(
            self.contact_api_id
            if hasattr(self, "contact_api_id")
            else None
        )
        _primary_location_api_id=(
            self.primary_location_api_id
            if hasattr(self, "primary_location_api_id")
            else None
        )
        _status_code=(
            self.status_code
            if hasattr(self, "status_code")
            else None
        )
        _api_only=(
            self.api_only
            if hasattr(self, "api_only")
            else None
        )
        _is_invitation=(
            self.is_invitation
            if hasattr(self, "is_invitation")
            else None
        )
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _login_attempts=(
            self.login_attempts
            if hasattr(self, "login_attempts")
            else None
        )
        _last_login_ts=(
            self.last_login_ts
            if hasattr(self, "last_login_ts")
            else None
        )
        _created_ts=(
            self.created_ts
            if hasattr(self, "created_ts")
            else None
        )
        _modified_ts=(
            self.modified_ts
            if hasattr(self, "modified_ts")
            else None
        )
        _created_user_id=(
            self.created_user_id
            if hasattr(self, "created_user_id")
            else None
        )
        _terms_accepted_ts=(
            self.terms_accepted_ts
            if hasattr(self, "terms_accepted_ts")
            else None
        )
        _terms_agree_ip=(
            self.terms_agree_ip
            if hasattr(self, "terms_agree_ip")
            else None
        )
        _current_date_time=(
            self.current_date_time
            if hasattr(self, "current_date_time")
            else None
        )
        _current_login_ip=(
            self.current_login_ip
            if hasattr(self, "current_login_ip")
            else None
        )
        _current_login=(
            self.current_login
            if hasattr(self, "current_login")
            else None
        )
        _sftp_access=(
            self.sftp_access
            if hasattr(self, "sftp_access")
            else None
        )
        _log_api_response_body_ts=(
            self.log_api_response_body_ts
            if hasattr(self, "log_api_response_body_ts")
            else None
        )
        _locations=(
            self.locations
            if hasattr(self, "locations")
            else None
        )
        _primary_location=(
            self.primary_location
            if hasattr(self, "primary_location")
            else None
        )
        _received_emails=(
            self.received_emails
            if hasattr(self, "received_emails")
            else None
        )
        _contact=(
            self.contact
            if hasattr(self, "contact")
            else None
        )
        _is_deletable=(
            self.is_deletable
            if hasattr(self, "is_deletable")
            else None
        )
        _active_notification_alerts=(
            self.active_notification_alerts
            if hasattr(self, "active_notification_alerts")
            else None
        )
        _location_users=(
            self.location_users
            if hasattr(self, "location_users")
            else None
        )
        _auth_roles=(
            self.auth_roles
            if hasattr(self, "auth_roles")
            else None
        )
        _changelogs=(
            self.changelogs
            if hasattr(self, "changelogs")
            else None
        )
        _resources=(
            self.resources
            if hasattr(self, "resources")
            else None
        )
        _domain=(
            self.domain
            if hasattr(self, "domain")
            else None
        )
        _created_user=(
            self.created_user
            if hasattr(self, "created_user")
            else None
        )
        _location_marketplaces=(
            self.location_marketplaces
            if hasattr(self, "location_marketplaces")
            else None
        )
        _email_blacklist=(
            self.email_blacklist
            if hasattr(self, "email_blacklist")
            else None
        )
        _helppage=(
            self.helppage
            if hasattr(self, "helppage")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_number={_account_number!r}, "
            f"branding_domain_url={_branding_domain_url!r}, "
            f"cell_phone={_cell_phone!r}, "
            f"company_name={_company_name!r}, "
            f"contact_id={_contact_id!r}, "
            f"date_of_birth={_date_of_birth!r}, "
            f"domain_id={_domain_id!r}, "
            f"email={_email!r}, "
            f"email_trx_receipt={_email_trx_receipt!r}, "
            f"home_phone={_home_phone!r}, "
            f"first_name={_first_name!r}, "
            f"last_name={_last_name!r}, "
            f"locale={_locale!r}, "
            f"office_phone={_office_phone!r}, "
            f"office_ext_phone={_office_ext_phone!r}, "
            f"primary_location_id={_primary_location_id!r}, "
            f"requires_new_password={_requires_new_password!r}, "
            f"terms_condition_code={_terms_condition_code!r}, "
            f"tz={_tz!r}, "
            f"ui_prefs={_ui_prefs!r}, "
            f"username={_username!r}, "
            f"user_api_key={_user_api_key!r}, "
            f"user_hash_key={_user_hash_key!r}, "
            f"user_type_code={_user_type_code!r}, "
            f"password={_password!r}, "
            f"zip={_zip!r}, "
            f"location_id={_location_id!r}, "
            f"contact_api_id={_contact_api_id!r}, "
            f"primary_location_api_id={_primary_location_api_id!r}, "
            f"status_code={_status_code!r}, "
            f"api_only={_api_only!r}, "
            f"is_invitation={_is_invitation!r}, "
            f"address={_address!r}, "
            f"id={_id!r}, "
            f"status={_status!r}, "
            f"login_attempts={_login_attempts!r}, "
            f"last_login_ts={_last_login_ts!r}, "
            f"created_ts={_created_ts!r}, "
            f"modified_ts={_modified_ts!r}, "
            f"created_user_id={_created_user_id!r}, "
            f"terms_accepted_ts={_terms_accepted_ts!r}, "
            f"terms_agree_ip={_terms_agree_ip!r}, "
            f"current_date_time={_current_date_time!r}, "
            f"current_login_ip={_current_login_ip!r}, "
            f"current_login={_current_login!r}, "
            f"sftp_access={_sftp_access!r}, "
            f"log_api_response_body_ts={_log_api_response_body_ts!r}, "
            f"locations={_locations!r}, "
            f"primary_location={_primary_location!r}, "
            f"received_emails={_received_emails!r}, "
            f"contact={_contact!r}, "
            f"is_deletable={_is_deletable!r}, "
            f"active_notification_alerts={_active_notification_alerts!r}, "
            f"location_users={_location_users!r}, "
            f"auth_roles={_auth_roles!r}, "
            f"changelogs={_changelogs!r}, "
            f"resources={_resources!r}, "
            f"domain={_domain!r}, "
            f"created_user={_created_user!r}, "
            f"location_marketplaces={_location_marketplaces!r}, "
            f"email_blacklist={_email_blacklist!r}, "
            f"helppage={_helppage!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_number=(
            self.account_number
            if hasattr(self, "account_number")
            else None
        )
        _branding_domain_url=(
            self.branding_domain_url
            if hasattr(self, "branding_domain_url")
            else None
        )
        _cell_phone=(
            self.cell_phone
            if hasattr(self, "cell_phone")
            else None
        )
        _company_name=(
            self.company_name
            if hasattr(self, "company_name")
            else None
        )
        _contact_id=(
            self.contact_id
            if hasattr(self, "contact_id")
            else None
        )
        _date_of_birth=(
            self.date_of_birth
            if hasattr(self, "date_of_birth")
            else None
        )
        _domain_id=(
            self.domain_id
            if hasattr(self, "domain_id")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _email_trx_receipt=(
            self.email_trx_receipt
            if hasattr(self, "email_trx_receipt")
            else None
        )
        _home_phone=(
            self.home_phone
            if hasattr(self, "home_phone")
            else None
        )
        _first_name=(
            self.first_name
            if hasattr(self, "first_name")
            else None
        )
        _last_name=(
            self.last_name
            if hasattr(self, "last_name")
            else None
        )
        _locale=(
            self.locale
            if hasattr(self, "locale")
            else None
        )
        _office_phone=(
            self.office_phone
            if hasattr(self, "office_phone")
            else None
        )
        _office_ext_phone=(
            self.office_ext_phone
            if hasattr(self, "office_ext_phone")
            else None
        )
        _primary_location_id=(
            self.primary_location_id
            if hasattr(self, "primary_location_id")
            else None
        )
        _requires_new_password=(
            self.requires_new_password
            if hasattr(self, "requires_new_password")
            else None
        )
        _terms_condition_code=(
            self.terms_condition_code
            if hasattr(self, "terms_condition_code")
            else None
        )
        _tz=(
            self.tz
            if hasattr(self, "tz")
            else None
        )
        _ui_prefs=(
            self.ui_prefs
            if hasattr(self, "ui_prefs")
            else None
        )
        _username=(
            self.username
            if hasattr(self, "username")
            else None
        )
        _user_api_key=(
            self.user_api_key
            if hasattr(self, "user_api_key")
            else None
        )
        _user_hash_key=(
            self.user_hash_key
            if hasattr(self, "user_hash_key")
            else None
        )
        _user_type_code=(
            self.user_type_code
            if hasattr(self, "user_type_code")
            else None
        )
        _password=(
            self.password
            if hasattr(self, "password")
            else None
        )
        _zip=(
            self.zip
            if hasattr(self, "zip")
            else None
        )
        _location_id=(
            self.location_id
            if hasattr(self, "location_id")
            else None
        )
        _contact_api_id=(
            self.contact_api_id
            if hasattr(self, "contact_api_id")
            else None
        )
        _primary_location_api_id=(
            self.primary_location_api_id
            if hasattr(self, "primary_location_api_id")
            else None
        )
        _status_code=(
            self.status_code
            if hasattr(self, "status_code")
            else None
        )
        _api_only=(
            self.api_only
            if hasattr(self, "api_only")
            else None
        )
        _is_invitation=(
            self.is_invitation
            if hasattr(self, "is_invitation")
            else None
        )
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _login_attempts=(
            self.login_attempts
            if hasattr(self, "login_attempts")
            else None
        )
        _last_login_ts=(
            self.last_login_ts
            if hasattr(self, "last_login_ts")
            else None
        )
        _created_ts=(
            self.created_ts
            if hasattr(self, "created_ts")
            else None
        )
        _modified_ts=(
            self.modified_ts
            if hasattr(self, "modified_ts")
            else None
        )
        _created_user_id=(
            self.created_user_id
            if hasattr(self, "created_user_id")
            else None
        )
        _terms_accepted_ts=(
            self.terms_accepted_ts
            if hasattr(self, "terms_accepted_ts")
            else None
        )
        _terms_agree_ip=(
            self.terms_agree_ip
            if hasattr(self, "terms_agree_ip")
            else None
        )
        _current_date_time=(
            self.current_date_time
            if hasattr(self, "current_date_time")
            else None
        )
        _current_login_ip=(
            self.current_login_ip
            if hasattr(self, "current_login_ip")
            else None
        )
        _current_login=(
            self.current_login
            if hasattr(self, "current_login")
            else None
        )
        _sftp_access=(
            self.sftp_access
            if hasattr(self, "sftp_access")
            else None
        )
        _log_api_response_body_ts=(
            self.log_api_response_body_ts
            if hasattr(self, "log_api_response_body_ts")
            else None
        )
        _locations=(
            self.locations
            if hasattr(self, "locations")
            else None
        )
        _primary_location=(
            self.primary_location
            if hasattr(self, "primary_location")
            else None
        )
        _received_emails=(
            self.received_emails
            if hasattr(self, "received_emails")
            else None
        )
        _contact=(
            self.contact
            if hasattr(self, "contact")
            else None
        )
        _is_deletable=(
            self.is_deletable
            if hasattr(self, "is_deletable")
            else None
        )
        _active_notification_alerts=(
            self.active_notification_alerts
            if hasattr(self, "active_notification_alerts")
            else None
        )
        _location_users=(
            self.location_users
            if hasattr(self, "location_users")
            else None
        )
        _auth_roles=(
            self.auth_roles
            if hasattr(self, "auth_roles")
            else None
        )
        _changelogs=(
            self.changelogs
            if hasattr(self, "changelogs")
            else None
        )
        _resources=(
            self.resources
            if hasattr(self, "resources")
            else None
        )
        _domain=(
            self.domain
            if hasattr(self, "domain")
            else None
        )
        _created_user=(
            self.created_user
            if hasattr(self, "created_user")
            else None
        )
        _location_marketplaces=(
            self.location_marketplaces
            if hasattr(self, "location_marketplaces")
            else None
        )
        _email_blacklist=(
            self.email_blacklist
            if hasattr(self, "email_blacklist")
            else None
        )
        _helppage=(
            self.helppage
            if hasattr(self, "helppage")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_number={_account_number!s}, "
            f"branding_domain_url={_branding_domain_url!s}, "
            f"cell_phone={_cell_phone!s}, "
            f"company_name={_company_name!s}, "
            f"contact_id={_contact_id!s}, "
            f"date_of_birth={_date_of_birth!s}, "
            f"domain_id={_domain_id!s}, "
            f"email={_email!s}, "
            f"email_trx_receipt={_email_trx_receipt!s}, "
            f"home_phone={_home_phone!s}, "
            f"first_name={_first_name!s}, "
            f"last_name={_last_name!s}, "
            f"locale={_locale!s}, "
            f"office_phone={_office_phone!s}, "
            f"office_ext_phone={_office_ext_phone!s}, "
            f"primary_location_id={_primary_location_id!s}, "
            f"requires_new_password={_requires_new_password!s}, "
            f"terms_condition_code={_terms_condition_code!s}, "
            f"tz={_tz!s}, "
            f"ui_prefs={_ui_prefs!s}, "
            f"username={_username!s}, "
            f"user_api_key={_user_api_key!s}, "
            f"user_hash_key={_user_hash_key!s}, "
            f"user_type_code={_user_type_code!s}, "
            f"password={_password!s}, "
            f"zip={_zip!s}, "
            f"location_id={_location_id!s}, "
            f"contact_api_id={_contact_api_id!s}, "
            f"primary_location_api_id={_primary_location_api_id!s}, "
            f"status_code={_status_code!s}, "
            f"api_only={_api_only!s}, "
            f"is_invitation={_is_invitation!s}, "
            f"address={_address!s}, "
            f"id={_id!s}, "
            f"status={_status!s}, "
            f"login_attempts={_login_attempts!s}, "
            f"last_login_ts={_last_login_ts!s}, "
            f"created_ts={_created_ts!s}, "
            f"modified_ts={_modified_ts!s}, "
            f"created_user_id={_created_user_id!s}, "
            f"terms_accepted_ts={_terms_accepted_ts!s}, "
            f"terms_agree_ip={_terms_agree_ip!s}, "
            f"current_date_time={_current_date_time!s}, "
            f"current_login_ip={_current_login_ip!s}, "
            f"current_login={_current_login!s}, "
            f"sftp_access={_sftp_access!s}, "
            f"log_api_response_body_ts={_log_api_response_body_ts!s}, "
            f"locations={_locations!s}, "
            f"primary_location={_primary_location!s}, "
            f"received_emails={_received_emails!s}, "
            f"contact={_contact!s}, "
            f"is_deletable={_is_deletable!s}, "
            f"active_notification_alerts={_active_notification_alerts!s}, "
            f"location_users={_location_users!s}, "
            f"auth_roles={_auth_roles!s}, "
            f"changelogs={_changelogs!s}, "
            f"resources={_resources!s}, "
            f"domain={_domain!s}, "
            f"created_user={_created_user!s}, "
            f"location_marketplaces={_location_marketplaces!s}, "
            f"email_blacklist={_email_blacklist!s}, "
            f"helppage={_helppage!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
