"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper


class Data19(object):
    """Implementation of the 'Data19' model.

    Attributes:
        id (str): Quick Invoice ID
        email_log_id (str): Email Log Id
        sms_log_id (str): SMS Log Id
        success (bool): Success
        sms_success (bool): SMS Success
        email (str): Email
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "email_log_id": "email_log_id",
        "sms_log_id": "sms_log_id",
        "success": "success",
        "sms_success": "sms_success",
        "email": "email",
    }

    _optionals = [
        "id",
        "email_log_id",
        "sms_log_id",
        "success",
        "sms_success",
        "email",
    ]

    _nullables = [
        "email_log_id",
        "sms_log_id",
        "email",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        email_log_id=APIHelper.SKIP,
        sms_log_id=APIHelper.SKIP,
        success=APIHelper.SKIP,
        sms_success=APIHelper.SKIP,
        email=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Data19 instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if email_log_id is not APIHelper.SKIP:
            self.email_log_id = email_log_id
        if sms_log_id is not APIHelper.SKIP:
            self.sms_log_id = sms_log_id
        if success is not APIHelper.SKIP:
            self.success = success
        if sms_success is not APIHelper.SKIP:
            self.sms_success = sms_success
        if email is not APIHelper.SKIP:
            self.email = email

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        email_log_id =\
            dictionary.get("email_log_id")\
            if "email_log_id" in dictionary.keys()\
                else APIHelper.SKIP
        sms_log_id =\
            dictionary.get("sms_log_id")\
            if "sms_log_id" in dictionary.keys()\
                else APIHelper.SKIP
        success =\
            dictionary.get("success")\
            if "success" in dictionary.keys()\
                else APIHelper.SKIP
        sms_success =\
            dictionary.get("sms_success")\
            if "sms_success" in dictionary.keys()\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if "email" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   email_log_id,
                   sms_log_id,
                   success,
                   sms_success,
                   email,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _email_log_id=(
            self.email_log_id
            if hasattr(self, "email_log_id")
            else None
        )
        _sms_log_id=(
            self.sms_log_id
            if hasattr(self, "sms_log_id")
            else None
        )
        _success=(
            self.success
            if hasattr(self, "success")
            else None
        )
        _sms_success=(
            self.sms_success
            if hasattr(self, "sms_success")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"email_log_id={_email_log_id!r}, "
            f"sms_log_id={_sms_log_id!r}, "
            f"success={_success!r}, "
            f"sms_success={_sms_success!r}, "
            f"email={_email!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _email_log_id=(
            self.email_log_id
            if hasattr(self, "email_log_id")
            else None
        )
        _sms_log_id=(
            self.sms_log_id
            if hasattr(self, "sms_log_id")
            else None
        )
        _success=(
            self.success
            if hasattr(self, "success")
            else None
        )
        _sms_success=(
            self.sms_success
            if hasattr(self, "sms_success")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"email_log_id={_email_log_id!s}, "
            f"sms_log_id={_sms_log_id!s}, "
            f"success={_success!s}, "
            f"sms_success={_sms_success!s}, "
            f"email={_email!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
