"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Field55(object):
    """Implementation of the 'field55' enum.

    Attributes:
        REJECTED_TRANSACTION_ID: The enum member of type str.
        RETURN_FEE: The enum member of type str.
        ID: The enum member of type str.
        RETRY_TRANSACTION_ID: The enum member of type str.
        RETURN_FEE_TRANSACTION_ID: The enum member of type str.
        CREATED_TS: The enum member of type str.
        CREATED_USER_ID: The enum member of type str.
        REJECTED_TRANSACTION: The enum member of type str.
        RETRY_TRANSACTION: The enum member of type str.
        RETURN_FEE_TRANSACTION: The enum member of type str.
        CREATED_USER: The enum member of type str.
        CHANGELOGS: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    REJECTED_TRANSACTION_ID = "rejected_transaction_id"

    RETURN_FEE = "return_fee"

    ID = "id"

    RETRY_TRANSACTION_ID = "retry_transaction_id"

    RETURN_FEE_TRANSACTION_ID = "return_fee_transaction_id"

    CREATED_TS = "created_ts"

    CREATED_USER_ID = "created_user_id"

    REJECTED_TRANSACTION = "rejected_transaction"

    RETRY_TRANSACTION = "retry_transaction"

    RETURN_FEE_TRANSACTION = "return_fee_transaction"

    CREATED_USER = "created_user"

    CHANGELOGS = "changelogs"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
