"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper


class Field(object):
    """Implementation of the 'Field' model.

    Attributes:
        field (str): Field name used on the sort
        order (OrderEnum): Sort direction ASC/DESC
        additional_properties (Dict[str, object]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "field": "field",
        "order": "order",
    }

    _optionals = [
        "field",
        "order",
    ]

    def __init__(
        self,
        field=APIHelper.SKIP,
        order=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Field instance."""
        # Initialize members of the class
        if field is not APIHelper.SKIP:
            self.field = field
        if order is not APIHelper.SKIP:
            self.order = order

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        field =\
            dictionary.get("field")\
            if dictionary.get("field")\
                else APIHelper.SKIP
        order =\
            dictionary.get("order")\
            if dictionary.get("order")\
                else APIHelper.SKIP

        # Clean out expected properties from dictionary
        additional_properties =\
            {k: v for k, v in dictionary.items() if k not in cls._names.values()}

        # Return an object of this model
        return cls(field,
                   order,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _field=(
            self.field
            if hasattr(self, "field")
            else None
        )
        _order=(
            self.order
            if hasattr(self, "order")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"field={_field!r}, "
            f"order={_order!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _field=(
            self.field
            if hasattr(self, "field")
            else None
        )
        _order=(
            self.order
            if hasattr(self, "order")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"field={_field!s}, "
            f"order={_order!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
