"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Field38(object):
    """Implementation of the 'field38' enum.

    Attributes:
        ID: The enum member of type str.
        COMPANY_ID: The enum member of type str.
        MERCHANT_ID: The enum member of type str.
        SERVICE: The enum member of type str.
        DEPOSIT_TYPES: The enum member of type str.
        DEPOSIT_AMOUNT: The enum member of type str.
        BATCH_AMOUNT: The enum member of type str.
        ADJUSTMENT_AMOUNT: The enum member of type str.
        RETAINED_AMOUNT: The enum member of type str.
        CONVEYED_AMOUNT: The enum member of type str.
        FEE_AMOUNT: The enum member of type str.
        REFERENCE_NUMBER: The enum member of type str.
        TRACE_NUMBER: The enum member of type str.
        CURRENCY: The enum member of type str.
        CREATED_TS: The enum member of type str.
        REPORTED_DATE: The enum member of type str.
        TRANSACTION_DATE: The enum member of type str.
        DEPOSIT_ACCOUNT: The enum member of type str.
        DETAILS: The enum member of type str.
        LOCATION_ID: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    ID = "id"

    COMPANY_ID = "company_id"

    MERCHANT_ID = "merchant_id"

    SERVICE = "service"

    DEPOSIT_TYPES = "deposit_types"

    DEPOSIT_AMOUNT = "deposit_amount"

    BATCH_AMOUNT = "batch_amount"

    ADJUSTMENT_AMOUNT = "adjustment_amount"

    RETAINED_AMOUNT = "retained_amount"

    CONVEYED_AMOUNT = "conveyed_amount"

    FEE_AMOUNT = "fee_amount"

    REFERENCE_NUMBER = "reference_number"

    TRACE_NUMBER = "trace_number"

    CURRENCY = "currency"

    CREATED_TS = "created_ts"

    REPORTED_DATE = "reported_date"

    TRANSACTION_DATE = "transaction_date"

    DEPOSIT_ACCOUNT = "deposit_account"

    DETAILS = "details"

    LOCATION_ID = "location_id"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
