"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper
from fortisapi.models.field_18 import Field18
from fortisapi.models.settings import Settings


class Footer2(object):
    """Implementation of the 'Footer2' model.

    Attributes:
        settings (Settings): The model property of type Settings.
        fields (List[Field18]): The model property of type List[Field18].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "settings": "settings",
        "fields": "fields",
    }

    _optionals = [
        "settings",
        "fields",
    ]

    def __init__(
        self,
        settings=APIHelper.SKIP,
        fields=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Footer2 instance."""
        # Initialize members of the class
        if settings is not APIHelper.SKIP:
            self.settings = settings
        if fields is not APIHelper.SKIP:
            self.fields = fields

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        settings =\
            Settings.from_dictionary(
                dictionary.get("settings"))\
                if "settings" in dictionary.keys()\
                else APIHelper.SKIP
        fields = None
        if dictionary.get("fields") is not None:
            fields = [
                Field18.from_dictionary(x)
                    for x in dictionary.get("fields")
            ]
        else:
            fields = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(settings,
                   fields,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _settings=(
            self.settings
            if hasattr(self, "settings")
            else None
        )
        _fields=(
            self.fields
            if hasattr(self, "fields")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"settings={_settings!r}, "
            f"fields={_fields!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _settings=(
            self.settings
            if hasattr(self, "settings")
            else None
        )
        _fields=(
            self.fields
            if hasattr(self, "fields")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"settings={_settings!s}, "
            f"fields={_fields!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
