"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper


class Forecast(object):
    """Implementation of the 'Forecast' model.

    Forecast Information on `expand`

    Attributes:
        id (str): ID
        recurring_id (str): Recurring ID
        recurring_type (float): Recurring Type
        amount (float): Amount
        month (str): Month
        created_ts (int): Created Time Stamp
        modified_ts (int): Modified Time Stamp
        additional_properties (Dict[str, object]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "recurring_id": "recurring_id",
        "recurring_type": "recurring_type",
        "amount": "amount",
        "month": "month",
        "created_ts": "created_ts",
        "modified_ts": "modified_ts",
    }

    _optionals = [
        "id",
        "recurring_id",
        "recurring_type",
        "amount",
        "month",
        "created_ts",
        "modified_ts",
    ]

    _nullables = [
        "recurring_type",
        "amount",
        "month",
        "created_ts",
        "modified_ts",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        recurring_id=APIHelper.SKIP,
        recurring_type=APIHelper.SKIP,
        amount=APIHelper.SKIP,
        month=APIHelper.SKIP,
        created_ts=APIHelper.SKIP,
        modified_ts=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Forecast instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if recurring_id is not APIHelper.SKIP:
            self.recurring_id = recurring_id
        if recurring_type is not APIHelper.SKIP:
            self.recurring_type = recurring_type
        if amount is not APIHelper.SKIP:
            self.amount = amount
        if month is not APIHelper.SKIP:
            self.month = month
        if created_ts is not APIHelper.SKIP:
            self.created_ts = created_ts
        if modified_ts is not APIHelper.SKIP:
            self.modified_ts = modified_ts

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        recurring_id =\
            dictionary.get("recurring_id")\
            if dictionary.get("recurring_id")\
                else APIHelper.SKIP
        recurring_type =\
            dictionary.get("recurring_type")\
            if "recurring_type" in dictionary.keys()\
                else APIHelper.SKIP
        amount =\
            dictionary.get("amount")\
            if "amount" in dictionary.keys()\
                else APIHelper.SKIP
        month =\
            dictionary.get("month")\
            if "month" in dictionary.keys()\
                else APIHelper.SKIP
        created_ts =\
            dictionary.get("created_ts")\
            if "created_ts" in dictionary.keys()\
                else APIHelper.SKIP
        modified_ts =\
            dictionary.get("modified_ts")\
            if "modified_ts" in dictionary.keys()\
                else APIHelper.SKIP

        # Clean out expected properties from dictionary
        additional_properties =\
            {k: v for k, v in dictionary.items() if k not in cls._names.values()}

        # Return an object of this model
        return cls(id,
                   recurring_id,
                   recurring_type,
                   amount,
                   month,
                   created_ts,
                   modified_ts,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _recurring_id=(
            self.recurring_id
            if hasattr(self, "recurring_id")
            else None
        )
        _recurring_type=(
            self.recurring_type
            if hasattr(self, "recurring_type")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _month=(
            self.month
            if hasattr(self, "month")
            else None
        )
        _created_ts=(
            self.created_ts
            if hasattr(self, "created_ts")
            else None
        )
        _modified_ts=(
            self.modified_ts
            if hasattr(self, "modified_ts")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"recurring_id={_recurring_id!r}, "
            f"recurring_type={_recurring_type!r}, "
            f"amount={_amount!r}, "
            f"month={_month!r}, "
            f"created_ts={_created_ts!r}, "
            f"modified_ts={_modified_ts!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _recurring_id=(
            self.recurring_id
            if hasattr(self, "recurring_id")
            else None
        )
        _recurring_type=(
            self.recurring_type
            if hasattr(self, "recurring_type")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _month=(
            self.month
            if hasattr(self, "month")
            else None
        )
        _created_ts=(
            self.created_ts
            if hasattr(self, "created_ts")
            else None
        )
        _modified_ts=(
            self.modified_ts
            if hasattr(self, "modified_ts")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"recurring_id={_recurring_id!s}, "
            f"recurring_type={_recurring_type!s}, "
            f"amount={_amount!s}, "
            f"month={_month!s}, "
            f"created_ts={_created_ts!s}, "
            f"modified_ts={_modified_ts!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
