"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper


class HomePhone(object):
    """Implementation of the 'HomePhone' model.

    The home phone provided by the Cardholder. Refer to ITU-E.164 for additional
    information on format and length.
    This field is required if available, unless market or regional mandate restricts
    sending this information.

    Attributes:
        cc (str): Country Code of the phone
        subscriber (str): Subscriber section of the number
        additional_properties (Dict[str, object]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "cc": "cc",
        "subscriber": "subscriber",
    }

    _optionals = [
        "cc",
        "subscriber",
    ]

    def __init__(
        self,
        cc=APIHelper.SKIP,
        subscriber=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a HomePhone instance."""
        # Initialize members of the class
        if cc is not APIHelper.SKIP:
            self.cc = cc
        if subscriber is not APIHelper.SKIP:
            self.subscriber = subscriber

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        cc =\
            dictionary.get("cc")\
            if dictionary.get("cc")\
                else APIHelper.SKIP
        subscriber =\
            dictionary.get("subscriber")\
            if dictionary.get("subscriber")\
                else APIHelper.SKIP

        # Clean out expected properties from dictionary
        additional_properties =\
            {k: v for k, v in dictionary.items() if k not in cls._names.values()}

        # Return an object of this model
        return cls(cc,
                   subscriber,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _cc=(
            self.cc
            if hasattr(self, "cc")
            else None
        )
        _subscriber=(
            self.subscriber
            if hasattr(self, "subscriber")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"cc={_cc!r}, "
            f"subscriber={_subscriber!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _cc=(
            self.cc
            if hasattr(self, "cc")
            else None
        )
        _subscriber=(
            self.subscriber
            if hasattr(self, "subscriber")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"cc={_cc!s}, "
            f"subscriber={_subscriber!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
