"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper
from fortisapi.models.field_configuration import (
    FieldConfiguration,
)


class HostedPaymentPage(object):
    """Implementation of the 'HostedPaymentPage' model.

    Hosted Payment Page Information on `expand`

    Attributes:
        user_id (str): User ID
        location_id (str): Location ID
        location_api_id (str): Location Api Id
        product_transaction_id (str): Product Transaction ID
        title (str): Title
        redirect_url_delay (float): Redirect Url Delay
        min_payment_amount (int): Min Payment Amount
        max_payment_amount (int): Max Payment Amount
        redirect_url_on_approve (str): Redirect Url On Approval
        redirect_url_on_decline (str): Redirect Url On Decline
        field_configuration (FieldConfiguration): field_configuration
        encryption_key (str): Encryption Key
        stylesheet_url (str): Stylesheet Url
        parent_send_message (bool): Parent Send Message
        hide_optional_fields (bool): Hide Optional Fields
        id (str): Hosted Payment Page Id
        created_ts (int): Created Time Stamp
        modified_ts (int): Modified Time Stamp
        created_user_id (str): System generated id for user who created record
        modified_user_id (str): System generated id for user who created record
        additional_properties (Dict[str, object]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "user_id": "user_id",
        "location_id": "location_id",
        "location_api_id": "location_api_id",
        "product_transaction_id": "product_transaction_id",
        "title": "title",
        "redirect_url_delay": "redirect_url_delay",
        "min_payment_amount": "min_payment_amount",
        "max_payment_amount": "max_payment_amount",
        "redirect_url_on_approve": "redirect_url_on_approve",
        "redirect_url_on_decline": "redirect_url_on_decline",
        "field_configuration": "field_configuration",
        "encryption_key": "encryption_key",
        "stylesheet_url": "stylesheet_url",
        "parent_send_message": "parent_send_message",
        "hide_optional_fields": "hide_optional_fields",
        "id": "id",
        "created_ts": "created_ts",
        "modified_ts": "modified_ts",
        "created_user_id": "created_user_id",
        "modified_user_id": "modified_user_id",
    }

    _optionals = [
        "user_id",
        "location_id",
        "location_api_id",
        "product_transaction_id",
        "title",
        "redirect_url_delay",
        "min_payment_amount",
        "max_payment_amount",
        "redirect_url_on_approve",
        "redirect_url_on_decline",
        "field_configuration",
        "encryption_key",
        "stylesheet_url",
        "parent_send_message",
        "hide_optional_fields",
        "id",
        "created_ts",
        "modified_ts",
        "created_user_id",
        "modified_user_id",
    ]

    _nullables = [
        "user_id",
        "location_id",
        "location_api_id",
        "redirect_url_delay",
        "min_payment_amount",
        "max_payment_amount",
        "redirect_url_on_approve",
        "redirect_url_on_decline",
        "encryption_key",
        "stylesheet_url",
        "created_user_id",
        "modified_user_id",
    ]

    def __init__(
        self,
        user_id=APIHelper.SKIP,
        location_id=APIHelper.SKIP,
        location_api_id=APIHelper.SKIP,
        product_transaction_id=APIHelper.SKIP,
        title=APIHelper.SKIP,
        redirect_url_delay=15,
        min_payment_amount=APIHelper.SKIP,
        max_payment_amount=9999999999,
        redirect_url_on_approve=APIHelper.SKIP,
        redirect_url_on_decline=APIHelper.SKIP,
        field_configuration=APIHelper.SKIP,
        encryption_key=APIHelper.SKIP,
        stylesheet_url=APIHelper.SKIP,
        parent_send_message=APIHelper.SKIP,
        hide_optional_fields=APIHelper.SKIP,
        id=APIHelper.SKIP,
        created_ts=APIHelper.SKIP,
        modified_ts=APIHelper.SKIP,
        created_user_id=APIHelper.SKIP,
        modified_user_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a HostedPaymentPage instance."""
        # Initialize members of the class
        if user_id is not APIHelper.SKIP:
            self.user_id = user_id
        if location_id is not APIHelper.SKIP:
            self.location_id = location_id
        if location_api_id is not APIHelper.SKIP:
            self.location_api_id = location_api_id
        if product_transaction_id is not APIHelper.SKIP:
            self.product_transaction_id = product_transaction_id
        if title is not APIHelper.SKIP:
            self.title = title
        self.redirect_url_delay = redirect_url_delay
        if min_payment_amount is not APIHelper.SKIP:
            self.min_payment_amount = min_payment_amount
        self.max_payment_amount = max_payment_amount
        if redirect_url_on_approve is not APIHelper.SKIP:
            self.redirect_url_on_approve = redirect_url_on_approve
        if redirect_url_on_decline is not APIHelper.SKIP:
            self.redirect_url_on_decline = redirect_url_on_decline
        if field_configuration is not APIHelper.SKIP:
            self.field_configuration = field_configuration
        if encryption_key is not APIHelper.SKIP:
            self.encryption_key = encryption_key
        if stylesheet_url is not APIHelper.SKIP:
            self.stylesheet_url = stylesheet_url
        if parent_send_message is not APIHelper.SKIP:
            self.parent_send_message = parent_send_message
        if hide_optional_fields is not APIHelper.SKIP:
            self.hide_optional_fields = hide_optional_fields
        if id is not APIHelper.SKIP:
            self.id = id
        if created_ts is not APIHelper.SKIP:
            self.created_ts = created_ts
        if modified_ts is not APIHelper.SKIP:
            self.modified_ts = modified_ts
        if created_user_id is not APIHelper.SKIP:
            self.created_user_id = created_user_id
        if modified_user_id is not APIHelper.SKIP:
            self.modified_user_id = modified_user_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        user_id =\
            dictionary.get("user_id")\
            if "user_id" in dictionary.keys()\
                else APIHelper.SKIP
        location_id =\
            dictionary.get("location_id")\
            if "location_id" in dictionary.keys()\
                else APIHelper.SKIP
        location_api_id =\
            dictionary.get("location_api_id")\
            if "location_api_id" in dictionary.keys()\
                else APIHelper.SKIP
        product_transaction_id =\
            dictionary.get("product_transaction_id")\
            if dictionary.get("product_transaction_id")\
                else APIHelper.SKIP
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else APIHelper.SKIP
        redirect_url_delay =\
            dictionary.get("redirect_url_delay")\
            if dictionary.get("redirect_url_delay")\
                else 15
        min_payment_amount =\
            dictionary.get("min_payment_amount")\
            if "min_payment_amount" in dictionary.keys()\
                else APIHelper.SKIP
        max_payment_amount =\
            dictionary.get("max_payment_amount")\
            if dictionary.get("max_payment_amount")\
                else 9999999999
        redirect_url_on_approve =\
            dictionary.get("redirect_url_on_approve")\
            if "redirect_url_on_approve" in dictionary.keys()\
                else APIHelper.SKIP
        redirect_url_on_decline =\
            dictionary.get("redirect_url_on_decline")\
            if "redirect_url_on_decline" in dictionary.keys()\
                else APIHelper.SKIP
        field_configuration =\
            FieldConfiguration.from_dictionary(
                dictionary.get("field_configuration"))\
                if "field_configuration" in dictionary.keys()\
                else APIHelper.SKIP
        encryption_key =\
            dictionary.get("encryption_key")\
            if "encryption_key" in dictionary.keys()\
                else APIHelper.SKIP
        stylesheet_url =\
            dictionary.get("stylesheet_url")\
            if "stylesheet_url" in dictionary.keys()\
                else APIHelper.SKIP
        parent_send_message =\
            dictionary.get("parent_send_message")\
            if "parent_send_message" in dictionary.keys()\
                else APIHelper.SKIP
        hide_optional_fields =\
            dictionary.get("hide_optional_fields")\
            if "hide_optional_fields" in dictionary.keys()\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        created_ts =\
            dictionary.get("created_ts")\
            if dictionary.get("created_ts")\
                else APIHelper.SKIP
        modified_ts =\
            dictionary.get("modified_ts")\
            if dictionary.get("modified_ts")\
                else APIHelper.SKIP
        created_user_id =\
            dictionary.get("created_user_id")\
            if "created_user_id" in dictionary.keys()\
                else APIHelper.SKIP
        modified_user_id =\
            dictionary.get("modified_user_id")\
            if "modified_user_id" in dictionary.keys()\
                else APIHelper.SKIP

        # Clean out expected properties from dictionary
        additional_properties =\
            {k: v for k, v in dictionary.items() if k not in cls._names.values()}

        # Return an object of this model
        return cls(user_id,
                   location_id,
                   location_api_id,
                   product_transaction_id,
                   title,
                   redirect_url_delay,
                   min_payment_amount,
                   max_payment_amount,
                   redirect_url_on_approve,
                   redirect_url_on_decline,
                   field_configuration,
                   encryption_key,
                   stylesheet_url,
                   parent_send_message,
                   hide_optional_fields,
                   id,
                   created_ts,
                   modified_ts,
                   created_user_id,
                   modified_user_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        _location_id=(
            self.location_id
            if hasattr(self, "location_id")
            else None
        )
        _location_api_id=(
            self.location_api_id
            if hasattr(self, "location_api_id")
            else None
        )
        _product_transaction_id=(
            self.product_transaction_id
            if hasattr(self, "product_transaction_id")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _redirect_url_delay=(
            self.redirect_url_delay
            if hasattr(self, "redirect_url_delay")
            else None
        )
        _min_payment_amount=(
            self.min_payment_amount
            if hasattr(self, "min_payment_amount")
            else None
        )
        _max_payment_amount=(
            self.max_payment_amount
            if hasattr(self, "max_payment_amount")
            else None
        )
        _redirect_url_on_approve=(
            self.redirect_url_on_approve
            if hasattr(self, "redirect_url_on_approve")
            else None
        )
        _redirect_url_on_decline=(
            self.redirect_url_on_decline
            if hasattr(self, "redirect_url_on_decline")
            else None
        )
        _field_configuration=(
            self.field_configuration
            if hasattr(self, "field_configuration")
            else None
        )
        _encryption_key=(
            self.encryption_key
            if hasattr(self, "encryption_key")
            else None
        )
        _stylesheet_url=(
            self.stylesheet_url
            if hasattr(self, "stylesheet_url")
            else None
        )
        _parent_send_message=(
            self.parent_send_message
            if hasattr(self, "parent_send_message")
            else None
        )
        _hide_optional_fields=(
            self.hide_optional_fields
            if hasattr(self, "hide_optional_fields")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _created_ts=(
            self.created_ts
            if hasattr(self, "created_ts")
            else None
        )
        _modified_ts=(
            self.modified_ts
            if hasattr(self, "modified_ts")
            else None
        )
        _created_user_id=(
            self.created_user_id
            if hasattr(self, "created_user_id")
            else None
        )
        _modified_user_id=(
            self.modified_user_id
            if hasattr(self, "modified_user_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"user_id={_user_id!r}, "
            f"location_id={_location_id!r}, "
            f"location_api_id={_location_api_id!r}, "
            f"product_transaction_id={_product_transaction_id!r}, "
            f"title={_title!r}, "
            f"redirect_url_delay={_redirect_url_delay!r}, "
            f"min_payment_amount={_min_payment_amount!r}, "
            f"max_payment_amount={_max_payment_amount!r}, "
            f"redirect_url_on_approve={_redirect_url_on_approve!r}, "
            f"redirect_url_on_decline={_redirect_url_on_decline!r}, "
            f"field_configuration={_field_configuration!r}, "
            f"encryption_key={_encryption_key!r}, "
            f"stylesheet_url={_stylesheet_url!r}, "
            f"parent_send_message={_parent_send_message!r}, "
            f"hide_optional_fields={_hide_optional_fields!r}, "
            f"id={_id!r}, "
            f"created_ts={_created_ts!r}, "
            f"modified_ts={_modified_ts!r}, "
            f"created_user_id={_created_user_id!r}, "
            f"modified_user_id={_modified_user_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        _location_id=(
            self.location_id
            if hasattr(self, "location_id")
            else None
        )
        _location_api_id=(
            self.location_api_id
            if hasattr(self, "location_api_id")
            else None
        )
        _product_transaction_id=(
            self.product_transaction_id
            if hasattr(self, "product_transaction_id")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _redirect_url_delay=(
            self.redirect_url_delay
            if hasattr(self, "redirect_url_delay")
            else None
        )
        _min_payment_amount=(
            self.min_payment_amount
            if hasattr(self, "min_payment_amount")
            else None
        )
        _max_payment_amount=(
            self.max_payment_amount
            if hasattr(self, "max_payment_amount")
            else None
        )
        _redirect_url_on_approve=(
            self.redirect_url_on_approve
            if hasattr(self, "redirect_url_on_approve")
            else None
        )
        _redirect_url_on_decline=(
            self.redirect_url_on_decline
            if hasattr(self, "redirect_url_on_decline")
            else None
        )
        _field_configuration=(
            self.field_configuration
            if hasattr(self, "field_configuration")
            else None
        )
        _encryption_key=(
            self.encryption_key
            if hasattr(self, "encryption_key")
            else None
        )
        _stylesheet_url=(
            self.stylesheet_url
            if hasattr(self, "stylesheet_url")
            else None
        )
        _parent_send_message=(
            self.parent_send_message
            if hasattr(self, "parent_send_message")
            else None
        )
        _hide_optional_fields=(
            self.hide_optional_fields
            if hasattr(self, "hide_optional_fields")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _created_ts=(
            self.created_ts
            if hasattr(self, "created_ts")
            else None
        )
        _modified_ts=(
            self.modified_ts
            if hasattr(self, "modified_ts")
            else None
        )
        _created_user_id=(
            self.created_user_id
            if hasattr(self, "created_user_id")
            else None
        )
        _modified_user_id=(
            self.modified_user_id
            if hasattr(self, "modified_user_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"user_id={_user_id!s}, "
            f"location_id={_location_id!s}, "
            f"location_api_id={_location_api_id!s}, "
            f"product_transaction_id={_product_transaction_id!s}, "
            f"title={_title!s}, "
            f"redirect_url_delay={_redirect_url_delay!s}, "
            f"min_payment_amount={_min_payment_amount!s}, "
            f"max_payment_amount={_max_payment_amount!s}, "
            f"redirect_url_on_approve={_redirect_url_on_approve!s}, "
            f"redirect_url_on_decline={_redirect_url_on_decline!s}, "
            f"field_configuration={_field_configuration!s}, "
            f"encryption_key={_encryption_key!s}, "
            f"stylesheet_url={_stylesheet_url!s}, "
            f"parent_send_message={_parent_send_message!s}, "
            f"hide_optional_fields={_hide_optional_fields!s}, "
            f"id={_id!s}, "
            f"created_ts={_created_ts!s}, "
            f"modified_ts={_modified_ts!s}, "
            f"created_user_id={_created_user_id!s}, "
            f"modified_user_id={_modified_user_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
