"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class InitiationType(object):
    """Implementation of the 'InitiationType' enum.

    Initiation Type

    Attributes:
        C101: The enum member of type str.
        C102: The enum member of type str.
        C103: The enum member of type str.
        C104: The enum member of type str.
        M101: The enum member of type str.
        M102: The enum member of type str.
        M103: The enum member of type str.
        M104: The enum member of type str.
        M205: The enum member of type str.
        M206: The enum member of type str.
        M207: The enum member of type str.
        M208: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    C101 = "C101"

    C102 = "C102"

    C103 = "C103"

    C104 = "C104"

    M101 = "M101"

    M102 = "M102"

    M103 = "M103"

    M104 = "M104"

    M205 = "M205"

    M206 = "M206"

    M207 = "M207"

    M208 = "M208"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
