"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper
from fortisapi.models.line_item_13 import LineItem13


class Level3Data(object):
    """Implementation of the 'Level3Data' model.

    Level 3 data object

    Attributes:
        destination_country_code (str): Code of the country where the goods are being
            shipped.
        duty_amount (int): Fee amount associated with the import of the purchased
            goods ,Can accept Two (2) decimal places
        freight_amount (int): Freight or shipping portion of the total transaction
            amount ,Can accept Two (2) decimal places.
        national_tax (int): National tax for the transaction ,Can accept Two (2)
            decimal places.
        sales_tax (int): Sales tax for the transaction ,Can accept Two (2) decimal
            places.
        shipfrom_zip_code (str): Postal/ZIP code of the address from where the
            purchased goods are being shipped.
        shipto_zip_code (str): Postal/ZIP code of the address where purchased goods
            will be delivered.
        tax_amount (int): Amount of any value added taxes ,Can accept Two (2) decimal
            places.
        tax_exempt (Any): The model property of type Any.
        customer_vat_registration (str): Customer VAT Registration
        merchant_vat_registration (str): Merchant VAT Registration
        order_date (str): Order Date
        summary_commodity_code (str): Summary Commodity Code
        tax_rate (int): Tax rate used to calculate the sales tax amount, can accept 2
            decimal places.
        unique_vat_ref_number (str): Unique VAT Reference Number
        line_items (List[LineItem13]): Array of line items in transaction
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "destination_country_code": "destination_country_code",
        "duty_amount": "duty_amount",
        "freight_amount": "freight_amount",
        "national_tax": "national_tax",
        "sales_tax": "sales_tax",
        "shipfrom_zip_code": "shipfrom_zip_code",
        "shipto_zip_code": "shipto_zip_code",
        "tax_amount": "tax_amount",
        "tax_exempt": "tax_exempt",
        "customer_vat_registration": "customer_vat_registration",
        "merchant_vat_registration": "merchant_vat_registration",
        "order_date": "order_date",
        "summary_commodity_code": "summary_commodity_code",
        "tax_rate": "tax_rate",
        "unique_vat_ref_number": "unique_vat_ref_number",
        "line_items": "line_items",
    }

    _optionals = [
        "destination_country_code",
        "duty_amount",
        "freight_amount",
        "national_tax",
        "sales_tax",
        "shipfrom_zip_code",
        "shipto_zip_code",
        "tax_amount",
        "tax_exempt",
        "customer_vat_registration",
        "merchant_vat_registration",
        "order_date",
        "summary_commodity_code",
        "tax_rate",
        "unique_vat_ref_number",
        "line_items",
    ]

    _nullables = [
        "destination_country_code",
        "duty_amount",
        "freight_amount",
        "national_tax",
        "sales_tax",
        "shipfrom_zip_code",
        "shipto_zip_code",
        "tax_amount",
        "customer_vat_registration",
        "merchant_vat_registration",
        "order_date",
        "summary_commodity_code",
        "tax_rate",
        "unique_vat_ref_number",
    ]

    def __init__(
        self,
        destination_country_code=APIHelper.SKIP,
        duty_amount=APIHelper.SKIP,
        freight_amount=APIHelper.SKIP,
        national_tax=APIHelper.SKIP,
        sales_tax=APIHelper.SKIP,
        shipfrom_zip_code=APIHelper.SKIP,
        shipto_zip_code=APIHelper.SKIP,
        tax_amount=APIHelper.SKIP,
        tax_exempt=APIHelper.SKIP,
        customer_vat_registration=APIHelper.SKIP,
        merchant_vat_registration=APIHelper.SKIP,
        order_date=APIHelper.SKIP,
        summary_commodity_code=APIHelper.SKIP,
        tax_rate=APIHelper.SKIP,
        unique_vat_ref_number=APIHelper.SKIP,
        line_items=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Level3Data instance."""
        # Initialize members of the class
        if destination_country_code is not APIHelper.SKIP:
            self.destination_country_code = destination_country_code
        if duty_amount is not APIHelper.SKIP:
            self.duty_amount = duty_amount
        if freight_amount is not APIHelper.SKIP:
            self.freight_amount = freight_amount
        if national_tax is not APIHelper.SKIP:
            self.national_tax = national_tax
        if sales_tax is not APIHelper.SKIP:
            self.sales_tax = sales_tax
        if shipfrom_zip_code is not APIHelper.SKIP:
            self.shipfrom_zip_code = shipfrom_zip_code
        if shipto_zip_code is not APIHelper.SKIP:
            self.shipto_zip_code = shipto_zip_code
        if tax_amount is not APIHelper.SKIP:
            self.tax_amount = tax_amount
        if tax_exempt is not APIHelper.SKIP:
            self.tax_exempt = tax_exempt
        if customer_vat_registration is not APIHelper.SKIP:
            self.customer_vat_registration = customer_vat_registration
        if merchant_vat_registration is not APIHelper.SKIP:
            self.merchant_vat_registration = merchant_vat_registration
        if order_date is not APIHelper.SKIP:
            self.order_date = order_date
        if summary_commodity_code is not APIHelper.SKIP:
            self.summary_commodity_code = summary_commodity_code
        if tax_rate is not APIHelper.SKIP:
            self.tax_rate = tax_rate
        if unique_vat_ref_number is not APIHelper.SKIP:
            self.unique_vat_ref_number = unique_vat_ref_number
        if line_items is not APIHelper.SKIP:
            self.line_items = line_items

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        destination_country_code =\
            dictionary.get("destination_country_code")\
            if "destination_country_code" in dictionary.keys()\
                else APIHelper.SKIP
        duty_amount =\
            dictionary.get("duty_amount")\
            if "duty_amount" in dictionary.keys()\
                else APIHelper.SKIP
        freight_amount =\
            dictionary.get("freight_amount")\
            if "freight_amount" in dictionary.keys()\
                else APIHelper.SKIP
        national_tax =\
            dictionary.get("national_tax")\
            if "national_tax" in dictionary.keys()\
                else APIHelper.SKIP
        sales_tax =\
            dictionary.get("sales_tax")\
            if "sales_tax" in dictionary.keys()\
                else APIHelper.SKIP
        shipfrom_zip_code =\
            dictionary.get("shipfrom_zip_code")\
            if "shipfrom_zip_code" in dictionary.keys()\
                else APIHelper.SKIP
        shipto_zip_code =\
            dictionary.get("shipto_zip_code")\
            if "shipto_zip_code" in dictionary.keys()\
                else APIHelper.SKIP
        tax_amount =\
            dictionary.get("tax_amount")\
            if "tax_amount" in dictionary.keys()\
                else APIHelper.SKIP
        tax_exempt =\
            dictionary.get("tax_exempt")\
            if dictionary.get("tax_exempt")\
                else APIHelper.SKIP
        customer_vat_registration =\
            dictionary.get("customer_vat_registration")\
            if "customer_vat_registration" in dictionary.keys()\
                else APIHelper.SKIP
        merchant_vat_registration =\
            dictionary.get("merchant_vat_registration")\
            if "merchant_vat_registration" in dictionary.keys()\
                else APIHelper.SKIP
        order_date =\
            dictionary.get("order_date")\
            if "order_date" in dictionary.keys()\
                else APIHelper.SKIP
        summary_commodity_code =\
            dictionary.get("summary_commodity_code")\
            if "summary_commodity_code" in dictionary.keys()\
                else APIHelper.SKIP
        tax_rate =\
            dictionary.get("tax_rate")\
            if "tax_rate" in dictionary.keys()\
                else APIHelper.SKIP
        unique_vat_ref_number =\
            dictionary.get("unique_vat_ref_number")\
            if "unique_vat_ref_number" in dictionary.keys()\
                else APIHelper.SKIP
        line_items = None
        if dictionary.get("line_items") is not None:
            line_items = [
                LineItem13.from_dictionary(x)
                    for x in dictionary.get("line_items")
            ]
        else:
            line_items = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(destination_country_code,
                   duty_amount,
                   freight_amount,
                   national_tax,
                   sales_tax,
                   shipfrom_zip_code,
                   shipto_zip_code,
                   tax_amount,
                   tax_exempt,
                   customer_vat_registration,
                   merchant_vat_registration,
                   order_date,
                   summary_commodity_code,
                   tax_rate,
                   unique_vat_ref_number,
                   line_items,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _destination_country_code=(
            self.destination_country_code
            if hasattr(self, "destination_country_code")
            else None
        )
        _duty_amount=(
            self.duty_amount
            if hasattr(self, "duty_amount")
            else None
        )
        _freight_amount=(
            self.freight_amount
            if hasattr(self, "freight_amount")
            else None
        )
        _national_tax=(
            self.national_tax
            if hasattr(self, "national_tax")
            else None
        )
        _sales_tax=(
            self.sales_tax
            if hasattr(self, "sales_tax")
            else None
        )
        _shipfrom_zip_code=(
            self.shipfrom_zip_code
            if hasattr(self, "shipfrom_zip_code")
            else None
        )
        _shipto_zip_code=(
            self.shipto_zip_code
            if hasattr(self, "shipto_zip_code")
            else None
        )
        _tax_amount=(
            self.tax_amount
            if hasattr(self, "tax_amount")
            else None
        )
        _tax_exempt=(
            self.tax_exempt
            if hasattr(self, "tax_exempt")
            else None
        )
        _customer_vat_registration=(
            self.customer_vat_registration
            if hasattr(self, "customer_vat_registration")
            else None
        )
        _merchant_vat_registration=(
            self.merchant_vat_registration
            if hasattr(self, "merchant_vat_registration")
            else None
        )
        _order_date=(
            self.order_date
            if hasattr(self, "order_date")
            else None
        )
        _summary_commodity_code=(
            self.summary_commodity_code
            if hasattr(self, "summary_commodity_code")
            else None
        )
        _tax_rate=(
            self.tax_rate
            if hasattr(self, "tax_rate")
            else None
        )
        _unique_vat_ref_number=(
            self.unique_vat_ref_number
            if hasattr(self, "unique_vat_ref_number")
            else None
        )
        _line_items=(
            self.line_items
            if hasattr(self, "line_items")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"destination_country_code={_destination_country_code!r}, "
            f"duty_amount={_duty_amount!r}, "
            f"freight_amount={_freight_amount!r}, "
            f"national_tax={_national_tax!r}, "
            f"sales_tax={_sales_tax!r}, "
            f"shipfrom_zip_code={_shipfrom_zip_code!r}, "
            f"shipto_zip_code={_shipto_zip_code!r}, "
            f"tax_amount={_tax_amount!r}, "
            f"tax_exempt={_tax_exempt!r}, "
            f"customer_vat_registration={_customer_vat_registration!r}, "
            f"merchant_vat_registration={_merchant_vat_registration!r}, "
            f"order_date={_order_date!r}, "
            f"summary_commodity_code={_summary_commodity_code!r}, "
            f"tax_rate={_tax_rate!r}, "
            f"unique_vat_ref_number={_unique_vat_ref_number!r}, "
            f"line_items={_line_items!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _destination_country_code=(
            self.destination_country_code
            if hasattr(self, "destination_country_code")
            else None
        )
        _duty_amount=(
            self.duty_amount
            if hasattr(self, "duty_amount")
            else None
        )
        _freight_amount=(
            self.freight_amount
            if hasattr(self, "freight_amount")
            else None
        )
        _national_tax=(
            self.national_tax
            if hasattr(self, "national_tax")
            else None
        )
        _sales_tax=(
            self.sales_tax
            if hasattr(self, "sales_tax")
            else None
        )
        _shipfrom_zip_code=(
            self.shipfrom_zip_code
            if hasattr(self, "shipfrom_zip_code")
            else None
        )
        _shipto_zip_code=(
            self.shipto_zip_code
            if hasattr(self, "shipto_zip_code")
            else None
        )
        _tax_amount=(
            self.tax_amount
            if hasattr(self, "tax_amount")
            else None
        )
        _tax_exempt=(
            self.tax_exempt
            if hasattr(self, "tax_exempt")
            else None
        )
        _customer_vat_registration=(
            self.customer_vat_registration
            if hasattr(self, "customer_vat_registration")
            else None
        )
        _merchant_vat_registration=(
            self.merchant_vat_registration
            if hasattr(self, "merchant_vat_registration")
            else None
        )
        _order_date=(
            self.order_date
            if hasattr(self, "order_date")
            else None
        )
        _summary_commodity_code=(
            self.summary_commodity_code
            if hasattr(self, "summary_commodity_code")
            else None
        )
        _tax_rate=(
            self.tax_rate
            if hasattr(self, "tax_rate")
            else None
        )
        _unique_vat_ref_number=(
            self.unique_vat_ref_number
            if hasattr(self, "unique_vat_ref_number")
            else None
        )
        _line_items=(
            self.line_items
            if hasattr(self, "line_items")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"destination_country_code={_destination_country_code!s}, "
            f"duty_amount={_duty_amount!s}, "
            f"freight_amount={_freight_amount!s}, "
            f"national_tax={_national_tax!s}, "
            f"sales_tax={_sales_tax!s}, "
            f"shipfrom_zip_code={_shipfrom_zip_code!s}, "
            f"shipto_zip_code={_shipto_zip_code!s}, "
            f"tax_amount={_tax_amount!s}, "
            f"tax_exempt={_tax_exempt!s}, "
            f"customer_vat_registration={_customer_vat_registration!s}, "
            f"merchant_vat_registration={_merchant_vat_registration!s}, "
            f"order_date={_order_date!s}, "
            f"summary_commodity_code={_summary_commodity_code!s}, "
            f"tax_rate={_tax_rate!s}, "
            f"unique_vat_ref_number={_unique_vat_ref_number!s}, "
            f"line_items={_line_items!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
