"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper


class Pagination(object):
    """Implementation of the 'Pagination' model.

    Pagination info

    Attributes:
        mtype (Type3): The model property of type Type3.
        total_count (int): Total records count
        page_count (int): Total page count
        page_number (int): Current page
        page_size (int): Page size
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "total_count": "total_count",
        "page_count": "page_count",
        "page_number": "page_number",
        "page_size": "page_size",
    }

    _optionals = [
        "mtype",
        "total_count",
        "page_count",
        "page_number",
        "page_size",
    ]

    def __init__(
        self,
        mtype=APIHelper.SKIP,
        total_count=APIHelper.SKIP,
        page_count=APIHelper.SKIP,
        page_number=APIHelper.SKIP,
        page_size=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Pagination instance."""
        # Initialize members of the class
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if total_count is not APIHelper.SKIP:
            self.total_count = total_count
        if page_count is not APIHelper.SKIP:
            self.page_count = page_count
        if page_number is not APIHelper.SKIP:
            self.page_number = page_number
        if page_size is not APIHelper.SKIP:
            self.page_size = page_size

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        total_count =\
            dictionary.get("total_count")\
            if dictionary.get("total_count")\
                else APIHelper.SKIP
        page_count =\
            dictionary.get("page_count")\
            if dictionary.get("page_count")\
                else APIHelper.SKIP
        page_number =\
            dictionary.get("page_number")\
            if dictionary.get("page_number")\
                else APIHelper.SKIP
        page_size =\
            dictionary.get("page_size")\
            if dictionary.get("page_size")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   total_count,
                   page_count,
                   page_number,
                   page_size,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _total_count=(
            self.total_count
            if hasattr(self, "total_count")
            else None
        )
        _page_count=(
            self.page_count
            if hasattr(self, "page_count")
            else None
        )
        _page_number=(
            self.page_number
            if hasattr(self, "page_number")
            else None
        )
        _page_size=(
            self.page_size
            if hasattr(self, "page_size")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"total_count={_total_count!r}, "
            f"page_count={_page_count!r}, "
            f"page_number={_page_number!r}, "
            f"page_size={_page_size!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _total_count=(
            self.total_count
            if hasattr(self, "total_count")
            else None
        )
        _page_count=(
            self.page_count
            if hasattr(self, "page_count")
            else None
        )
        _page_number=(
            self.page_number
            if hasattr(self, "page_number")
            else None
        )
        _page_size=(
            self.page_size
            if hasattr(self, "page_size")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"total_count={_total_count!s}, "
            f"page_count={_page_count!s}, "
            f"page_number={_page_number!s}, "
            f"page_size={_page_size!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
