"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper


class ProductInvoice(object):
    """Implementation of the 'ProductInvoice' model.

    Product Invoice Information on `expand`

    Attributes:
        title (str): Title
        quote_number_format (str): Quote Number Format
        quote_number_start (float): Quote Number Start
        quote_number_increment (float): Quote Number Increment
        quote_number_current (float): Quote Number Current
        invoice_number_format (str): Invoice Number Format
        invoice_number_start (float): Invoice Number Start
        invoice_number_increment (float): Invoice Number Increment
        invoice_number_current (float): Invoice Number Current
        tax_rate (float): Tax Rate
        tax_fee (int): Tax Fee
        monthly_fee (int): Monthly Fees
        per_invoice_fee (int): Per Invoice Fee
        per_quote_fee (int): Per Quote fee
        require_pay_in_full (bool): Require Pay In Full
        selectable (float): Selectable
        reportable (float): Reportable
        portfolio_id (str): Portfolio Id
        location_id (str): Location ID
        id (str): Product Invoice Id
        created_ts (int): Created Time Stamp
        modified_ts (int): Modified Time Stamp
        created_user_id (str): User ID Created the register
        modified_user_id (str): Last User ID that updated the register
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "title": "title",
        "quote_number_format": "quote_number_format",
        "quote_number_start": "quote_number_start",
        "quote_number_increment": "quote_number_increment",
        "quote_number_current": "quote_number_current",
        "invoice_number_format": "invoice_number_format",
        "invoice_number_start": "invoice_number_start",
        "invoice_number_increment": "invoice_number_increment",
        "invoice_number_current": "invoice_number_current",
        "tax_rate": "tax_rate",
        "tax_fee": "tax_fee",
        "monthly_fee": "monthly_fee",
        "per_invoice_fee": "per_invoice_fee",
        "per_quote_fee": "per_quote_fee",
        "require_pay_in_full": "require_pay_in_full",
        "selectable": "selectable",
        "reportable": "reportable",
        "portfolio_id": "portfolio_id",
        "location_id": "location_id",
        "id": "id",
        "created_ts": "created_ts",
        "modified_ts": "modified_ts",
        "created_user_id": "created_user_id",
        "modified_user_id": "modified_user_id",
    }

    _optionals = [
        "title",
        "quote_number_format",
        "quote_number_start",
        "quote_number_increment",
        "quote_number_current",
        "invoice_number_format",
        "invoice_number_start",
        "invoice_number_increment",
        "invoice_number_current",
        "tax_rate",
        "tax_fee",
        "monthly_fee",
        "per_invoice_fee",
        "per_quote_fee",
        "require_pay_in_full",
        "selectable",
        "reportable",
        "portfolio_id",
        "location_id",
        "id",
        "created_ts",
        "modified_ts",
        "created_user_id",
        "modified_user_id",
    ]

    _nullables = [
        "quote_number_format",
        "quote_number_start",
        "quote_number_increment",
        "quote_number_current",
        "invoice_number_format",
        "invoice_number_start",
        "invoice_number_increment",
        "invoice_number_current",
        "tax_fee",
        "monthly_fee",
        "selectable",
        "reportable",
        "portfolio_id",
        "created_user_id",
        "modified_user_id",
    ]

    def __init__(
        self,
        title=APIHelper.SKIP,
        quote_number_format=APIHelper.SKIP,
        quote_number_start=APIHelper.SKIP,
        quote_number_increment=APIHelper.SKIP,
        quote_number_current=APIHelper.SKIP,
        invoice_number_format=APIHelper.SKIP,
        invoice_number_start=APIHelper.SKIP,
        invoice_number_increment=APIHelper.SKIP,
        invoice_number_current=APIHelper.SKIP,
        tax_rate=APIHelper.SKIP,
        tax_fee=APIHelper.SKIP,
        monthly_fee=APIHelper.SKIP,
        per_invoice_fee=APIHelper.SKIP,
        per_quote_fee=APIHelper.SKIP,
        require_pay_in_full=APIHelper.SKIP,
        selectable=APIHelper.SKIP,
        reportable=APIHelper.SKIP,
        portfolio_id=APIHelper.SKIP,
        location_id=APIHelper.SKIP,
        id=APIHelper.SKIP,
        created_ts=APIHelper.SKIP,
        modified_ts=APIHelper.SKIP,
        created_user_id=APIHelper.SKIP,
        modified_user_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ProductInvoice instance."""
        # Initialize members of the class
        if title is not APIHelper.SKIP:
            self.title = title
        if quote_number_format is not APIHelper.SKIP:
            self.quote_number_format = quote_number_format
        if quote_number_start is not APIHelper.SKIP:
            self.quote_number_start = quote_number_start
        if quote_number_increment is not APIHelper.SKIP:
            self.quote_number_increment = quote_number_increment
        if quote_number_current is not APIHelper.SKIP:
            self.quote_number_current = quote_number_current
        if invoice_number_format is not APIHelper.SKIP:
            self.invoice_number_format = invoice_number_format
        if invoice_number_start is not APIHelper.SKIP:
            self.invoice_number_start = invoice_number_start
        if invoice_number_increment is not APIHelper.SKIP:
            self.invoice_number_increment = invoice_number_increment
        if invoice_number_current is not APIHelper.SKIP:
            self.invoice_number_current = invoice_number_current
        if tax_rate is not APIHelper.SKIP:
            self.tax_rate = tax_rate
        if tax_fee is not APIHelper.SKIP:
            self.tax_fee = tax_fee
        if monthly_fee is not APIHelper.SKIP:
            self.monthly_fee = monthly_fee
        if per_invoice_fee is not APIHelper.SKIP:
            self.per_invoice_fee = per_invoice_fee
        if per_quote_fee is not APIHelper.SKIP:
            self.per_quote_fee = per_quote_fee
        if require_pay_in_full is not APIHelper.SKIP:
            self.require_pay_in_full = require_pay_in_full
        if selectable is not APIHelper.SKIP:
            self.selectable = selectable
        if reportable is not APIHelper.SKIP:
            self.reportable = reportable
        if portfolio_id is not APIHelper.SKIP:
            self.portfolio_id = portfolio_id
        if location_id is not APIHelper.SKIP:
            self.location_id = location_id
        if id is not APIHelper.SKIP:
            self.id = id
        if created_ts is not APIHelper.SKIP:
            self.created_ts = created_ts
        if modified_ts is not APIHelper.SKIP:
            self.modified_ts = modified_ts
        if created_user_id is not APIHelper.SKIP:
            self.created_user_id = created_user_id
        if modified_user_id is not APIHelper.SKIP:
            self.modified_user_id = modified_user_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else APIHelper.SKIP
        quote_number_format =\
            dictionary.get("quote_number_format")\
            if "quote_number_format" in dictionary.keys()\
                else APIHelper.SKIP
        quote_number_start =\
            dictionary.get("quote_number_start")\
            if "quote_number_start" in dictionary.keys()\
                else APIHelper.SKIP
        quote_number_increment =\
            dictionary.get("quote_number_increment")\
            if "quote_number_increment" in dictionary.keys()\
                else APIHelper.SKIP
        quote_number_current =\
            dictionary.get("quote_number_current")\
            if "quote_number_current" in dictionary.keys()\
                else APIHelper.SKIP
        invoice_number_format =\
            dictionary.get("invoice_number_format")\
            if "invoice_number_format" in dictionary.keys()\
                else APIHelper.SKIP
        invoice_number_start =\
            dictionary.get("invoice_number_start")\
            if "invoice_number_start" in dictionary.keys()\
                else APIHelper.SKIP
        invoice_number_increment =\
            dictionary.get("invoice_number_increment")\
            if "invoice_number_increment" in dictionary.keys()\
                else APIHelper.SKIP
        invoice_number_current =\
            dictionary.get("invoice_number_current")\
            if "invoice_number_current" in dictionary.keys()\
                else APIHelper.SKIP
        tax_rate =\
            dictionary.get("tax_rate")\
            if dictionary.get("tax_rate")\
                else APIHelper.SKIP
        tax_fee =\
            dictionary.get("tax_fee")\
            if "tax_fee" in dictionary.keys()\
                else APIHelper.SKIP
        monthly_fee =\
            dictionary.get("monthly_fee")\
            if "monthly_fee" in dictionary.keys()\
                else APIHelper.SKIP
        per_invoice_fee =\
            dictionary.get("per_invoice_fee")\
            if dictionary.get("per_invoice_fee")\
                else APIHelper.SKIP
        per_quote_fee =\
            dictionary.get("per_quote_fee")\
            if dictionary.get("per_quote_fee")\
                else APIHelper.SKIP
        require_pay_in_full =\
            dictionary.get("require_pay_in_full")\
            if "require_pay_in_full" in dictionary.keys()\
                else APIHelper.SKIP
        selectable =\
            dictionary.get("selectable")\
            if "selectable" in dictionary.keys()\
                else APIHelper.SKIP
        reportable =\
            dictionary.get("reportable")\
            if "reportable" in dictionary.keys()\
                else APIHelper.SKIP
        portfolio_id =\
            dictionary.get("portfolio_id")\
            if "portfolio_id" in dictionary.keys()\
                else APIHelper.SKIP
        location_id =\
            dictionary.get("location_id")\
            if dictionary.get("location_id")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        created_ts =\
            dictionary.get("created_ts")\
            if dictionary.get("created_ts")\
                else APIHelper.SKIP
        modified_ts =\
            dictionary.get("modified_ts")\
            if dictionary.get("modified_ts")\
                else APIHelper.SKIP
        created_user_id =\
            dictionary.get("created_user_id")\
            if "created_user_id" in dictionary.keys()\
                else APIHelper.SKIP
        modified_user_id =\
            dictionary.get("modified_user_id")\
            if "modified_user_id" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(title,
                   quote_number_format,
                   quote_number_start,
                   quote_number_increment,
                   quote_number_current,
                   invoice_number_format,
                   invoice_number_start,
                   invoice_number_increment,
                   invoice_number_current,
                   tax_rate,
                   tax_fee,
                   monthly_fee,
                   per_invoice_fee,
                   per_quote_fee,
                   require_pay_in_full,
                   selectable,
                   reportable,
                   portfolio_id,
                   location_id,
                   id,
                   created_ts,
                   modified_ts,
                   created_user_id,
                   modified_user_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _quote_number_format=(
            self.quote_number_format
            if hasattr(self, "quote_number_format")
            else None
        )
        _quote_number_start=(
            self.quote_number_start
            if hasattr(self, "quote_number_start")
            else None
        )
        _quote_number_increment=(
            self.quote_number_increment
            if hasattr(self, "quote_number_increment")
            else None
        )
        _quote_number_current=(
            self.quote_number_current
            if hasattr(self, "quote_number_current")
            else None
        )
        _invoice_number_format=(
            self.invoice_number_format
            if hasattr(self, "invoice_number_format")
            else None
        )
        _invoice_number_start=(
            self.invoice_number_start
            if hasattr(self, "invoice_number_start")
            else None
        )
        _invoice_number_increment=(
            self.invoice_number_increment
            if hasattr(self, "invoice_number_increment")
            else None
        )
        _invoice_number_current=(
            self.invoice_number_current
            if hasattr(self, "invoice_number_current")
            else None
        )
        _tax_rate=(
            self.tax_rate
            if hasattr(self, "tax_rate")
            else None
        )
        _tax_fee=(
            self.tax_fee
            if hasattr(self, "tax_fee")
            else None
        )
        _monthly_fee=(
            self.monthly_fee
            if hasattr(self, "monthly_fee")
            else None
        )
        _per_invoice_fee=(
            self.per_invoice_fee
            if hasattr(self, "per_invoice_fee")
            else None
        )
        _per_quote_fee=(
            self.per_quote_fee
            if hasattr(self, "per_quote_fee")
            else None
        )
        _require_pay_in_full=(
            self.require_pay_in_full
            if hasattr(self, "require_pay_in_full")
            else None
        )
        _selectable=(
            self.selectable
            if hasattr(self, "selectable")
            else None
        )
        _reportable=(
            self.reportable
            if hasattr(self, "reportable")
            else None
        )
        _portfolio_id=(
            self.portfolio_id
            if hasattr(self, "portfolio_id")
            else None
        )
        _location_id=(
            self.location_id
            if hasattr(self, "location_id")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _created_ts=(
            self.created_ts
            if hasattr(self, "created_ts")
            else None
        )
        _modified_ts=(
            self.modified_ts
            if hasattr(self, "modified_ts")
            else None
        )
        _created_user_id=(
            self.created_user_id
            if hasattr(self, "created_user_id")
            else None
        )
        _modified_user_id=(
            self.modified_user_id
            if hasattr(self, "modified_user_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"title={_title!r}, "
            f"quote_number_format={_quote_number_format!r}, "
            f"quote_number_start={_quote_number_start!r}, "
            f"quote_number_increment={_quote_number_increment!r}, "
            f"quote_number_current={_quote_number_current!r}, "
            f"invoice_number_format={_invoice_number_format!r}, "
            f"invoice_number_start={_invoice_number_start!r}, "
            f"invoice_number_increment={_invoice_number_increment!r}, "
            f"invoice_number_current={_invoice_number_current!r}, "
            f"tax_rate={_tax_rate!r}, "
            f"tax_fee={_tax_fee!r}, "
            f"monthly_fee={_monthly_fee!r}, "
            f"per_invoice_fee={_per_invoice_fee!r}, "
            f"per_quote_fee={_per_quote_fee!r}, "
            f"require_pay_in_full={_require_pay_in_full!r}, "
            f"selectable={_selectable!r}, "
            f"reportable={_reportable!r}, "
            f"portfolio_id={_portfolio_id!r}, "
            f"location_id={_location_id!r}, "
            f"id={_id!r}, "
            f"created_ts={_created_ts!r}, "
            f"modified_ts={_modified_ts!r}, "
            f"created_user_id={_created_user_id!r}, "
            f"modified_user_id={_modified_user_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _quote_number_format=(
            self.quote_number_format
            if hasattr(self, "quote_number_format")
            else None
        )
        _quote_number_start=(
            self.quote_number_start
            if hasattr(self, "quote_number_start")
            else None
        )
        _quote_number_increment=(
            self.quote_number_increment
            if hasattr(self, "quote_number_increment")
            else None
        )
        _quote_number_current=(
            self.quote_number_current
            if hasattr(self, "quote_number_current")
            else None
        )
        _invoice_number_format=(
            self.invoice_number_format
            if hasattr(self, "invoice_number_format")
            else None
        )
        _invoice_number_start=(
            self.invoice_number_start
            if hasattr(self, "invoice_number_start")
            else None
        )
        _invoice_number_increment=(
            self.invoice_number_increment
            if hasattr(self, "invoice_number_increment")
            else None
        )
        _invoice_number_current=(
            self.invoice_number_current
            if hasattr(self, "invoice_number_current")
            else None
        )
        _tax_rate=(
            self.tax_rate
            if hasattr(self, "tax_rate")
            else None
        )
        _tax_fee=(
            self.tax_fee
            if hasattr(self, "tax_fee")
            else None
        )
        _monthly_fee=(
            self.monthly_fee
            if hasattr(self, "monthly_fee")
            else None
        )
        _per_invoice_fee=(
            self.per_invoice_fee
            if hasattr(self, "per_invoice_fee")
            else None
        )
        _per_quote_fee=(
            self.per_quote_fee
            if hasattr(self, "per_quote_fee")
            else None
        )
        _require_pay_in_full=(
            self.require_pay_in_full
            if hasattr(self, "require_pay_in_full")
            else None
        )
        _selectable=(
            self.selectable
            if hasattr(self, "selectable")
            else None
        )
        _reportable=(
            self.reportable
            if hasattr(self, "reportable")
            else None
        )
        _portfolio_id=(
            self.portfolio_id
            if hasattr(self, "portfolio_id")
            else None
        )
        _location_id=(
            self.location_id
            if hasattr(self, "location_id")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _created_ts=(
            self.created_ts
            if hasattr(self, "created_ts")
            else None
        )
        _modified_ts=(
            self.modified_ts
            if hasattr(self, "modified_ts")
            else None
        )
        _created_user_id=(
            self.created_user_id
            if hasattr(self, "created_user_id")
            else None
        )
        _modified_user_id=(
            self.modified_user_id
            if hasattr(self, "modified_user_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"title={_title!s}, "
            f"quote_number_format={_quote_number_format!s}, "
            f"quote_number_start={_quote_number_start!s}, "
            f"quote_number_increment={_quote_number_increment!s}, "
            f"quote_number_current={_quote_number_current!s}, "
            f"invoice_number_format={_invoice_number_format!s}, "
            f"invoice_number_start={_invoice_number_start!s}, "
            f"invoice_number_increment={_invoice_number_increment!s}, "
            f"invoice_number_current={_invoice_number_current!s}, "
            f"tax_rate={_tax_rate!s}, "
            f"tax_fee={_tax_fee!s}, "
            f"monthly_fee={_monthly_fee!s}, "
            f"per_invoice_fee={_per_invoice_fee!s}, "
            f"per_quote_fee={_per_quote_fee!s}, "
            f"require_pay_in_full={_require_pay_in_full!s}, "
            f"selectable={_selectable!s}, "
            f"reportable={_reportable!s}, "
            f"portfolio_id={_portfolio_id!s}, "
            f"location_id={_location_id!s}, "
            f"id={_id!s}, "
            f"created_ts={_created_ts!s}, "
            f"modified_ts={_modified_ts!s}, "
            f"created_user_id={_created_user_id!s}, "
            f"modified_user_id={_modified_user_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
