"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper
from fortisapi.models.merchant_risk_indicator import (
    MerchantRiskIndicator,
)


class Purchase(object):
    """Implementation of the 'Purchase' model.

    Contains purchase information

    Attributes:
        purchase_install_data (int): Indicates the maximum number of authorizations
            permitted for installment payments.  The fields is required if the
            Merchant and Cardholder have agreed to installment payments, i.e. if 3DS
            Requestor Authentication Indicator = 03. Omitted if not an installment
            payment authentication.  Starting from EMV 3DS 2.3.1: Additionally this
            field is required for device_channel = 03 (3RI) if three_ri_ind = 02.
        merchant_risk_indicator (MerchantRiskIndicator): Contains purchase information
        purchase_amount (int): Purchase amount in minor units of currency with all
            punctuation removed. When used in conjunction with the Purchase Currency
            Exponent field, proper punctuation can be calculated. Example: If the
            purchase amount is USD 123.45, element will contain the value 12345. The
            field is limited to maximum 48 characters.  This field is required for
            02-NPA message category if 3DS Requestor Authentication Indicator = 02 or
            03.   This field is always required for message_category = 01 (PA).
            Starting from EMV 3DS 2.3.1: Additionally this field is required for
            message_category = 02-NPA if three_ri_ind = 01, 02, 06, 07, 08, 09, or 11.
        purchase_currency (str): Currency in which purchase amount is expressed. The
            value is limited to 3 numeric characters and is represented by the ISO
            4217 three-digit currency code, except 955-964 and 999.  This field is
            always required for message_category = 01-PA.   It is required for
            message_category = 02-NPA if 3DS Requestor Authentication Indicator = 02
            or 03.  Starting from EMV 3DS 2.3.1: Additionally this field is required
            for message_category = 02-NPA if three_ri_ind = 01, 02, 06, 07, 08, 09,
            or 11.
        purchase_exponent (int): Minor units of currency as specified in the ISO 4217
            currency exponent. The field is limited to 1 character.   This field is
            always required for message_category = 01-PA.   It is required for
            message_category = 02-NPA if 3DS Requestor Authentication Indicator = 02
            or 03.   Example: for currency USD the exponent should be 2, and for Yen
            the exponent should be 0.  Starting from EMV 3DS 2.3.1: Additionally this
            field is required for message_category = 02-NPA if three_ri_ind = 01, 02,
            06, 07, 08, 09, or 11.
        purchase_date (str): Date and time of the purchase, converted into UTC. The
            field is limited to 14 characters, formatted as YYYYMMDDHHMMSS.    This
            field is always required for message_category = 01-PA.   It is required
            for message_category = 02-NPA if 3DS Requestor Authentication Indicator =
            02 or 03.   Starting from EMV 3DS 2.3.1: Additionally this field is
            required for message_category = 02-NPA if three_ri_ind = 01, 02, 06, 07,
            08, 09, or 11.
        recurring_expiry (str): Date after which no further authorizations shall be
            performed. This field is limited to 8 characters, and the accepted format
            is YYYYMMDD.  This field is required if 3DS Requestor Authentication
            Indicator = 02 or 03 and message_category = 01 or 02. Required if there
            is an end date.
        recurring_frequency (int): Indicates the minimum number of days between
            authorizations.  This field is required if 3DS Requestor Authentication
            Indicator = 02 or 03 and frequency_ind = 01.
        transaction_type (TransactionTypeEnum): Identifies the type of transaction
            being authenticated. The values are derived from ISO 8583. This field is
            required in some markets. Otherwise, the field is optional. >01 - Goods /
            Service purchase > >03 - Check Acceptance > >10 - Account Funding > >11 -
            Quasi-Cash Transaction > >28 - Prepaid activation and Loan >
        recurring_amount (int): Recurring amount after first/promotional payment in
            minor units of currency with all punctuation removed. Example: If the
            recurring amount is USD 123.45, element will contain the value 12345. The
            field is limited to maximum 48 characters.  The field is required if
            three_ds_requestor_authentication_ind = 02 or 03 AND three_ri_iInd = 01
            or 02 AND amount_ind = 01. Available for supporting EMV 3DS 2.3.1 and
            later versions.
        recurring_currency (str): Currency in which recurring amount is expressed.
            The value is limited to 3 numeric characters and is represented by the
            ISO 4217 three-digit currency code, except 955-964 and 999.  This field
            is required if recurring_amount is present. Available for supporting EMV
            3DS 2.3.1 and later versions.
        recurring_exponent (int): Minor units of currency as specified in the ISO
            4217 currency exponent. Example: USD = 2, Yen = 0. The value is limited
            to 1 numeric character.  This field is required if recurring_amount is
            present. Available for supporting EMV 3DS 2.3.1 and later versions.
        recurring_date (str): Effective date of new authorized amount following
            first/promotional payment in recurring transaction. The value is limited
            to 8 characters. Accepted format: YYYYMMDD.  This field is required if
            frequency_ind = 01. Available for supporting EMV 3DS 2.3.1 and later
            versions.
        amount_ind (AmountIndEnum): Part of the indication whether the recurring or
            installment payment has a fixed or variable amount.  Starting from EMV
            3DS 2.3.1:   This field is required if
            three_ds_requestor.three_ds_requestor_authentication_ind = 02 or 03.
            This field is required if three_ri_ind= 01 or 02. >01 - Fixed Purchase
            Amount > >02 - Variable Purchase Amount > >03 through 79 - Reserved for
            EMVCo future use (values invalid until defined by EMVCo) > >80 through 99
            - PS-specific value (dependent on the payment scheme type) >
        frequency_ind (str): Part of the indication whether the recurring or
            instalment payment has a fixed or variable frequency.  Starting from EMV
            3DS 2.3.1:   This field is required if
            three_ds_requestor.three_ds_requestor_authentication_ind = 02 or 03.
            This field is required if three_ri_ind= 01 or 02.
        additional_properties (Dict[str, object]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "purchase_install_data": "purchase_install_data",
        "merchant_risk_indicator": "merchant_risk_indicator",
        "purchase_amount": "purchase_amount",
        "purchase_currency": "purchase_currency",
        "purchase_exponent": "purchase_exponent",
        "purchase_date": "purchase_date",
        "recurring_expiry": "recurring_expiry",
        "recurring_frequency": "recurring_frequency",
        "transaction_type": "transaction_type",
        "recurring_amount": "recurring_amount",
        "recurring_currency": "recurring_currency",
        "recurring_exponent": "recurring_exponent",
        "recurring_date": "recurring_date",
        "amount_ind": "amount_ind",
        "frequency_ind": "frequency_ind",
    }

    _optionals = [
        "purchase_install_data",
        "merchant_risk_indicator",
        "purchase_amount",
        "purchase_currency",
        "purchase_exponent",
        "purchase_date",
        "recurring_expiry",
        "recurring_frequency",
        "transaction_type",
        "recurring_amount",
        "recurring_currency",
        "recurring_exponent",
        "recurring_date",
        "amount_ind",
        "frequency_ind",
    ]

    def __init__(
        self,
        purchase_install_data=APIHelper.SKIP,
        merchant_risk_indicator=APIHelper.SKIP,
        purchase_amount=APIHelper.SKIP,
        purchase_currency=APIHelper.SKIP,
        purchase_exponent=APIHelper.SKIP,
        purchase_date=APIHelper.SKIP,
        recurring_expiry=APIHelper.SKIP,
        recurring_frequency=APIHelper.SKIP,
        transaction_type=APIHelper.SKIP,
        recurring_amount=APIHelper.SKIP,
        recurring_currency=APIHelper.SKIP,
        recurring_exponent=APIHelper.SKIP,
        recurring_date=APIHelper.SKIP,
        amount_ind=APIHelper.SKIP,
        frequency_ind=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Purchase instance."""
        # Initialize members of the class
        if purchase_install_data is not APIHelper.SKIP:
            self.purchase_install_data = purchase_install_data
        if merchant_risk_indicator is not APIHelper.SKIP:
            self.merchant_risk_indicator = merchant_risk_indicator
        if purchase_amount is not APIHelper.SKIP:
            self.purchase_amount = purchase_amount
        if purchase_currency is not APIHelper.SKIP:
            self.purchase_currency = purchase_currency
        if purchase_exponent is not APIHelper.SKIP:
            self.purchase_exponent = purchase_exponent
        if purchase_date is not APIHelper.SKIP:
            self.purchase_date = purchase_date
        if recurring_expiry is not APIHelper.SKIP:
            self.recurring_expiry = recurring_expiry
        if recurring_frequency is not APIHelper.SKIP:
            self.recurring_frequency = recurring_frequency
        if transaction_type is not APIHelper.SKIP:
            self.transaction_type = transaction_type
        if recurring_amount is not APIHelper.SKIP:
            self.recurring_amount = recurring_amount
        if recurring_currency is not APIHelper.SKIP:
            self.recurring_currency = recurring_currency
        if recurring_exponent is not APIHelper.SKIP:
            self.recurring_exponent = recurring_exponent
        if recurring_date is not APIHelper.SKIP:
            self.recurring_date = recurring_date
        if amount_ind is not APIHelper.SKIP:
            self.amount_ind = amount_ind
        if frequency_ind is not APIHelper.SKIP:
            self.frequency_ind = frequency_ind

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        purchase_install_data =\
            dictionary.get("purchase_install_data")\
            if dictionary.get("purchase_install_data")\
                else APIHelper.SKIP
        merchant_risk_indicator =\
            MerchantRiskIndicator.from_dictionary(
                dictionary.get("merchant_risk_indicator"))\
                if "merchant_risk_indicator" in dictionary.keys()\
                else APIHelper.SKIP
        purchase_amount =\
            dictionary.get("purchase_amount")\
            if dictionary.get("purchase_amount")\
                else APIHelper.SKIP
        purchase_currency =\
            dictionary.get("purchase_currency")\
            if dictionary.get("purchase_currency")\
                else APIHelper.SKIP
        purchase_exponent =\
            dictionary.get("purchase_exponent")\
            if dictionary.get("purchase_exponent")\
                else APIHelper.SKIP
        purchase_date =\
            dictionary.get("purchase_date")\
            if dictionary.get("purchase_date")\
                else APIHelper.SKIP
        recurring_expiry =\
            dictionary.get("recurring_expiry")\
            if dictionary.get("recurring_expiry")\
                else APIHelper.SKIP
        recurring_frequency =\
            dictionary.get("recurring_frequency")\
            if dictionary.get("recurring_frequency")\
                else APIHelper.SKIP
        transaction_type =\
            dictionary.get("transaction_type")\
            if dictionary.get("transaction_type")\
                else APIHelper.SKIP
        recurring_amount =\
            dictionary.get("recurring_amount")\
            if dictionary.get("recurring_amount")\
                else APIHelper.SKIP
        recurring_currency =\
            dictionary.get("recurring_currency")\
            if dictionary.get("recurring_currency")\
                else APIHelper.SKIP
        recurring_exponent =\
            dictionary.get("recurring_exponent")\
            if dictionary.get("recurring_exponent")\
                else APIHelper.SKIP
        recurring_date =\
            dictionary.get("recurring_date")\
            if dictionary.get("recurring_date")\
                else APIHelper.SKIP
        amount_ind =\
            dictionary.get("amount_ind")\
            if dictionary.get("amount_ind")\
                else APIHelper.SKIP
        frequency_ind =\
            dictionary.get("frequency_ind")\
            if dictionary.get("frequency_ind")\
                else APIHelper.SKIP

        # Clean out expected properties from dictionary
        additional_properties =\
            {k: v for k, v in dictionary.items() if k not in cls._names.values()}

        # Return an object of this model
        return cls(purchase_install_data,
                   merchant_risk_indicator,
                   purchase_amount,
                   purchase_currency,
                   purchase_exponent,
                   purchase_date,
                   recurring_expiry,
                   recurring_frequency,
                   transaction_type,
                   recurring_amount,
                   recurring_currency,
                   recurring_exponent,
                   recurring_date,
                   amount_ind,
                   frequency_ind,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _purchase_install_data=(
            self.purchase_install_data
            if hasattr(self, "purchase_install_data")
            else None
        )
        _merchant_risk_indicator=(
            self.merchant_risk_indicator
            if hasattr(self, "merchant_risk_indicator")
            else None
        )
        _purchase_amount=(
            self.purchase_amount
            if hasattr(self, "purchase_amount")
            else None
        )
        _purchase_currency=(
            self.purchase_currency
            if hasattr(self, "purchase_currency")
            else None
        )
        _purchase_exponent=(
            self.purchase_exponent
            if hasattr(self, "purchase_exponent")
            else None
        )
        _purchase_date=(
            self.purchase_date
            if hasattr(self, "purchase_date")
            else None
        )
        _recurring_expiry=(
            self.recurring_expiry
            if hasattr(self, "recurring_expiry")
            else None
        )
        _recurring_frequency=(
            self.recurring_frequency
            if hasattr(self, "recurring_frequency")
            else None
        )
        _transaction_type=(
            self.transaction_type
            if hasattr(self, "transaction_type")
            else None
        )
        _recurring_amount=(
            self.recurring_amount
            if hasattr(self, "recurring_amount")
            else None
        )
        _recurring_currency=(
            self.recurring_currency
            if hasattr(self, "recurring_currency")
            else None
        )
        _recurring_exponent=(
            self.recurring_exponent
            if hasattr(self, "recurring_exponent")
            else None
        )
        _recurring_date=(
            self.recurring_date
            if hasattr(self, "recurring_date")
            else None
        )
        _amount_ind=(
            self.amount_ind
            if hasattr(self, "amount_ind")
            else None
        )
        _frequency_ind=(
            self.frequency_ind
            if hasattr(self, "frequency_ind")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"purchase_install_data={_purchase_install_data!r}, "
            f"merchant_risk_indicator={_merchant_risk_indicator!r}, "
            f"purchase_amount={_purchase_amount!r}, "
            f"purchase_currency={_purchase_currency!r}, "
            f"purchase_exponent={_purchase_exponent!r}, "
            f"purchase_date={_purchase_date!r}, "
            f"recurring_expiry={_recurring_expiry!r}, "
            f"recurring_frequency={_recurring_frequency!r}, "
            f"transaction_type={_transaction_type!r}, "
            f"recurring_amount={_recurring_amount!r}, "
            f"recurring_currency={_recurring_currency!r}, "
            f"recurring_exponent={_recurring_exponent!r}, "
            f"recurring_date={_recurring_date!r}, "
            f"amount_ind={_amount_ind!r}, "
            f"frequency_ind={_frequency_ind!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _purchase_install_data=(
            self.purchase_install_data
            if hasattr(self, "purchase_install_data")
            else None
        )
        _merchant_risk_indicator=(
            self.merchant_risk_indicator
            if hasattr(self, "merchant_risk_indicator")
            else None
        )
        _purchase_amount=(
            self.purchase_amount
            if hasattr(self, "purchase_amount")
            else None
        )
        _purchase_currency=(
            self.purchase_currency
            if hasattr(self, "purchase_currency")
            else None
        )
        _purchase_exponent=(
            self.purchase_exponent
            if hasattr(self, "purchase_exponent")
            else None
        )
        _purchase_date=(
            self.purchase_date
            if hasattr(self, "purchase_date")
            else None
        )
        _recurring_expiry=(
            self.recurring_expiry
            if hasattr(self, "recurring_expiry")
            else None
        )
        _recurring_frequency=(
            self.recurring_frequency
            if hasattr(self, "recurring_frequency")
            else None
        )
        _transaction_type=(
            self.transaction_type
            if hasattr(self, "transaction_type")
            else None
        )
        _recurring_amount=(
            self.recurring_amount
            if hasattr(self, "recurring_amount")
            else None
        )
        _recurring_currency=(
            self.recurring_currency
            if hasattr(self, "recurring_currency")
            else None
        )
        _recurring_exponent=(
            self.recurring_exponent
            if hasattr(self, "recurring_exponent")
            else None
        )
        _recurring_date=(
            self.recurring_date
            if hasattr(self, "recurring_date")
            else None
        )
        _amount_ind=(
            self.amount_ind
            if hasattr(self, "amount_ind")
            else None
        )
        _frequency_ind=(
            self.frequency_ind
            if hasattr(self, "frequency_ind")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"purchase_install_data={_purchase_install_data!s}, "
            f"merchant_risk_indicator={_merchant_risk_indicator!s}, "
            f"purchase_amount={_purchase_amount!s}, "
            f"purchase_currency={_purchase_currency!s}, "
            f"purchase_exponent={_purchase_exponent!s}, "
            f"purchase_date={_purchase_date!s}, "
            f"recurring_expiry={_recurring_expiry!s}, "
            f"recurring_frequency={_recurring_frequency!s}, "
            f"transaction_type={_transaction_type!s}, "
            f"recurring_amount={_recurring_amount!s}, "
            f"recurring_currency={_recurring_currency!s}, "
            f"recurring_exponent={_recurring_exponent!s}, "
            f"recurring_date={_recurring_date!s}, "
            f"amount_ind={_amount_ind!s}, "
            f"frequency_ind={_frequency_ind!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
