"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Recipients(object):
    """Implementation of the 'Recipients' enum.

    Indicates the intended recipient(s) of the broadcasted information. This field is
    required.
    >01 - 3DS SDK
    >
    >02 - 3DS Server
    >
    >03 - DS
    >
    >04 - ACS
    >

    Attributes:
        ENUM_01: The enum member of type str.
        ENUM_02: The enum member of type str.
        ENUM_03: The enum member of type str.
        ENUM_04: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    ENUM_01 = "01"

    ENUM_02 = "02"

    ENUM_03 = "03"

    ENUM_04 = "04"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
