"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper
from fortisapi.models.links_1 import Links1
from fortisapi.models.list_6 import List6
from fortisapi.models.pagination_1 import Pagination1
from fortisapi.models.sort_1 import Sort1


class ResponseLocationsCollection(object):
    """Implementation of the 'responseLocationsCollection' model.

    Attributes:
        mtype (Type35): The model property of type Type35.
        list (List[List6]): Resource Members
        links (Links1): The model property of type Links1.
        pagination (Pagination1): The model property of type Pagination1.
        sort (Sort1): The model property of type Sort1.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "list": "list",
        "links": "links",
        "pagination": "pagination",
        "sort": "sort",
    }

    _optionals = [
        "mtype",
        "list",
        "links",
        "pagination",
        "sort",
    ]

    def __init__(
        self,
        mtype=APIHelper.SKIP,
        list=APIHelper.SKIP,
        links=APIHelper.SKIP,
        pagination=APIHelper.SKIP,
        sort=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ResponseLocationsCollection instance."""
        # Initialize members of the class
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if list is not APIHelper.SKIP:
            self.list = list
        if links is not APIHelper.SKIP:
            self.links = links
        if pagination is not APIHelper.SKIP:
            self.pagination = pagination
        if sort is not APIHelper.SKIP:
            self.sort = sort

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        list = None
        if dictionary.get("list") is not None:
            list = [
                List6.from_dictionary(x)
                    for x in dictionary.get("list")
            ]
        else:
            list = APIHelper.SKIP
        links =\
            Links1.from_dictionary(
                dictionary.get("links"))\
                if "links" in dictionary.keys()\
                else APIHelper.SKIP
        pagination =\
            Pagination1.from_dictionary(
                dictionary.get("pagination"))\
                if "pagination" in dictionary.keys()\
                else APIHelper.SKIP
        sort =\
            Sort1.from_dictionary(
                dictionary.get("sort"))\
                if "sort" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   list,
                   links,
                   pagination,
                   sort,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _list=(
            self.list
            if hasattr(self, "list")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _pagination=(
            self.pagination
            if hasattr(self, "pagination")
            else None
        )
        _sort=(
            self.sort
            if hasattr(self, "sort")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"list={_list!r}, "
            f"links={_links!r}, "
            f"pagination={_pagination!r}, "
            f"sort={_sort!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _list=(
            self.list
            if hasattr(self, "list")
            else None
        )
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _pagination=(
            self.pagination
            if hasattr(self, "pagination")
            else None
        )
        _sort=(
            self.sort
            if hasattr(self, "sort")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"list={_list!s}, "
            f"links={_links!s}, "
            f"pagination={_pagination!s}, "
            f"sort={_sort!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
