"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class SchemeIdEnum(object):
    """Implementation of the 'SchemeId' enum.

    ID for the scheme to which the Cardholder's acctNumber belongs to. It will be
    used to identify the Scheme from the 3DS Server configuration.

    Attributes:
        VISA: The enum member of type str.
        MASTERCARD: The enum member of type str.
        ENUM_AMERICAN EXPRESS: The enum member of type str.
        DINERS: The enum member of type str.
        additional_properties (Dict[str, object]): The additional properties for the
            model.

    """

    VISA = "Visa"

    MASTERCARD = "Mastercard"

    ENUM_AMERICAN_EXPRESS = "American Express"

    DINERS = "Diners"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
