"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper


class Settings(object):
    """Implementation of the 'Settings' model.

    Attributes:
        enabled (bool): Enabled
        columns (float): Columns
        rows (float): Rows
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "enabled": "enabled",
        "columns": "columns",
        "rows": "rows",
    }

    _optionals = [
        "enabled",
        "columns",
        "rows",
    ]

    def __init__(
        self,
        enabled=APIHelper.SKIP,
        columns=APIHelper.SKIP,
        rows=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Settings instance."""
        # Initialize members of the class
        if enabled is not APIHelper.SKIP:
            self.enabled = enabled
        if columns is not APIHelper.SKIP:
            self.columns = columns
        if rows is not APIHelper.SKIP:
            self.rows = rows

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        enabled =\
            dictionary.get("enabled")\
            if "enabled" in dictionary.keys()\
                else APIHelper.SKIP
        columns =\
            dictionary.get("columns")\
            if dictionary.get("columns")\
                else APIHelper.SKIP
        rows =\
            dictionary.get("rows")\
            if dictionary.get("rows")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(enabled,
                   columns,
                   rows,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _enabled=(
            self.enabled
            if hasattr(self, "enabled")
            else None
        )
        _columns=(
            self.columns
            if hasattr(self, "columns")
            else None
        )
        _rows=(
            self.rows
            if hasattr(self, "rows")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"enabled={_enabled!r}, "
            f"columns={_columns!r}, "
            f"rows={_rows!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _enabled=(
            self.enabled
            if hasattr(self, "enabled")
            else None
        )
        _columns=(
            self.columns
            if hasattr(self, "columns")
            else None
        )
        _rows=(
            self.rows
            if hasattr(self, "rows")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"enabled={_enabled!s}, "
            f"columns={_columns!s}, "
            f"rows={_rows!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
