"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class ThreeDsRequestorSpcSupport(object):
    """Implementation of the 'ThreeDsRequestorSpcSupport' enum.

    Indicate if the 3DS Requestor supports the SPC authentication.
    This field is required if device_channel = 02 (BRW) and it is supported by the
    3DS Requestor.
    Available for supporting EMV 3DS 2.3.1 and later versions.
    >Y - Supported
    >

    Attributes:
        Y: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    Y = "Y"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
