"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class TransactionStatus(object):
    """Implementation of the 'TransactionStatus' enum.

    Indicates whether a transaction qualifies as an authenticated transaction.
    >Y - Authentication / Account verification successful
    >
    >N - Not authenticated / Account not verified; Transaction denied
    >
    >U - Authentication / Account verification could not be performed; technical or
    other problem
    >
    >C - In order to complete the authentication, a challenge is required
    >
    >R - Authentication / Account verification Rejected. Issuer is rejecting
    authentication/verification and request that authorization not be attempted
    >
    >A - Attempts processing performed; Not authenticated / verified, but a proof of
    attempt authentication / verification is provided
    >
    >D - In order to complete the authentication, a challenge is required. Decoupled
    Authentication confirmed. (Only if the 3DS Server has initiated authentication
    with EMV 3DS 2.2.0 version or greater)
    >
    >I - Informational Only; 3DS Requestor challenge preference acknowledged. (Only
    if the 3DS Server has initiated authentication with EMV 3DS 2.2.0 version or
    greater)
    >

    Attributes:
        Y: The enum member of type str.
        N: The enum member of type str.
        U: The enum member of type str.
        C: The enum member of type str.
        R: The enum member of type str.
        A: The enum member of type str.
        D: The enum member of type str.
        I: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    Y = "Y"

    N = "N"

    U = "U"

    C = "C"

    R = "R"

    A = "A"

    D = "D"

    I = "I"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
