"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper


class V1WalletProviderApplePayValidateMerchantRequest(object):
    """Implementation of the 'V1WalletProviderApplePayValidateMerchantRequest' model.

    Attributes:
        url (str): Url obtained in the ApplePay button click event. Apple's URL that
            needs to be called to validate merchant.
        merchant_id (str): Merchant ID
        domain_name (str): Domain Name
        display_name (str): Title
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "url": "url",
        "merchant_id": "merchantId",
        "domain_name": "domainName",
        "display_name": "displayName",
    }

    def __init__(
        self,
        url=None,
        merchant_id=None,
        domain_name=None,
        display_name=None,
        additional_properties=None):
        """Initialize a V1WalletProviderApplePayValidateMerchantRequest instance."""
        # Initialize members of the class
        self.url = url
        self.merchant_id = merchant_id
        self.domain_name = domain_name
        self.display_name = display_name

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else None
        merchant_id =\
            dictionary.get("merchantId")\
            if dictionary.get("merchantId")\
                else None
        domain_name =\
            dictionary.get("domainName")\
            if dictionary.get("domainName")\
                else None
        display_name =\
            dictionary.get("displayName")\
            if dictionary.get("displayName")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(url,
                   merchant_id,
                   domain_name,
                   display_name,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _url=self.url
        _merchant_id=self.merchant_id
        _domain_name=self.domain_name
        _display_name=self.display_name
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"url={_url!r}, "
            f"merchant_id={_merchant_id!r}, "
            f"domain_name={_domain_name!r}, "
            f"display_name={_display_name!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _url=self.url
        _merchant_id=self.merchant_id
        _domain_name=self.domain_name
        _display_name=self.display_name
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"url={_url!s}, "
            f"merchant_id={_merchant_id!s}, "
            f"domain_name={_domain_name!s}, "
            f"display_name={_display_name!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
