"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper
from fortisapi.models.additional_amount import (
    AdditionalAmount,
)
from fortisapi.models.billing_address_1 import (
    BillingAddress1,
)
from fortisapi.models.identity_verification import (
    IdentityVerification,
)


class V1TransactionsCashSaleRequest(object):
    """Implementation of the 'V1 Transactions Cash Sale Request' model.

    Attributes:
        additional_amounts (List[AdditionalAmount]): Additional amounts
        billing_address (BillingAddress1): Billing Address Object
        checkin_date (str): Checkin Date - The time difference between checkin_date
            and checkout_date must be less than or equal to 99 days. NOTE: if
            checkin_date is in the future, set the advance_deposit to 1 >Required if
            merchant industry type is lodging.  >
        checkout_date (str): Checkout Date - The time difference between checkin_date
            and checkout_date must be less than or equal to 99 days. >Required if
            merchant industry type is lodging. >
        clerk_number (str): Clerk or Employee Identifier
        contact_api_id (str): This can be supplied in place of contact_id if you
            would like to use a contact for the transaction and are using your own
            custom api_id's to track contacts in the system.
        contact_id (str): If contact_id is provided, ensure it belongs to the same
            location as the transaction. You cannot move transaction across locations.
        custom_data (Any): A field that allows custom JSON to be entered to store
            extra data.
        customer_id (str): Can be used by Merchants to identify Contacts in our
            system by an ID from another system.
        description (str): Description
        identity_verification (IdentityVerification): Identity Verification
        iias_ind (IiasIndEnum): Possible values are '0', '1','2'
        image_front (str): A base64 encoded string for the image.  Used with Check21
            ACH transactions.
        image_back (str): A base64 encoded string for the image.  Used with Check21
            ACH transactions.
        installment (bool): Flag that is allowed to be passed on card not present
            industries to signify the transaction is a fixed installment plan
            transaction.
        installment_number (int): If this is a fixed installment plan and installment
            field is being passed as 1, then this field must have a vlue of 1-999
            specifying the current installment number that is running.
        installment_count (int): If this is a fixed installment plan and installment
            field is being passed as 1, then this field must have a vlue of 1-999
            specifying the total number of installments on the plan. This number must
            be grater than or equal to installment_number.
        recurring_flag (RecurringFlagEnum): Recurring Flag
        installment_counter (int): Installment Counter
        installment_total (int): Installment Total
        subscription (bool): Subscription
        standing_order (bool): Standing Order
        location_api_id (str): This can be supplied in place of location_id for the
            transaction if you are using your own custom api_id's for your locations.
        location_id (str): A valid Location Id to associate the transaction with.
        product_transaction_id (str): The Product's method (cc/ach) has to match the
            action. If not provided, the API will use the default configured for the
            Location.
        advance_deposit (bool): Advance Deposit
        no_show (bool): Used in Lodging
        notification_email_address (str): If email is supplied then receipt will be
            emailed
        order_number (str): Required for CC transactions , if merchant's deposit
            account's duplicate check per batch has 'order_number' field
        po_number (str): Purchase Order number
        quick_invoice_id (str): Can be used to associate a transaction to a Quick
            Invoice.  Quick Invoice transactions will have a value for this field
            automatically.
        recurring (bool): Flag that is allowed to be passed on card not present
            industries to signify the transaction is an ongoing recurring
            transaction. Possible values to send are 0 or 1. This field must be 0 or
            not present if installment is sent as 1.
        recurring_number (int): If this is an ongoing recurring and recurring field
            is being passed as 1, then this field must have a vlue of 1-999
            specifying the current recurring number that is running.
        room_num (str): Used in Lodging
        room_rate (int): Required if merchant industry type is lodging.
        save_account (bool): Specifies to save account to contacts profile if
            account_number/track_data is present with either contact_id or
            contact_api_id in params.
        save_account_title (str): If saving token while running a transaction, this
            will be the title of the token.
        subtotal_amount (int): This field is allowed and required for transactions
            that have a product where surcharge is configured. Use only integer
            numbers, so $10.99 will be 1099.
        surcharge_amount (int): This field is allowed and required for transactions
            that have a product where surcharge is configured. Use only integer
            numbers, so $10.99 will be 1099.
        tags (List[str]): Tags
        tax (int): Amount of Sales tax - If supplied, this amount should be included
            in the total transaction_amount field. Use only integer numbers, so
            $10.99 will be 1099.
        tip_amount (int): Optional tip amount. Tip is not supported for lodging and
            ecommerce merchants. Use only integer numbers, so $10.99 will be 1099.
        transaction_amount (int): Amount of the transaction. This should always be
            the desired settle amount of the transaction. Use only integer numbers,
            so $10.99 will be 1099.
        secondary_amount (int): Retained Amount of the transaction. This should
            always be less than transaction amount. Use only integer numbers, so
            $10.99 will be 1099
        transaction_api_id (str): See api_id page for more details
        transaction_c_1 (str): Custom field 1 for api users to store custom data
        transaction_c_2 (str): Custom field 2 for api users to store custom data
        transaction_c_3 (str): Custom field 3 for api users to store custom data
        bank_funded_only_override (bool): Bank Funded Only Override
        allow_partial_authorization_override (bool): Allow Partial Authorization
            Override
        auto_decline_cvv_override (bool): Auto Decline CVV Override
        auto_decline_street_override (bool): Auto Decline Street Override
        auto_decline_zip_override (bool): Auto Decline Zip Override
        ebt_type (EbtTypeEnum): EBT Type
        account_holder_name (str): For CC, this is the 'Name (as it appears) on
            Card'. For ACH, this is the 'Name on Account'. >Required for ACH
            transactions if account_vault_id is not provided. For CC transactions
            that are run through a terminal, this field may be overwritten by data
            acquired from the credit card track data. >
        response_message (str): Response Message
        additional_properties (Dict[str, object]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "transaction_amount": "transaction_amount",
        "additional_amounts": "additional_amounts",
        "billing_address": "billing_address",
        "checkin_date": "checkin_date",
        "checkout_date": "checkout_date",
        "clerk_number": "clerk_number",
        "contact_api_id": "contact_api_id",
        "contact_id": "contact_id",
        "custom_data": "custom_data",
        "customer_id": "customer_id",
        "description": "description",
        "identity_verification": "identity_verification",
        "iias_ind": "iias_ind",
        "image_front": "image_front",
        "image_back": "image_back",
        "installment": "installment",
        "installment_number": "installment_number",
        "installment_count": "installment_count",
        "recurring_flag": "recurring_flag",
        "installment_counter": "installment_counter",
        "installment_total": "installment_total",
        "subscription": "subscription",
        "standing_order": "standing_order",
        "location_api_id": "location_api_id",
        "location_id": "location_id",
        "product_transaction_id": "product_transaction_id",
        "advance_deposit": "advance_deposit",
        "no_show": "no_show",
        "notification_email_address": "notification_email_address",
        "order_number": "order_number",
        "po_number": "po_number",
        "quick_invoice_id": "quick_invoice_id",
        "recurring": "recurring",
        "recurring_number": "recurring_number",
        "room_num": "room_num",
        "room_rate": "room_rate",
        "save_account": "save_account",
        "save_account_title": "save_account_title",
        "subtotal_amount": "subtotal_amount",
        "surcharge_amount": "surcharge_amount",
        "tags": "tags",
        "tax": "tax",
        "tip_amount": "tip_amount",
        "secondary_amount": "secondary_amount",
        "transaction_api_id": "transaction_api_id",
        "transaction_c_1": "transaction_c1",
        "transaction_c_2": "transaction_c2",
        "transaction_c_3": "transaction_c3",
        "bank_funded_only_override": "bank_funded_only_override",
        "allow_partial_authorization_override": "allow_partial_authorization_override",
        "auto_decline_cvv_override": "auto_decline_cvv_override",
        "auto_decline_street_override": "auto_decline_street_override",
        "auto_decline_zip_override": "auto_decline_zip_override",
        "ebt_type": "ebt_type",
        "account_holder_name": "account_holder_name",
        "response_message": "response_message",
    }

    _optionals = [
        "additional_amounts",
        "billing_address",
        "checkin_date",
        "checkout_date",
        "clerk_number",
        "contact_api_id",
        "contact_id",
        "custom_data",
        "customer_id",
        "description",
        "identity_verification",
        "iias_ind",
        "image_front",
        "image_back",
        "installment",
        "installment_number",
        "installment_count",
        "recurring_flag",
        "installment_counter",
        "installment_total",
        "subscription",
        "standing_order",
        "location_api_id",
        "location_id",
        "product_transaction_id",
        "advance_deposit",
        "no_show",
        "notification_email_address",
        "order_number",
        "po_number",
        "quick_invoice_id",
        "recurring",
        "recurring_number",
        "room_num",
        "room_rate",
        "save_account",
        "save_account_title",
        "subtotal_amount",
        "surcharge_amount",
        "tags",
        "tax",
        "tip_amount",
        "secondary_amount",
        "transaction_api_id",
        "transaction_c_1",
        "transaction_c_2",
        "transaction_c_3",
        "bank_funded_only_override",
        "allow_partial_authorization_override",
        "auto_decline_cvv_override",
        "auto_decline_street_override",
        "auto_decline_zip_override",
        "ebt_type",
        "account_holder_name",
        "response_message",
    ]

    _nullables = [
        "checkin_date",
        "checkout_date",
        "clerk_number",
        "contact_api_id",
        "contact_id",
        "customer_id",
        "description",
        "iias_ind",
        "image_front",
        "image_back",
        "installment_number",
        "installment_count",
        "recurring_flag",
        "installment_counter",
        "installment_total",
        "location_api_id",
        "location_id",
        "product_transaction_id",
        "notification_email_address",
        "order_number",
        "po_number",
        "quick_invoice_id",
        "recurring_number",
        "room_num",
        "room_rate",
        "save_account_title",
        "subtotal_amount",
        "surcharge_amount",
        "tags",
        "tax",
        "tip_amount",
        "secondary_amount",
        "transaction_api_id",
        "transaction_c_1",
        "transaction_c_2",
        "transaction_c_3",
        "ebt_type",
        "account_holder_name",
        "response_message",
    ]

    def __init__(
        self,
        transaction_amount=None,
        additional_amounts=APIHelper.SKIP,
        billing_address=APIHelper.SKIP,
        checkin_date=APIHelper.SKIP,
        checkout_date=APIHelper.SKIP,
        clerk_number=APIHelper.SKIP,
        contact_api_id=APIHelper.SKIP,
        contact_id=APIHelper.SKIP,
        custom_data=APIHelper.SKIP,
        customer_id=APIHelper.SKIP,
        description=APIHelper.SKIP,
        identity_verification=APIHelper.SKIP,
        iias_ind=APIHelper.SKIP,
        image_front=APIHelper.SKIP,
        image_back=APIHelper.SKIP,
        installment=APIHelper.SKIP,
        installment_number=APIHelper.SKIP,
        installment_count=APIHelper.SKIP,
        recurring_flag=APIHelper.SKIP,
        installment_counter=APIHelper.SKIP,
        installment_total=APIHelper.SKIP,
        subscription=APIHelper.SKIP,
        standing_order=APIHelper.SKIP,
        location_api_id=APIHelper.SKIP,
        location_id=APIHelper.SKIP,
        product_transaction_id=APIHelper.SKIP,
        advance_deposit=APIHelper.SKIP,
        no_show=APIHelper.SKIP,
        notification_email_address=APIHelper.SKIP,
        order_number=APIHelper.SKIP,
        po_number=APIHelper.SKIP,
        quick_invoice_id=APIHelper.SKIP,
        recurring=APIHelper.SKIP,
        recurring_number=APIHelper.SKIP,
        room_num=APIHelper.SKIP,
        room_rate=APIHelper.SKIP,
        save_account=APIHelper.SKIP,
        save_account_title=APIHelper.SKIP,
        subtotal_amount=APIHelper.SKIP,
        surcharge_amount=APIHelper.SKIP,
        tags=APIHelper.SKIP,
        tax=APIHelper.SKIP,
        tip_amount=APIHelper.SKIP,
        secondary_amount=APIHelper.SKIP,
        transaction_api_id=APIHelper.SKIP,
        transaction_c_1=APIHelper.SKIP,
        transaction_c_2=APIHelper.SKIP,
        transaction_c_3=APIHelper.SKIP,
        bank_funded_only_override=APIHelper.SKIP,
        allow_partial_authorization_override=APIHelper.SKIP,
        auto_decline_cvv_override=APIHelper.SKIP,
        auto_decline_street_override=APIHelper.SKIP,
        auto_decline_zip_override=APIHelper.SKIP,
        ebt_type=APIHelper.SKIP,
        account_holder_name=APIHelper.SKIP,
        response_message=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a V1TransactionsCashSaleRequest instance."""
        # Initialize members of the class
        if additional_amounts is not APIHelper.SKIP:
            self.additional_amounts = additional_amounts
        if billing_address is not APIHelper.SKIP:
            self.billing_address = billing_address
        if checkin_date is not APIHelper.SKIP:
            self.checkin_date = checkin_date
        if checkout_date is not APIHelper.SKIP:
            self.checkout_date = checkout_date
        if clerk_number is not APIHelper.SKIP:
            self.clerk_number = clerk_number
        if contact_api_id is not APIHelper.SKIP:
            self.contact_api_id = contact_api_id
        if contact_id is not APIHelper.SKIP:
            self.contact_id = contact_id
        if custom_data is not APIHelper.SKIP:
            self.custom_data = custom_data
        if customer_id is not APIHelper.SKIP:
            self.customer_id = customer_id
        if description is not APIHelper.SKIP:
            self.description = description
        if identity_verification is not APIHelper.SKIP:
            self.identity_verification = identity_verification
        if iias_ind is not APIHelper.SKIP:
            self.iias_ind = iias_ind
        if image_front is not APIHelper.SKIP:
            self.image_front = image_front
        if image_back is not APIHelper.SKIP:
            self.image_back = image_back
        if installment is not APIHelper.SKIP:
            self.installment = installment
        if installment_number is not APIHelper.SKIP:
            self.installment_number = installment_number
        if installment_count is not APIHelper.SKIP:
            self.installment_count = installment_count
        if recurring_flag is not APIHelper.SKIP:
            self.recurring_flag = recurring_flag
        if installment_counter is not APIHelper.SKIP:
            self.installment_counter = installment_counter
        if installment_total is not APIHelper.SKIP:
            self.installment_total = installment_total
        if subscription is not APIHelper.SKIP:
            self.subscription = subscription
        if standing_order is not APIHelper.SKIP:
            self.standing_order = standing_order
        if location_api_id is not APIHelper.SKIP:
            self.location_api_id = location_api_id
        if location_id is not APIHelper.SKIP:
            self.location_id = location_id
        if product_transaction_id is not APIHelper.SKIP:
            self.product_transaction_id = product_transaction_id
        if advance_deposit is not APIHelper.SKIP:
            self.advance_deposit = advance_deposit
        if no_show is not APIHelper.SKIP:
            self.no_show = no_show
        if notification_email_address is not APIHelper.SKIP:
            self.notification_email_address = notification_email_address
        if order_number is not APIHelper.SKIP:
            self.order_number = order_number
        if po_number is not APIHelper.SKIP:
            self.po_number = po_number
        if quick_invoice_id is not APIHelper.SKIP:
            self.quick_invoice_id = quick_invoice_id
        if recurring is not APIHelper.SKIP:
            self.recurring = recurring
        if recurring_number is not APIHelper.SKIP:
            self.recurring_number = recurring_number
        if room_num is not APIHelper.SKIP:
            self.room_num = room_num
        if room_rate is not APIHelper.SKIP:
            self.room_rate = room_rate
        if save_account is not APIHelper.SKIP:
            self.save_account = save_account
        if save_account_title is not APIHelper.SKIP:
            self.save_account_title = save_account_title
        if subtotal_amount is not APIHelper.SKIP:
            self.subtotal_amount = subtotal_amount
        if surcharge_amount is not APIHelper.SKIP:
            self.surcharge_amount = surcharge_amount
        if tags is not APIHelper.SKIP:
            self.tags = tags
        if tax is not APIHelper.SKIP:
            self.tax = tax
        if tip_amount is not APIHelper.SKIP:
            self.tip_amount = tip_amount
        self.transaction_amount = transaction_amount
        if secondary_amount is not APIHelper.SKIP:
            self.secondary_amount = secondary_amount
        if transaction_api_id is not APIHelper.SKIP:
            self.transaction_api_id = transaction_api_id
        if transaction_c_1 is not APIHelper.SKIP:
            self.transaction_c_1 = transaction_c_1
        if transaction_c_2 is not APIHelper.SKIP:
            self.transaction_c_2 = transaction_c_2
        if transaction_c_3 is not APIHelper.SKIP:
            self.transaction_c_3 = transaction_c_3
        if bank_funded_only_override is not APIHelper.SKIP:
            self.bank_funded_only_override = bank_funded_only_override
        if allow_partial_authorization_override is not APIHelper.SKIP:
            self.allow_partial_authorization_override =\
                 allow_partial_authorization_override
        if auto_decline_cvv_override is not APIHelper.SKIP:
            self.auto_decline_cvv_override = auto_decline_cvv_override
        if auto_decline_street_override is not APIHelper.SKIP:
            self.auto_decline_street_override = auto_decline_street_override
        if auto_decline_zip_override is not APIHelper.SKIP:
            self.auto_decline_zip_override = auto_decline_zip_override
        if ebt_type is not APIHelper.SKIP:
            self.ebt_type = ebt_type
        if account_holder_name is not APIHelper.SKIP:
            self.account_holder_name = account_holder_name
        if response_message is not APIHelper.SKIP:
            self.response_message = response_message

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        transaction_amount =\
            dictionary.get("transaction_amount")\
            if dictionary.get("transaction_amount")\
                else None
        additional_amounts = None
        if dictionary.get("additional_amounts") is not None:
            additional_amounts = [
                AdditionalAmount.from_dictionary(x)
                    for x in dictionary.get("additional_amounts")
            ]
        else:
            additional_amounts = APIHelper.SKIP
        billing_address =\
            BillingAddress1.from_dictionary(
                dictionary.get("billing_address"))\
                if "billing_address" in dictionary.keys()\
                else APIHelper.SKIP
        checkin_date =\
            dictionary.get("checkin_date")\
            if "checkin_date" in dictionary.keys()\
                else APIHelper.SKIP
        checkout_date =\
            dictionary.get("checkout_date")\
            if "checkout_date" in dictionary.keys()\
                else APIHelper.SKIP
        clerk_number =\
            dictionary.get("clerk_number")\
            if "clerk_number" in dictionary.keys()\
                else APIHelper.SKIP
        contact_api_id =\
            dictionary.get("contact_api_id")\
            if "contact_api_id" in dictionary.keys()\
                else APIHelper.SKIP
        contact_id =\
            dictionary.get("contact_id")\
            if "contact_id" in dictionary.keys()\
                else APIHelper.SKIP
        custom_data =\
            dictionary.get("custom_data")\
            if dictionary.get("custom_data")\
                else APIHelper.SKIP
        customer_id =\
            dictionary.get("customer_id")\
            if "customer_id" in dictionary.keys()\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if "description" in dictionary.keys()\
                else APIHelper.SKIP
        identity_verification =\
            IdentityVerification.from_dictionary(
                dictionary.get("identity_verification"))\
                if "identity_verification" in dictionary.keys()\
                else APIHelper.SKIP
        iias_ind =\
            dictionary.get("iias_ind")\
            if "iias_ind" in dictionary.keys()\
                else APIHelper.SKIP
        image_front =\
            dictionary.get("image_front")\
            if "image_front" in dictionary.keys()\
                else APIHelper.SKIP
        image_back =\
            dictionary.get("image_back")\
            if "image_back" in dictionary.keys()\
                else APIHelper.SKIP
        installment =\
            dictionary.get("installment")\
            if "installment" in dictionary.keys()\
                else APIHelper.SKIP
        installment_number =\
            dictionary.get("installment_number")\
            if "installment_number" in dictionary.keys()\
                else APIHelper.SKIP
        installment_count =\
            dictionary.get("installment_count")\
            if "installment_count" in dictionary.keys()\
                else APIHelper.SKIP
        recurring_flag =\
            dictionary.get("recurring_flag")\
            if "recurring_flag" in dictionary.keys()\
                else APIHelper.SKIP
        installment_counter =\
            dictionary.get("installment_counter")\
            if "installment_counter" in dictionary.keys()\
                else APIHelper.SKIP
        installment_total =\
            dictionary.get("installment_total")\
            if "installment_total" in dictionary.keys()\
                else APIHelper.SKIP
        subscription =\
            dictionary.get("subscription")\
            if "subscription" in dictionary.keys()\
                else APIHelper.SKIP
        standing_order =\
            dictionary.get("standing_order")\
            if "standing_order" in dictionary.keys()\
                else APIHelper.SKIP
        location_api_id =\
            dictionary.get("location_api_id")\
            if "location_api_id" in dictionary.keys()\
                else APIHelper.SKIP
        location_id =\
            dictionary.get("location_id")\
            if "location_id" in dictionary.keys()\
                else APIHelper.SKIP
        product_transaction_id =\
            dictionary.get("product_transaction_id")\
            if "product_transaction_id" in dictionary.keys()\
                else APIHelper.SKIP
        advance_deposit =\
            dictionary.get("advance_deposit")\
            if "advance_deposit" in dictionary.keys()\
                else APIHelper.SKIP
        no_show =\
            dictionary.get("no_show")\
            if "no_show" in dictionary.keys()\
                else APIHelper.SKIP
        notification_email_address =\
            dictionary.get("notification_email_address")\
            if "notification_email_address" in dictionary.keys()\
                else APIHelper.SKIP
        order_number =\
            dictionary.get("order_number")\
            if "order_number" in dictionary.keys()\
                else APIHelper.SKIP
        po_number =\
            dictionary.get("po_number")\
            if "po_number" in dictionary.keys()\
                else APIHelper.SKIP
        quick_invoice_id =\
            dictionary.get("quick_invoice_id")\
            if "quick_invoice_id" in dictionary.keys()\
                else APIHelper.SKIP
        recurring =\
            dictionary.get("recurring")\
            if "recurring" in dictionary.keys()\
                else APIHelper.SKIP
        recurring_number =\
            dictionary.get("recurring_number")\
            if "recurring_number" in dictionary.keys()\
                else APIHelper.SKIP
        room_num =\
            dictionary.get("room_num")\
            if "room_num" in dictionary.keys()\
                else APIHelper.SKIP
        room_rate =\
            dictionary.get("room_rate")\
            if "room_rate" in dictionary.keys()\
                else APIHelper.SKIP
        save_account =\
            dictionary.get("save_account")\
            if "save_account" in dictionary.keys()\
                else APIHelper.SKIP
        save_account_title =\
            dictionary.get("save_account_title")\
            if "save_account_title" in dictionary.keys()\
                else APIHelper.SKIP
        subtotal_amount =\
            dictionary.get("subtotal_amount")\
            if "subtotal_amount" in dictionary.keys()\
                else APIHelper.SKIP
        surcharge_amount =\
            dictionary.get("surcharge_amount")\
            if "surcharge_amount" in dictionary.keys()\
                else APIHelper.SKIP
        tags =\
            dictionary.get("tags")\
            if "tags" in dictionary.keys()\
                else APIHelper.SKIP
        tax =\
            dictionary.get("tax")\
            if "tax" in dictionary.keys()\
                else APIHelper.SKIP
        tip_amount =\
            dictionary.get("tip_amount")\
            if "tip_amount" in dictionary.keys()\
                else APIHelper.SKIP
        secondary_amount =\
            dictionary.get("secondary_amount")\
            if "secondary_amount" in dictionary.keys()\
                else APIHelper.SKIP
        transaction_api_id =\
            dictionary.get("transaction_api_id")\
            if "transaction_api_id" in dictionary.keys()\
                else APIHelper.SKIP
        transaction_c_1 =\
            dictionary.get("transaction_c1")\
            if "transaction_c1" in dictionary.keys()\
                else APIHelper.SKIP
        transaction_c_2 =\
            dictionary.get("transaction_c2")\
            if "transaction_c2" in dictionary.keys()\
                else APIHelper.SKIP
        transaction_c_3 =\
            dictionary.get("transaction_c3")\
            if "transaction_c3" in dictionary.keys()\
                else APIHelper.SKIP
        bank_funded_only_override =\
            dictionary.get("bank_funded_only_override")\
            if "bank_funded_only_override" in dictionary.keys()\
                else APIHelper.SKIP
        allow_partial_authorization_override =\
            dictionary.get("allow_partial_authorization_override")\
            if "allow_partial_authorization_override" in dictionary.keys()\
                else APIHelper.SKIP
        auto_decline_cvv_override =\
            dictionary.get("auto_decline_cvv_override")\
            if "auto_decline_cvv_override" in dictionary.keys()\
                else APIHelper.SKIP
        auto_decline_street_override =\
            dictionary.get("auto_decline_street_override")\
            if "auto_decline_street_override" in dictionary.keys()\
                else APIHelper.SKIP
        auto_decline_zip_override =\
            dictionary.get("auto_decline_zip_override")\
            if "auto_decline_zip_override" in dictionary.keys()\
                else APIHelper.SKIP
        ebt_type =\
            dictionary.get("ebt_type")\
            if "ebt_type" in dictionary.keys()\
                else APIHelper.SKIP
        account_holder_name =\
            dictionary.get("account_holder_name")\
            if "account_holder_name" in dictionary.keys()\
                else APIHelper.SKIP
        response_message =\
            dictionary.get("response_message")\
            if "response_message" in dictionary.keys()\
                else APIHelper.SKIP

        # Clean out expected properties from dictionary
        additional_properties =\
            {k: v for k, v in dictionary.items() if k not in cls._names.values()}

        # Return an object of this model
        return cls(transaction_amount,
                   additional_amounts,
                   billing_address,
                   checkin_date,
                   checkout_date,
                   clerk_number,
                   contact_api_id,
                   contact_id,
                   custom_data,
                   customer_id,
                   description,
                   identity_verification,
                   iias_ind,
                   image_front,
                   image_back,
                   installment,
                   installment_number,
                   installment_count,
                   recurring_flag,
                   installment_counter,
                   installment_total,
                   subscription,
                   standing_order,
                   location_api_id,
                   location_id,
                   product_transaction_id,
                   advance_deposit,
                   no_show,
                   notification_email_address,
                   order_number,
                   po_number,
                   quick_invoice_id,
                   recurring,
                   recurring_number,
                   room_num,
                   room_rate,
                   save_account,
                   save_account_title,
                   subtotal_amount,
                   surcharge_amount,
                   tags,
                   tax,
                   tip_amount,
                   secondary_amount,
                   transaction_api_id,
                   transaction_c_1,
                   transaction_c_2,
                   transaction_c_3,
                   bank_funded_only_override,
                   allow_partial_authorization_override,
                   auto_decline_cvv_override,
                   auto_decline_street_override,
                   auto_decline_zip_override,
                   ebt_type,
                   account_holder_name,
                   response_message,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _additional_amounts=(
            self.additional_amounts
            if hasattr(self, "additional_amounts")
            else None
        )
        _billing_address=(
            self.billing_address
            if hasattr(self, "billing_address")
            else None
        )
        _checkin_date=(
            self.checkin_date
            if hasattr(self, "checkin_date")
            else None
        )
        _checkout_date=(
            self.checkout_date
            if hasattr(self, "checkout_date")
            else None
        )
        _clerk_number=(
            self.clerk_number
            if hasattr(self, "clerk_number")
            else None
        )
        _contact_api_id=(
            self.contact_api_id
            if hasattr(self, "contact_api_id")
            else None
        )
        _contact_id=(
            self.contact_id
            if hasattr(self, "contact_id")
            else None
        )
        _custom_data=(
            self.custom_data
            if hasattr(self, "custom_data")
            else None
        )
        _customer_id=(
            self.customer_id
            if hasattr(self, "customer_id")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _identity_verification=(
            self.identity_verification
            if hasattr(self, "identity_verification")
            else None
        )
        _iias_ind=(
            self.iias_ind
            if hasattr(self, "iias_ind")
            else None
        )
        _image_front=(
            self.image_front
            if hasattr(self, "image_front")
            else None
        )
        _image_back=(
            self.image_back
            if hasattr(self, "image_back")
            else None
        )
        _installment=(
            self.installment
            if hasattr(self, "installment")
            else None
        )
        _installment_number=(
            self.installment_number
            if hasattr(self, "installment_number")
            else None
        )
        _installment_count=(
            self.installment_count
            if hasattr(self, "installment_count")
            else None
        )
        _recurring_flag=(
            self.recurring_flag
            if hasattr(self, "recurring_flag")
            else None
        )
        _installment_counter=(
            self.installment_counter
            if hasattr(self, "installment_counter")
            else None
        )
        _installment_total=(
            self.installment_total
            if hasattr(self, "installment_total")
            else None
        )
        _subscription=(
            self.subscription
            if hasattr(self, "subscription")
            else None
        )
        _standing_order=(
            self.standing_order
            if hasattr(self, "standing_order")
            else None
        )
        _location_api_id=(
            self.location_api_id
            if hasattr(self, "location_api_id")
            else None
        )
        _location_id=(
            self.location_id
            if hasattr(self, "location_id")
            else None
        )
        _product_transaction_id=(
            self.product_transaction_id
            if hasattr(self, "product_transaction_id")
            else None
        )
        _advance_deposit=(
            self.advance_deposit
            if hasattr(self, "advance_deposit")
            else None
        )
        _no_show=(
            self.no_show
            if hasattr(self, "no_show")
            else None
        )
        _notification_email_address=(
            self.notification_email_address
            if hasattr(self, "notification_email_address")
            else None
        )
        _order_number=(
            self.order_number
            if hasattr(self, "order_number")
            else None
        )
        _po_number=(
            self.po_number
            if hasattr(self, "po_number")
            else None
        )
        _quick_invoice_id=(
            self.quick_invoice_id
            if hasattr(self, "quick_invoice_id")
            else None
        )
        _recurring=(
            self.recurring
            if hasattr(self, "recurring")
            else None
        )
        _recurring_number=(
            self.recurring_number
            if hasattr(self, "recurring_number")
            else None
        )
        _room_num=(
            self.room_num
            if hasattr(self, "room_num")
            else None
        )
        _room_rate=(
            self.room_rate
            if hasattr(self, "room_rate")
            else None
        )
        _save_account=(
            self.save_account
            if hasattr(self, "save_account")
            else None
        )
        _save_account_title=(
            self.save_account_title
            if hasattr(self, "save_account_title")
            else None
        )
        _subtotal_amount=(
            self.subtotal_amount
            if hasattr(self, "subtotal_amount")
            else None
        )
        _surcharge_amount=(
            self.surcharge_amount
            if hasattr(self, "surcharge_amount")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _tax=(
            self.tax
            if hasattr(self, "tax")
            else None
        )
        _tip_amount=(
            self.tip_amount
            if hasattr(self, "tip_amount")
            else None
        )
        _transaction_amount=self.transaction_amount
        _secondary_amount=(
            self.secondary_amount
            if hasattr(self, "secondary_amount")
            else None
        )
        _transaction_api_id=(
            self.transaction_api_id
            if hasattr(self, "transaction_api_id")
            else None
        )
        _transaction_c_1=(
            self.transaction_c_1
            if hasattr(self, "transaction_c_1")
            else None
        )
        _transaction_c_2=(
            self.transaction_c_2
            if hasattr(self, "transaction_c_2")
            else None
        )
        _transaction_c_3=(
            self.transaction_c_3
            if hasattr(self, "transaction_c_3")
            else None
        )
        _bank_funded_only_override=(
            self.bank_funded_only_override
            if hasattr(self, "bank_funded_only_override")
            else None
        )
        _allow_partial_authorization_override=(
            self.allow_partial_authorization_override
            if hasattr(self, "allow_partial_authorization_override")
            else None
        )
        _auto_decline_cvv_override=(
            self.auto_decline_cvv_override
            if hasattr(self, "auto_decline_cvv_override")
            else None
        )
        _auto_decline_street_override=(
            self.auto_decline_street_override
            if hasattr(self, "auto_decline_street_override")
            else None
        )
        _auto_decline_zip_override=(
            self.auto_decline_zip_override
            if hasattr(self, "auto_decline_zip_override")
            else None
        )
        _ebt_type=(
            self.ebt_type
            if hasattr(self, "ebt_type")
            else None
        )
        _account_holder_name=(
            self.account_holder_name
            if hasattr(self, "account_holder_name")
            else None
        )
        _response_message=(
            self.response_message
            if hasattr(self, "response_message")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"additional_amounts={_additional_amounts!r}, "
            f"billing_address={_billing_address!r}, "
            f"checkin_date={_checkin_date!r}, "
            f"checkout_date={_checkout_date!r}, "
            f"clerk_number={_clerk_number!r}, "
            f"contact_api_id={_contact_api_id!r}, "
            f"contact_id={_contact_id!r}, "
            f"custom_data={_custom_data!r}, "
            f"customer_id={_customer_id!r}, "
            f"description={_description!r}, "
            f"identity_verification={_identity_verification!r}, "
            f"iias_ind={_iias_ind!r}, "
            f"image_front={_image_front!r}, "
            f"image_back={_image_back!r}, "
            f"installment={_installment!r}, "
            f"installment_number={_installment_number!r}, "
            f"installment_count={_installment_count!r}, "
            f"recurring_flag={_recurring_flag!r}, "
            f"installment_counter={_installment_counter!r}, "
            f"installment_total={_installment_total!r}, "
            f"subscription={_subscription!r}, "
            f"standing_order={_standing_order!r}, "
            f"location_api_id={_location_api_id!r}, "
            f"location_id={_location_id!r}, "
            f"product_transaction_id={_product_transaction_id!r}, "
            f"advance_deposit={_advance_deposit!r}, "
            f"no_show={_no_show!r}, "
            f"notification_email_address={_notification_email_address!r}, "
            f"order_number={_order_number!r}, "
            f"po_number={_po_number!r}, "
            f"quick_invoice_id={_quick_invoice_id!r}, "
            f"recurring={_recurring!r}, "
            f"recurring_number={_recurring_number!r}, "
            f"room_num={_room_num!r}, "
            f"room_rate={_room_rate!r}, "
            f"save_account={_save_account!r}, "
            f"save_account_title={_save_account_title!r}, "
            f"subtotal_amount={_subtotal_amount!r}, "
            f"surcharge_amount={_surcharge_amount!r}, "
            f"tags={_tags!r}, "
            f"tax={_tax!r}, "
            f"tip_amount={_tip_amount!r}, "
            f"transaction_amount={_transaction_amount!r}, "
            f"secondary_amount={_secondary_amount!r}, "
            f"transaction_api_id={_transaction_api_id!r}, "
            f"transaction_c_1={_transaction_c_1!r}, "
            f"transaction_c_2={_transaction_c_2!r}, "
            f"transaction_c_3={_transaction_c_3!r}, "
            f"bank_funded_only_override={_bank_funded_only_override!r}, "
            f"allow_partial_authorization_override={_allow_partial_authorization_override!r}, "
            f"auto_decline_cvv_override={_auto_decline_cvv_override!r}, "
            f"auto_decline_street_override={_auto_decline_street_override!r}, "
            f"auto_decline_zip_override={_auto_decline_zip_override!r}, "
            f"ebt_type={_ebt_type!r}, "
            f"account_holder_name={_account_holder_name!r}, "
            f"response_message={_response_message!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _additional_amounts=(
            self.additional_amounts
            if hasattr(self, "additional_amounts")
            else None
        )
        _billing_address=(
            self.billing_address
            if hasattr(self, "billing_address")
            else None
        )
        _checkin_date=(
            self.checkin_date
            if hasattr(self, "checkin_date")
            else None
        )
        _checkout_date=(
            self.checkout_date
            if hasattr(self, "checkout_date")
            else None
        )
        _clerk_number=(
            self.clerk_number
            if hasattr(self, "clerk_number")
            else None
        )
        _contact_api_id=(
            self.contact_api_id
            if hasattr(self, "contact_api_id")
            else None
        )
        _contact_id=(
            self.contact_id
            if hasattr(self, "contact_id")
            else None
        )
        _custom_data=(
            self.custom_data
            if hasattr(self, "custom_data")
            else None
        )
        _customer_id=(
            self.customer_id
            if hasattr(self, "customer_id")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _identity_verification=(
            self.identity_verification
            if hasattr(self, "identity_verification")
            else None
        )
        _iias_ind=(
            self.iias_ind
            if hasattr(self, "iias_ind")
            else None
        )
        _image_front=(
            self.image_front
            if hasattr(self, "image_front")
            else None
        )
        _image_back=(
            self.image_back
            if hasattr(self, "image_back")
            else None
        )
        _installment=(
            self.installment
            if hasattr(self, "installment")
            else None
        )
        _installment_number=(
            self.installment_number
            if hasattr(self, "installment_number")
            else None
        )
        _installment_count=(
            self.installment_count
            if hasattr(self, "installment_count")
            else None
        )
        _recurring_flag=(
            self.recurring_flag
            if hasattr(self, "recurring_flag")
            else None
        )
        _installment_counter=(
            self.installment_counter
            if hasattr(self, "installment_counter")
            else None
        )
        _installment_total=(
            self.installment_total
            if hasattr(self, "installment_total")
            else None
        )
        _subscription=(
            self.subscription
            if hasattr(self, "subscription")
            else None
        )
        _standing_order=(
            self.standing_order
            if hasattr(self, "standing_order")
            else None
        )
        _location_api_id=(
            self.location_api_id
            if hasattr(self, "location_api_id")
            else None
        )
        _location_id=(
            self.location_id
            if hasattr(self, "location_id")
            else None
        )
        _product_transaction_id=(
            self.product_transaction_id
            if hasattr(self, "product_transaction_id")
            else None
        )
        _advance_deposit=(
            self.advance_deposit
            if hasattr(self, "advance_deposit")
            else None
        )
        _no_show=(
            self.no_show
            if hasattr(self, "no_show")
            else None
        )
        _notification_email_address=(
            self.notification_email_address
            if hasattr(self, "notification_email_address")
            else None
        )
        _order_number=(
            self.order_number
            if hasattr(self, "order_number")
            else None
        )
        _po_number=(
            self.po_number
            if hasattr(self, "po_number")
            else None
        )
        _quick_invoice_id=(
            self.quick_invoice_id
            if hasattr(self, "quick_invoice_id")
            else None
        )
        _recurring=(
            self.recurring
            if hasattr(self, "recurring")
            else None
        )
        _recurring_number=(
            self.recurring_number
            if hasattr(self, "recurring_number")
            else None
        )
        _room_num=(
            self.room_num
            if hasattr(self, "room_num")
            else None
        )
        _room_rate=(
            self.room_rate
            if hasattr(self, "room_rate")
            else None
        )
        _save_account=(
            self.save_account
            if hasattr(self, "save_account")
            else None
        )
        _save_account_title=(
            self.save_account_title
            if hasattr(self, "save_account_title")
            else None
        )
        _subtotal_amount=(
            self.subtotal_amount
            if hasattr(self, "subtotal_amount")
            else None
        )
        _surcharge_amount=(
            self.surcharge_amount
            if hasattr(self, "surcharge_amount")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _tax=(
            self.tax
            if hasattr(self, "tax")
            else None
        )
        _tip_amount=(
            self.tip_amount
            if hasattr(self, "tip_amount")
            else None
        )
        _transaction_amount=self.transaction_amount
        _secondary_amount=(
            self.secondary_amount
            if hasattr(self, "secondary_amount")
            else None
        )
        _transaction_api_id=(
            self.transaction_api_id
            if hasattr(self, "transaction_api_id")
            else None
        )
        _transaction_c_1=(
            self.transaction_c_1
            if hasattr(self, "transaction_c_1")
            else None
        )
        _transaction_c_2=(
            self.transaction_c_2
            if hasattr(self, "transaction_c_2")
            else None
        )
        _transaction_c_3=(
            self.transaction_c_3
            if hasattr(self, "transaction_c_3")
            else None
        )
        _bank_funded_only_override=(
            self.bank_funded_only_override
            if hasattr(self, "bank_funded_only_override")
            else None
        )
        _allow_partial_authorization_override=(
            self.allow_partial_authorization_override
            if hasattr(self, "allow_partial_authorization_override")
            else None
        )
        _auto_decline_cvv_override=(
            self.auto_decline_cvv_override
            if hasattr(self, "auto_decline_cvv_override")
            else None
        )
        _auto_decline_street_override=(
            self.auto_decline_street_override
            if hasattr(self, "auto_decline_street_override")
            else None
        )
        _auto_decline_zip_override=(
            self.auto_decline_zip_override
            if hasattr(self, "auto_decline_zip_override")
            else None
        )
        _ebt_type=(
            self.ebt_type
            if hasattr(self, "ebt_type")
            else None
        )
        _account_holder_name=(
            self.account_holder_name
            if hasattr(self, "account_holder_name")
            else None
        )
        _response_message=(
            self.response_message
            if hasattr(self, "response_message")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"additional_amounts={_additional_amounts!s}, "
            f"billing_address={_billing_address!s}, "
            f"checkin_date={_checkin_date!s}, "
            f"checkout_date={_checkout_date!s}, "
            f"clerk_number={_clerk_number!s}, "
            f"contact_api_id={_contact_api_id!s}, "
            f"contact_id={_contact_id!s}, "
            f"custom_data={_custom_data!s}, "
            f"customer_id={_customer_id!s}, "
            f"description={_description!s}, "
            f"identity_verification={_identity_verification!s}, "
            f"iias_ind={_iias_ind!s}, "
            f"image_front={_image_front!s}, "
            f"image_back={_image_back!s}, "
            f"installment={_installment!s}, "
            f"installment_number={_installment_number!s}, "
            f"installment_count={_installment_count!s}, "
            f"recurring_flag={_recurring_flag!s}, "
            f"installment_counter={_installment_counter!s}, "
            f"installment_total={_installment_total!s}, "
            f"subscription={_subscription!s}, "
            f"standing_order={_standing_order!s}, "
            f"location_api_id={_location_api_id!s}, "
            f"location_id={_location_id!s}, "
            f"product_transaction_id={_product_transaction_id!s}, "
            f"advance_deposit={_advance_deposit!s}, "
            f"no_show={_no_show!s}, "
            f"notification_email_address={_notification_email_address!s}, "
            f"order_number={_order_number!s}, "
            f"po_number={_po_number!s}, "
            f"quick_invoice_id={_quick_invoice_id!s}, "
            f"recurring={_recurring!s}, "
            f"recurring_number={_recurring_number!s}, "
            f"room_num={_room_num!s}, "
            f"room_rate={_room_rate!s}, "
            f"save_account={_save_account!s}, "
            f"save_account_title={_save_account_title!s}, "
            f"subtotal_amount={_subtotal_amount!s}, "
            f"surcharge_amount={_surcharge_amount!s}, "
            f"tags={_tags!s}, "
            f"tax={_tax!s}, "
            f"tip_amount={_tip_amount!s}, "
            f"transaction_amount={_transaction_amount!s}, "
            f"secondary_amount={_secondary_amount!s}, "
            f"transaction_api_id={_transaction_api_id!s}, "
            f"transaction_c_1={_transaction_c_1!s}, "
            f"transaction_c_2={_transaction_c_2!s}, "
            f"transaction_c_3={_transaction_c_3!s}, "
            f"bank_funded_only_override={_bank_funded_only_override!s}, "
            f"allow_partial_authorization_override={_allow_partial_authorization_override!s}, "
            f"auto_decline_cvv_override={_auto_decline_cvv_override!s}, "
            f"auto_decline_street_override={_auto_decline_street_override!s}, "
            f"auto_decline_zip_override={_auto_decline_zip_override!s}, "
            f"ebt_type={_ebt_type!s}, "
            f"account_holder_name={_account_holder_name!s}, "
            f"response_message={_response_message!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
