"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper
from fortisapi.models.broad_info_1 import BroadInfo1
from fortisapi.models.browser_information_1 import (
    BrowserInformation1,
)
from fortisapi.models.cardholder_1 import Cardholder1
from fortisapi.models.cardholder_account_1 import (
    CardholderAccount1,
)
from fortisapi.models.challenge_message_extension import (
    ChallengeMessageExtension,
)
from fortisapi.models.device_1 import Device1
from fortisapi.models.message_extension import (
    MessageExtension,
)
from fortisapi.models.multi_transaction_1 import (
    MultiTransaction1,
)
from fortisapi.models.purchase_1 import Purchase1
from fortisapi.models.three_ds_requestor_1 import (
    ThreeDsRequestor1,
)


class V1MerchantThreedsecureAuthenticationRequest(object):
    """Implementation of the 'V1MerchantThreedsecureAuthenticationRequest' model.

    Attributes:
        product_transaction_id (str): Product Transaction ID to associate with this
            3DS request
        preferred_protocol_version (Any): The model property of type Any.
        enforce_preferred_protocol_version (bool): Boolean flag that enforces
            preferred 3D Secure protocol version to be used in 3D Secure
            authentication. The value should be set true to enforce preferred
            version. If value is false or not provided, 3DS Server can fall back to
            next supported 3DS protocol version while initiating 3D Secure
            authentication.
        device_channel (DeviceChannel): The model property of type DeviceChannel.
        message_category (MessageCategory): The model property of type
            MessageCategory.
        three_ds_comp_ind (str): Indicates whether the 3DS Method successfully
            completed. The value is used only when device_channel = 02 (Browser).
            From protocol version 2.3.1 this field is required. >Y - Successfully
            completed > >N - Did not successfully complete > >U - Unavailable - 3DS
            Method URL was not present in the PRes message data for the card range
            associated with the Cardholder Account Number. >
        three_ds_method_id (str): Contains the 3DS Server Transaction ID used during
            the previous execution of the 3DS method. Accepted value length is 36
            characters. Accepted value is a Canonical format as defined in IETF RFC
            4122. May utilise any of the specified versions if the output meets
            specified requirements. This field is required if the 3DS Requestor
            reuses previous 3DS Method execution with device_channel = 02 (BRW).
            Available in EMV 3DS 2.3.1 and later versions.
        three_ds_requestor (ThreeDsRequestor1): The model property of type
            ThreeDsRequestor1.
        three_ds_server_trans_id (uuid|str): Universally unique transaction
            identifier assigned by the 3DS Server to identify a single transaction.
            This value has 36 characters in a format defined in IETF RFC 4122. In
            case 3DS Method is previously invoked, the threeDSServerTransID should be
            sent. If not, 3DS Server will generate a new transaction identifier.  If
            threeDSServerTransID is generated in versioning flow same transaction
            identifier should be used in Authentication flow which combines them as
            one transaction.
        three_ds_requestor_url (str): Fully qualified URL of 3DS Requestor website or
            customer care site.
        cardholder_account (CardholderAccount1): The model property of type
            CardholderAccount1.
        cardholder (Cardholder1): The model property of type Cardholder1.
        purchase (Purchase1): The model property of type Purchase1.
        broad_info (BroadInfo1): The model property of type BroadInfo1.
        message_extension (List[MessageExtension]): Data necessary to support
            requirements not otherwise defined in the 3D Secure message are carried
            in a Message Extension. This field is limited to 81,920 characters and it
            is used in the Authentication Request.  Requirements of this field are
            set by each Directory Server.
        challenge_message_extension (List[ChallengeMessageExtension]): Data necessary
            to support requirements not otherwise defined in the 3D Secure message
            are carried in a Message Extension. This field is limited to 81,920
            characters and it is used in the generating of the ChallengeRequest, if
            challenge is needed.  Requirements of this field are set by each
            Directory Server.
        browser_information (BrowserInformation1): The model property of type
            BrowserInformation1.
        three_ri_ind (Any): The model property of type Any.
        device (Device1): The model property of type Device1.
        multi_transaction (MultiTransaction1): The model property of type
            MultiTransaction1.
        device_id (str): Unique and immutable identifier linked to a device that is
            consistent across 3DS transactions for the specific user device.
            Available for supporting EMV 3DS 2.3.1 and later versions.
        user_id (str): Identifier of the transacting user’s Browser Account ID.
            Available for supporting EMV 3DS 2.3.1 and later versions.
        payee_origin (str): The origin of the payee that will be provided in the SPC
            Transaction Data as a fully qualified URL.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "product_transaction_id": "product_transaction_id",
        "device_channel": "device_channel",
        "message_category": "message_category",
        "three_ds_requestor": "three_ds_requestor",
        "cardholder_account": "cardholder_account",
        "preferred_protocol_version": "preferred_protocol_version",
        "enforce_preferred_protocol_version": "enforce_preferred_protocol_version",
        "three_ds_comp_ind": "three_ds_comp_ind",
        "three_ds_method_id": "three_ds_method_id",
        "three_ds_server_trans_id": "three_ds_server_trans_id",
        "three_ds_requestor_url": "three_ds_requestor_url",
        "cardholder": "cardholder",
        "purchase": "purchase",
        "broad_info": "broad_info",
        "message_extension": "message_extension",
        "challenge_message_extension": "challenge_message_extension",
        "browser_information": "browser_information",
        "three_ri_ind": "three_ri_ind",
        "device": "device",
        "multi_transaction": "multi_transaction",
        "device_id": "device_id",
        "user_id": "user_id",
        "payee_origin": "payee_origin",
    }

    _optionals = [
        "preferred_protocol_version",
        "enforce_preferred_protocol_version",
        "three_ds_comp_ind",
        "three_ds_method_id",
        "three_ds_server_trans_id",
        "three_ds_requestor_url",
        "cardholder",
        "purchase",
        "broad_info",
        "message_extension",
        "challenge_message_extension",
        "browser_information",
        "three_ri_ind",
        "device",
        "multi_transaction",
        "device_id",
        "user_id",
        "payee_origin",
    ]

    _nullables = [
        "three_ds_comp_ind",
        "three_ds_method_id",
        "three_ds_server_trans_id",
        "three_ds_requestor_url",
        "device_id",
        "user_id",
        "payee_origin",
    ]

    def __init__(
        self,
        product_transaction_id=None,
        device_channel=None,
        message_category=None,
        three_ds_requestor=None,
        cardholder_account=None,
        preferred_protocol_version=APIHelper.SKIP,
        enforce_preferred_protocol_version=APIHelper.SKIP,
        three_ds_comp_ind=APIHelper.SKIP,
        three_ds_method_id=APIHelper.SKIP,
        three_ds_server_trans_id=APIHelper.SKIP,
        three_ds_requestor_url=APIHelper.SKIP,
        cardholder=APIHelper.SKIP,
        purchase=APIHelper.SKIP,
        broad_info=APIHelper.SKIP,
        message_extension=APIHelper.SKIP,
        challenge_message_extension=APIHelper.SKIP,
        browser_information=APIHelper.SKIP,
        three_ri_ind=APIHelper.SKIP,
        device=APIHelper.SKIP,
        multi_transaction=APIHelper.SKIP,
        device_id=APIHelper.SKIP,
        user_id=APIHelper.SKIP,
        payee_origin=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a V1MerchantThreedsecureAuthenticationRequest instance."""
        # Initialize members of the class
        self.product_transaction_id = product_transaction_id
        if preferred_protocol_version is not APIHelper.SKIP:
            self.preferred_protocol_version = preferred_protocol_version
        if enforce_preferred_protocol_version is not APIHelper.SKIP:
            self.enforce_preferred_protocol_version =\
                 enforce_preferred_protocol_version
        self.device_channel = device_channel
        self.message_category = message_category
        if three_ds_comp_ind is not APIHelper.SKIP:
            self.three_ds_comp_ind = three_ds_comp_ind
        if three_ds_method_id is not APIHelper.SKIP:
            self.three_ds_method_id = three_ds_method_id
        self.three_ds_requestor = three_ds_requestor
        if three_ds_server_trans_id is not APIHelper.SKIP:
            self.three_ds_server_trans_id = three_ds_server_trans_id
        if three_ds_requestor_url is not APIHelper.SKIP:
            self.three_ds_requestor_url = three_ds_requestor_url
        self.cardholder_account = cardholder_account
        if cardholder is not APIHelper.SKIP:
            self.cardholder = cardholder
        if purchase is not APIHelper.SKIP:
            self.purchase = purchase
        if broad_info is not APIHelper.SKIP:
            self.broad_info = broad_info
        if message_extension is not APIHelper.SKIP:
            self.message_extension = message_extension
        if challenge_message_extension is not APIHelper.SKIP:
            self.challenge_message_extension = challenge_message_extension
        if browser_information is not APIHelper.SKIP:
            self.browser_information = browser_information
        if three_ri_ind is not APIHelper.SKIP:
            self.three_ri_ind = three_ri_ind
        if device is not APIHelper.SKIP:
            self.device = device
        if multi_transaction is not APIHelper.SKIP:
            self.multi_transaction = multi_transaction
        if device_id is not APIHelper.SKIP:
            self.device_id = device_id
        if user_id is not APIHelper.SKIP:
            self.user_id = user_id
        if payee_origin is not APIHelper.SKIP:
            self.payee_origin = payee_origin

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        product_transaction_id =\
            dictionary.get("product_transaction_id")\
            if dictionary.get("product_transaction_id")\
                else None
        device_channel =\
            dictionary.get("device_channel")\
            if dictionary.get("device_channel")\
                else None
        message_category =\
            dictionary.get("message_category")\
            if dictionary.get("message_category")\
                else None
        three_ds_requestor =\
            ThreeDsRequestor1.from_dictionary(
                dictionary.get("three_ds_requestor"))\
                if dictionary.get("three_ds_requestor") else None
        cardholder_account =\
            CardholderAccount1.from_dictionary(
                dictionary.get("cardholder_account"))\
                if dictionary.get("cardholder_account") else None
        preferred_protocol_version =\
            dictionary.get("preferred_protocol_version")\
            if dictionary.get("preferred_protocol_version")\
                else APIHelper.SKIP
        enforce_preferred_protocol_version =\
            dictionary.get("enforce_preferred_protocol_version")\
            if "enforce_preferred_protocol_version" in dictionary.keys()\
                else APIHelper.SKIP
        three_ds_comp_ind =\
            dictionary.get("three_ds_comp_ind")\
            if "three_ds_comp_ind" in dictionary.keys()\
                else APIHelper.SKIP
        three_ds_method_id =\
            dictionary.get("three_ds_method_id")\
            if "three_ds_method_id" in dictionary.keys()\
                else APIHelper.SKIP
        three_ds_server_trans_id =\
            dictionary.get("three_ds_server_trans_id")\
            if "three_ds_server_trans_id" in dictionary.keys()\
                else APIHelper.SKIP
        three_ds_requestor_url =\
            dictionary.get("three_ds_requestor_url")\
            if "three_ds_requestor_url" in dictionary.keys()\
                else APIHelper.SKIP
        cardholder =\
            Cardholder1.from_dictionary(
                dictionary.get("cardholder"))\
                if "cardholder" in dictionary.keys()\
                else APIHelper.SKIP
        purchase =\
            Purchase1.from_dictionary(
                dictionary.get("purchase"))\
                if "purchase" in dictionary.keys()\
                else APIHelper.SKIP
        broad_info =\
            BroadInfo1.from_dictionary(
                dictionary.get("broad_info"))\
                if "broad_info" in dictionary.keys()\
                else APIHelper.SKIP
        message_extension = None
        if dictionary.get("message_extension") is not None:
            message_extension = [
                MessageExtension.from_dictionary(x)
                    for x in dictionary.get("message_extension")
            ]
        else:
            message_extension = APIHelper.SKIP
        challenge_message_extension = None
        if dictionary.get("challenge_message_extension") is not None:
            challenge_message_extension = [
                ChallengeMessageExtension.from_dictionary(x)
                    for x in dictionary.get("challenge_message_extension")
            ]
        else:
            challenge_message_extension = APIHelper.SKIP
        browser_information =\
            BrowserInformation1.from_dictionary(
                dictionary.get("browser_information"))\
                if "browser_information" in dictionary.keys()\
                else APIHelper.SKIP
        three_ri_ind =\
            dictionary.get("three_ri_ind")\
            if dictionary.get("three_ri_ind")\
                else APIHelper.SKIP
        device =\
            Device1.from_dictionary(
                dictionary.get("device"))\
                if "device" in dictionary.keys()\
                else APIHelper.SKIP
        multi_transaction =\
            MultiTransaction1.from_dictionary(
                dictionary.get("multi_transaction"))\
                if "multi_transaction" in dictionary.keys()\
                else APIHelper.SKIP
        device_id =\
            dictionary.get("device_id")\
            if "device_id" in dictionary.keys()\
                else APIHelper.SKIP
        user_id =\
            dictionary.get("user_id")\
            if "user_id" in dictionary.keys()\
                else APIHelper.SKIP
        payee_origin =\
            dictionary.get("payee_origin")\
            if "payee_origin" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(product_transaction_id,
                   device_channel,
                   message_category,
                   three_ds_requestor,
                   cardholder_account,
                   preferred_protocol_version,
                   enforce_preferred_protocol_version,
                   three_ds_comp_ind,
                   three_ds_method_id,
                   three_ds_server_trans_id,
                   three_ds_requestor_url,
                   cardholder,
                   purchase,
                   broad_info,
                   message_extension,
                   challenge_message_extension,
                   browser_information,
                   three_ri_ind,
                   device,
                   multi_transaction,
                   device_id,
                   user_id,
                   payee_origin,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _product_transaction_id=self.product_transaction_id
        _preferred_protocol_version=(
            self.preferred_protocol_version
            if hasattr(self, "preferred_protocol_version")
            else None
        )
        _enforce_preferred_protocol_version=(
            self.enforce_preferred_protocol_version
            if hasattr(self, "enforce_preferred_protocol_version")
            else None
        )
        _device_channel=self.device_channel
        _message_category=self.message_category
        _three_ds_comp_ind=(
            self.three_ds_comp_ind
            if hasattr(self, "three_ds_comp_ind")
            else None
        )
        _three_ds_method_id=(
            self.three_ds_method_id
            if hasattr(self, "three_ds_method_id")
            else None
        )
        _three_ds_requestor=self.three_ds_requestor
        _three_ds_server_trans_id=(
            self.three_ds_server_trans_id
            if hasattr(self, "three_ds_server_trans_id")
            else None
        )
        _three_ds_requestor_url=(
            self.three_ds_requestor_url
            if hasattr(self, "three_ds_requestor_url")
            else None
        )
        _cardholder_account=self.cardholder_account
        _cardholder=(
            self.cardholder
            if hasattr(self, "cardholder")
            else None
        )
        _purchase=(
            self.purchase
            if hasattr(self, "purchase")
            else None
        )
        _broad_info=(
            self.broad_info
            if hasattr(self, "broad_info")
            else None
        )
        _message_extension=(
            self.message_extension
            if hasattr(self, "message_extension")
            else None
        )
        _challenge_message_extension=(
            self.challenge_message_extension
            if hasattr(self, "challenge_message_extension")
            else None
        )
        _browser_information=(
            self.browser_information
            if hasattr(self, "browser_information")
            else None
        )
        _three_ri_ind=(
            self.three_ri_ind
            if hasattr(self, "three_ri_ind")
            else None
        )
        _device=(
            self.device
            if hasattr(self, "device")
            else None
        )
        _multi_transaction=(
            self.multi_transaction
            if hasattr(self, "multi_transaction")
            else None
        )
        _device_id=(
            self.device_id
            if hasattr(self, "device_id")
            else None
        )
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        _payee_origin=(
            self.payee_origin
            if hasattr(self, "payee_origin")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"product_transaction_id={_product_transaction_id!r}, "
            f"preferred_protocol_version={_preferred_protocol_version!r}, "
            f"enforce_preferred_protocol_version={_enforce_preferred_protocol_version!r}, "
            f"device_channel={_device_channel!r}, "
            f"message_category={_message_category!r}, "
            f"three_ds_comp_ind={_three_ds_comp_ind!r}, "
            f"three_ds_method_id={_three_ds_method_id!r}, "
            f"three_ds_requestor={_three_ds_requestor!r}, "
            f"three_ds_server_trans_id={_three_ds_server_trans_id!r}, "
            f"three_ds_requestor_url={_three_ds_requestor_url!r}, "
            f"cardholder_account={_cardholder_account!r}, "
            f"cardholder={_cardholder!r}, "
            f"purchase={_purchase!r}, "
            f"broad_info={_broad_info!r}, "
            f"message_extension={_message_extension!r}, "
            f"challenge_message_extension={_challenge_message_extension!r}, "
            f"browser_information={_browser_information!r}, "
            f"three_ri_ind={_three_ri_ind!r}, "
            f"device={_device!r}, "
            f"multi_transaction={_multi_transaction!r}, "
            f"device_id={_device_id!r}, "
            f"user_id={_user_id!r}, "
            f"payee_origin={_payee_origin!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _product_transaction_id=self.product_transaction_id
        _preferred_protocol_version=(
            self.preferred_protocol_version
            if hasattr(self, "preferred_protocol_version")
            else None
        )
        _enforce_preferred_protocol_version=(
            self.enforce_preferred_protocol_version
            if hasattr(self, "enforce_preferred_protocol_version")
            else None
        )
        _device_channel=self.device_channel
        _message_category=self.message_category
        _three_ds_comp_ind=(
            self.three_ds_comp_ind
            if hasattr(self, "three_ds_comp_ind")
            else None
        )
        _three_ds_method_id=(
            self.three_ds_method_id
            if hasattr(self, "three_ds_method_id")
            else None
        )
        _three_ds_requestor=self.three_ds_requestor
        _three_ds_server_trans_id=(
            self.three_ds_server_trans_id
            if hasattr(self, "three_ds_server_trans_id")
            else None
        )
        _three_ds_requestor_url=(
            self.three_ds_requestor_url
            if hasattr(self, "three_ds_requestor_url")
            else None
        )
        _cardholder_account=self.cardholder_account
        _cardholder=(
            self.cardholder
            if hasattr(self, "cardholder")
            else None
        )
        _purchase=(
            self.purchase
            if hasattr(self, "purchase")
            else None
        )
        _broad_info=(
            self.broad_info
            if hasattr(self, "broad_info")
            else None
        )
        _message_extension=(
            self.message_extension
            if hasattr(self, "message_extension")
            else None
        )
        _challenge_message_extension=(
            self.challenge_message_extension
            if hasattr(self, "challenge_message_extension")
            else None
        )
        _browser_information=(
            self.browser_information
            if hasattr(self, "browser_information")
            else None
        )
        _three_ri_ind=(
            self.three_ri_ind
            if hasattr(self, "three_ri_ind")
            else None
        )
        _device=(
            self.device
            if hasattr(self, "device")
            else None
        )
        _multi_transaction=(
            self.multi_transaction
            if hasattr(self, "multi_transaction")
            else None
        )
        _device_id=(
            self.device_id
            if hasattr(self, "device_id")
            else None
        )
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        _payee_origin=(
            self.payee_origin
            if hasattr(self, "payee_origin")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"product_transaction_id={_product_transaction_id!s}, "
            f"preferred_protocol_version={_preferred_protocol_version!s}, "
            f"enforce_preferred_protocol_version={_enforce_preferred_protocol_version!s}, "
            f"device_channel={_device_channel!s}, "
            f"message_category={_message_category!s}, "
            f"three_ds_comp_ind={_three_ds_comp_ind!s}, "
            f"three_ds_method_id={_three_ds_method_id!s}, "
            f"three_ds_requestor={_three_ds_requestor!s}, "
            f"three_ds_server_trans_id={_three_ds_server_trans_id!s}, "
            f"three_ds_requestor_url={_three_ds_requestor_url!s}, "
            f"cardholder_account={_cardholder_account!s}, "
            f"cardholder={_cardholder!s}, "
            f"purchase={_purchase!s}, "
            f"broad_info={_broad_info!s}, "
            f"message_extension={_message_extension!s}, "
            f"challenge_message_extension={_challenge_message_extension!s}, "
            f"browser_information={_browser_information!s}, "
            f"three_ri_ind={_three_ri_ind!s}, "
            f"device={_device!s}, "
            f"multi_transaction={_multi_transaction!s}, "
            f"device_id={_device_id!s}, "
            f"user_id={_user_id!s}, "
            f"payee_origin={_payee_origin!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
