"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from fortisapi.api_helper import APIHelper
from fortisapi.models.billing_address_7 import (
    BillingAddress7,
)


class V1DeclinedRecurringTransactionPaymentsRequest(object):
    """Implementation of the 'V1DeclinedRecurringTransactionPaymentsRequest' model.

    Attributes:
        declined_recurring_transaction_id (str): Declined Recurring Transaction Id
        account_number (str): Account Number
        account_holder_name (str): Account Holder Name
        exp_date (str): Exp Date
        transaction_amount (int): Transaction Amount
        description (str): Description
        billing_address (BillingAddress7): The model property of type BillingAddress7.
        tags (List[str]): Tags
        replace_account_vault (bool): Replace AccountVault
        save_account (bool): Specifies to save account to contacts profile if
            account_number/track_data is present with either contact_id or
            contact_api_id in params.
        save_account_title (str): If saving token while running a transaction, this
            will be the title of the token.
        subtotal_amount (int): Subtotal Amount
        surcharge_amount (int): Surcharge Amount
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "declined_recurring_transaction_id": "declined_recurring_transaction_id",
        "account_number": "account_number",
        "exp_date": "exp_date",
        "transaction_amount": "transaction_amount",
        "account_holder_name": "account_holder_name",
        "description": "description",
        "billing_address": "billing_address",
        "tags": "tags",
        "replace_account_vault": "replace_account_vault",
        "save_account": "save_account",
        "save_account_title": "save_account_title",
        "subtotal_amount": "subtotal_amount",
        "surcharge_amount": "surcharge_amount",
    }

    _optionals = [
        "account_holder_name",
        "description",
        "billing_address",
        "tags",
        "replace_account_vault",
        "save_account",
        "save_account_title",
        "subtotal_amount",
        "surcharge_amount",
    ]

    _nullables = [
        "account_holder_name",
        "tags",
        "save_account_title",
        "subtotal_amount",
        "surcharge_amount",
    ]

    def __init__(
        self,
        declined_recurring_transaction_id=None,
        account_number=None,
        exp_date=None,
        transaction_amount=None,
        account_holder_name=APIHelper.SKIP,
        description=APIHelper.SKIP,
        billing_address=APIHelper.SKIP,
        tags=APIHelper.SKIP,
        replace_account_vault=APIHelper.SKIP,
        save_account=APIHelper.SKIP,
        save_account_title=APIHelper.SKIP,
        subtotal_amount=APIHelper.SKIP,
        surcharge_amount=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a V1DeclinedRecurringTransactionPaymentsRequest instance."""
        # Initialize members of the class
        self.declined_recurring_transaction_id = declined_recurring_transaction_id
        self.account_number = account_number
        if account_holder_name is not APIHelper.SKIP:
            self.account_holder_name = account_holder_name
        self.exp_date = exp_date
        self.transaction_amount = transaction_amount
        if description is not APIHelper.SKIP:
            self.description = description
        if billing_address is not APIHelper.SKIP:
            self.billing_address = billing_address
        if tags is not APIHelper.SKIP:
            self.tags = tags
        if replace_account_vault is not APIHelper.SKIP:
            self.replace_account_vault = replace_account_vault
        if save_account is not APIHelper.SKIP:
            self.save_account = save_account
        if save_account_title is not APIHelper.SKIP:
            self.save_account_title = save_account_title
        if subtotal_amount is not APIHelper.SKIP:
            self.subtotal_amount = subtotal_amount
        if surcharge_amount is not APIHelper.SKIP:
            self.surcharge_amount = surcharge_amount

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        declined_recurring_transaction_id =\
            dictionary.get("declined_recurring_transaction_id")\
            if dictionary.get("declined_recurring_transaction_id")\
                else None
        account_number =\
            dictionary.get("account_number")\
            if dictionary.get("account_number")\
                else None
        exp_date =\
            dictionary.get("exp_date")\
            if dictionary.get("exp_date")\
                else None
        transaction_amount =\
            dictionary.get("transaction_amount")\
            if dictionary.get("transaction_amount")\
                else None
        account_holder_name =\
            dictionary.get("account_holder_name")\
            if "account_holder_name" in dictionary.keys()\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        billing_address =\
            BillingAddress7.from_dictionary(
                dictionary.get("billing_address"))\
                if "billing_address" in dictionary.keys()\
                else APIHelper.SKIP
        tags =\
            dictionary.get("tags")\
            if "tags" in dictionary.keys()\
                else APIHelper.SKIP
        replace_account_vault =\
            dictionary.get("replace_account_vault")\
            if "replace_account_vault" in dictionary.keys()\
                else APIHelper.SKIP
        save_account =\
            dictionary.get("save_account")\
            if "save_account" in dictionary.keys()\
                else APIHelper.SKIP
        save_account_title =\
            dictionary.get("save_account_title")\
            if "save_account_title" in dictionary.keys()\
                else APIHelper.SKIP
        subtotal_amount =\
            dictionary.get("subtotal_amount")\
            if "subtotal_amount" in dictionary.keys()\
                else APIHelper.SKIP
        surcharge_amount =\
            dictionary.get("surcharge_amount")\
            if "surcharge_amount" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(declined_recurring_transaction_id,
                   account_number,
                   exp_date,
                   transaction_amount,
                   account_holder_name,
                   description,
                   billing_address,
                   tags,
                   replace_account_vault,
                   save_account,
                   save_account_title,
                   subtotal_amount,
                   surcharge_amount,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _declined_recurring_transaction_id=self.declined_recurring_transaction_id
        _account_number=self.account_number
        _account_holder_name=(
            self.account_holder_name
            if hasattr(self, "account_holder_name")
            else None
        )
        _exp_date=self.exp_date
        _transaction_amount=self.transaction_amount
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _billing_address=(
            self.billing_address
            if hasattr(self, "billing_address")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _replace_account_vault=(
            self.replace_account_vault
            if hasattr(self, "replace_account_vault")
            else None
        )
        _save_account=(
            self.save_account
            if hasattr(self, "save_account")
            else None
        )
        _save_account_title=(
            self.save_account_title
            if hasattr(self, "save_account_title")
            else None
        )
        _subtotal_amount=(
            self.subtotal_amount
            if hasattr(self, "subtotal_amount")
            else None
        )
        _surcharge_amount=(
            self.surcharge_amount
            if hasattr(self, "surcharge_amount")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"declined_recurring_transaction_id={_declined_recurring_transaction_id!r}, "
            f"account_number={_account_number!r}, "
            f"account_holder_name={_account_holder_name!r}, "
            f"exp_date={_exp_date!r}, "
            f"transaction_amount={_transaction_amount!r}, "
            f"description={_description!r}, "
            f"billing_address={_billing_address!r}, "
            f"tags={_tags!r}, "
            f"replace_account_vault={_replace_account_vault!r}, "
            f"save_account={_save_account!r}, "
            f"save_account_title={_save_account_title!r}, "
            f"subtotal_amount={_subtotal_amount!r}, "
            f"surcharge_amount={_surcharge_amount!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _declined_recurring_transaction_id=self.declined_recurring_transaction_id
        _account_number=self.account_number
        _account_holder_name=(
            self.account_holder_name
            if hasattr(self, "account_holder_name")
            else None
        )
        _exp_date=self.exp_date
        _transaction_amount=self.transaction_amount
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _billing_address=(
            self.billing_address
            if hasattr(self, "billing_address")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _replace_account_vault=(
            self.replace_account_vault
            if hasattr(self, "replace_account_vault")
            else None
        )
        _save_account=(
            self.save_account
            if hasattr(self, "save_account")
            else None
        )
        _save_account_title=(
            self.save_account_title
            if hasattr(self, "save_account_title")
            else None
        )
        _subtotal_amount=(
            self.subtotal_amount
            if hasattr(self, "subtotal_amount")
            else None
        )
        _surcharge_amount=(
            self.surcharge_amount
            if hasattr(self, "surcharge_amount")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"declined_recurring_transaction_id={_declined_recurring_transaction_id!s}, "
            f"account_number={_account_number!s}, "
            f"account_holder_name={_account_holder_name!s}, "
            f"exp_date={_exp_date!s}, "
            f"transaction_amount={_transaction_amount!s}, "
            f"description={_description!s}, "
            f"billing_address={_billing_address!s}, "
            f"tags={_tags!s}, "
            f"replace_account_vault={_replace_account_vault!s}, "
            f"save_account={_save_account!s}, "
            f"save_account_title={_save_account_title!s}, "
            f"subtotal_amount={_subtotal_amount!s}, "
            f"surcharge_amount={_surcharge_amount!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
